import {describe,it,expect,vi} from "vitest";
import {createSessionController,RetiredSession} from "./session-controller";
import type {MobileBootstrapResponse} from "@stallorder/contracts/mobile/v1";
const session=(token:string)=>({token:token.repeat(43),expiresAt:new Date(Date.now()+3600000).toISOString()});
const deferred=<T>()=>{let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return {promise,resolve};};
function setup(){const state:unknown[]=[];const deps={read:vi.fn().mockResolvedValue(session("a")),write:vi.fn().mockResolvedValue(undefined),device:vi.fn().mockResolvedValue("device"),login:vi.fn().mockResolvedValue({session:session("b")}),rotate:vi.fn().mockResolvedValue({session:session("c")}),revoke:vi.fn().mockResolvedValue({ok:true}),bootstrap:vi.fn().mockResolvedValue({} as MobileBootstrapResponse),changed:(s:unknown)=>state.push(s)};return {deps,state,c:createSessionController(deps)};}
describe("Native session authority races",()=>{
 it("preserves the stored session and generation after offline initialization and reconnect",async()=>{const {c,deps,state}=setup();deps.bootstrap.mockRejectedValue(new TypeError("Network request failed"));await expect(c.initialize()).rejects.toThrow("Network request failed");await expect(c.refresh()).rejects.toThrow("Network request failed");expect(state.at(-1)).toEqual({session:await deps.read.mock.results[0].value,bootstrapData:null,generation:0});expect(deps.write).not.toHaveBeenCalled();expect(deps.revoke).not.toHaveBeenCalled();deps.bootstrap.mockResolvedValue({} as MobileBootstrapResponse);await c.refresh();expect(state.at(-1)).toMatchObject({bootstrapData:{},generation:0});});
 it("retires cached identity when proactive refresh is rejected",async()=>{const {c,deps,state}=setup();deps.read.mockResolvedValue({...session("a"),expiresAt:new Date(Date.now()+1000).toISOString()});deps.rotate.mockRejectedValue({status:401});await expect(c.initialize()).rejects.toEqual({status:401});expect(state.at(-1)).toMatchObject({session:null,bootstrapData:null});expect(deps.write).toHaveBeenLastCalledWith(null);});
 it("retires all private views on a current permission denial",async()=>{const {c,deps,state}=setup();await c.initialize();await expect(c.run(async()=>{throw {status:403};})).rejects.toEqual({status:403});expect(state.at(-1)).toMatchObject({session:null,bootstrapData:null});expect(deps.write).toHaveBeenLastCalledWith(null);});
 it("fences a late A read after logout",async()=>{const {c}=setup();await c.initialize();const response=deferred<string>();const read=c.run(()=>response.promise);await Promise.resolve();const retired=expect(read).rejects.toBeInstanceOf(RetiredSession);await c.signOut();response.resolve("A private data");await retired;});
 it("serializes an already-started secure write before the logout clear",async()=>{const {c,deps}=setup();await c.initialize();const write=deferred<void>();deps.write.mockImplementationOnce(()=>write.promise);const rotate=deferred<{session:ReturnType<typeof session>}>();deps.rotate.mockReturnValueOnce(rotate.promise);const read=c.run(async()=>{throw {status:401};});const rejected=expect(read).rejects.toBeInstanceOf(RetiredSession);await vi.waitFor(()=>expect(deps.rotate).toHaveBeenCalledOnce());rotate.resolve({session:session("c")});await vi.waitFor(()=>expect(deps.write).toHaveBeenCalledTimes(1));const out=c.signOut();write.resolve();await out;await rejected;expect(deps.write.mock.calls.at(-1)).toEqual([null]);expect(deps.revoke).toHaveBeenLastCalledWith(session("c").token,"device");});
 it("revokes the final rotated family without republishing its session",async()=>{const {c,deps,state}=setup();await c.initialize();const pending=deferred<{session:ReturnType<typeof session>}>();deps.rotate.mockReturnValue(pending.promise);const read=c.run(async()=>{throw {status:401};});const rejected=expect(read).rejects.toBeInstanceOf(RetiredSession);await vi.waitFor(()=>expect(deps.rotate).toHaveBeenCalledOnce());const out=c.signOut();const at=state.length;pending.resolve({session:session("c")});await out;await rejected;expect(deps.revoke).toHaveBeenLastCalledWith(session("c").token,"device");expect(state.slice(at)).toEqual([]);});
 it("coalesces parallel 401 refreshes and replays each read at most once",async()=>{const {c,deps}=setup();await c.initialize();const call=vi.fn().mockRejectedValueOnce({status:401}).mockRejectedValueOnce({status:401}).mockResolvedValue("ok");await expect(Promise.all([c.run(call),c.run(call)])).resolves.toEqual(["ok","ok"]);expect(deps.rotate).toHaveBeenCalledOnce();expect(call).toHaveBeenCalledTimes(4);});
 it("reports unconfirmed server revocation after offline local logout",async()=>{const {c,deps}=setup();await c.initialize();deps.revoke.mockRejectedValue(Error("offline"));await expect(c.signOut()).resolves.toBe(false);expect(deps.write).toHaveBeenLastCalledWith(null);await expect(c.run(async()=>"secret")).rejects.toBeInstanceOf(RetiredSession);});
 it("does not let simultaneous sign-in intents share a generation",async()=>{const {c,deps}=setup();await c.initialize();const firstRevoke=deferred<void>();deps.revoke.mockReturnValueOnce(firstRevoke.promise);const a=c.signIn("A","password");const retired=expect(a).rejects.toBeInstanceOf(RetiredSession);await vi.waitFor(()=>expect(deps.write).toHaveBeenCalledWith(null));await c.signIn("B","password");firstRevoke.resolve();await retired;expect(deps.login).toHaveBeenCalledTimes(1);expect(deps.login).toHaveBeenCalledWith("B","password","device");});
});
