import type { OrderStatus, UserRole } from "@prisma/client";

export type Permission =
  | "VIEW_ORDERS"
  | "CREATE_ORDERS"
  | "UPDATE_ORDERS"
  | "CHECKOUT_ORDERS"
  | "MANAGE_PRINT_QUEUE"
  | "VIEW_CASH_SHIFT"
  | "MANAGE_CASH_SHIFT"
  | "REVIEW_CASH_SHIFT"
  | "APPROVE_DISCOUNT"
  | "VIEW_DINING_FLOOR"
  | "MANAGE_PRODUCTS"
  | "MANAGE_ORDERING"
  | "VIEW_REPORTS"
  | "MANAGE_STAFF"
  | "MANAGE_STALL"
  | "MANAGE_ORGANIZATION"
  | "MANAGE_SUBSCRIPTION"
  | "VIEW_BILLING"
  | "MANAGE_SHARED_PRODUCTS"
  | "VIEW_AUDIT_LOGS"
  | "MANAGE_OPERATIONAL_ALERTS"
  | "MANAGE_REPORT_SCHEDULES"
  | "VIEW_KDS"
  | "UPDATE_PRODUCTION_TASKS"
  | "MANAGE_KDS"
  | "MANAGE_CDS"
  | "MANAGE_CAPACITY"
  | "OPERATE_CAPACITY"
  | "MANAGE_STALL_LOCATIONS"
  | "MANAGE_STALL_SCHEDULES"
  | "MANAGE_MARKET_EVENTS"
  | "MANAGE_LINE_INTEGRATION"
  | "MANAGE_DELIVERY_INTEGRATIONS"
  | "MANAGE_PAYMENT_INTEGRATIONS"
  | "REFUND_PROVIDER_PAYMENTS"
  | "USE_ATTENDANCE"
  | "MANAGE_ATTENDANCE"
  | "PLATFORM_ADMIN";

const rolePermissions: Record<UserRole, readonly Permission[]> = {
  PLATFORM_ADMIN: [
    "VIEW_ORDERS",
    "CREATE_ORDERS",
    "UPDATE_ORDERS",
    "CHECKOUT_ORDERS",
    "MANAGE_PRINT_QUEUE",
    "VIEW_CASH_SHIFT",
    "MANAGE_CASH_SHIFT",
    "REVIEW_CASH_SHIFT",
    "APPROVE_DISCOUNT",
    "VIEW_DINING_FLOOR",
    "MANAGE_PRODUCTS",
    "MANAGE_ORDERING",
    "VIEW_REPORTS",
    "MANAGE_STAFF",
    "MANAGE_STALL",
    "MANAGE_ORGANIZATION",
    "MANAGE_SUBSCRIPTION",
    "VIEW_BILLING",
    "MANAGE_SHARED_PRODUCTS",
    "VIEW_AUDIT_LOGS",
    "MANAGE_OPERATIONAL_ALERTS",
    "MANAGE_REPORT_SCHEDULES",
    "VIEW_KDS",
    "UPDATE_PRODUCTION_TASKS",
    "MANAGE_KDS",
    "MANAGE_CDS",
    "MANAGE_CAPACITY",
    "OPERATE_CAPACITY",
    "MANAGE_STALL_LOCATIONS",
    "MANAGE_STALL_SCHEDULES",
    "MANAGE_MARKET_EVENTS",
    "MANAGE_LINE_INTEGRATION",
    "MANAGE_DELIVERY_INTEGRATIONS",
    "MANAGE_PAYMENT_INTEGRATIONS",
    "REFUND_PROVIDER_PAYMENTS",
    "USE_ATTENDANCE",
    "MANAGE_ATTENDANCE",
    "PLATFORM_ADMIN",
  ],
  MERCHANT_OWNER: [],
  MERCHANT_MANAGER: [],
  ORGANIZATION_OWNER: [
    "VIEW_ORDERS",
    "CREATE_ORDERS",
    "UPDATE_ORDERS",
    "CHECKOUT_ORDERS",
    "MANAGE_PRINT_QUEUE",
    "VIEW_CASH_SHIFT",
    "MANAGE_CASH_SHIFT",
    "REVIEW_CASH_SHIFT",
    "APPROVE_DISCOUNT",
    "VIEW_DINING_FLOOR",
    "MANAGE_PRODUCTS",
    "MANAGE_ORDERING",
    "VIEW_REPORTS",
    "MANAGE_STAFF",
    "MANAGE_STALL",
    "MANAGE_ORGANIZATION",
    "MANAGE_SUBSCRIPTION",
    "VIEW_BILLING",
    "MANAGE_SHARED_PRODUCTS",
    "VIEW_AUDIT_LOGS",
    "MANAGE_OPERATIONAL_ALERTS",
    "MANAGE_REPORT_SCHEDULES",
    "VIEW_KDS",
    "UPDATE_PRODUCTION_TASKS",
    "MANAGE_KDS",
    "MANAGE_CDS",
    "MANAGE_CAPACITY",
    "OPERATE_CAPACITY",
    "MANAGE_STALL_LOCATIONS",
    "MANAGE_STALL_SCHEDULES",
    "MANAGE_MARKET_EVENTS",
    "MANAGE_LINE_INTEGRATION",
    "MANAGE_DELIVERY_INTEGRATIONS",
    "MANAGE_PAYMENT_INTEGRATIONS",
    "REFUND_PROVIDER_PAYMENTS",
    "USE_ATTENDANCE",
    "MANAGE_ATTENDANCE",
  ],
  ORGANIZATION_ADMIN: [
    "VIEW_ORDERS",
    "CREATE_ORDERS",
    "UPDATE_ORDERS",
    "CHECKOUT_ORDERS",
    "MANAGE_PRINT_QUEUE",
    "VIEW_CASH_SHIFT",
    "MANAGE_CASH_SHIFT",
    "REVIEW_CASH_SHIFT",
    "APPROVE_DISCOUNT",
    "VIEW_DINING_FLOOR",
    "MANAGE_PRODUCTS",
    "MANAGE_ORDERING",
    "VIEW_REPORTS",
    "MANAGE_STAFF",
    "MANAGE_STALL",
    "MANAGE_SHARED_PRODUCTS",
    "VIEW_AUDIT_LOGS",
    "MANAGE_OPERATIONAL_ALERTS",
    "MANAGE_REPORT_SCHEDULES",
    "VIEW_BILLING",
    "VIEW_KDS",
    "UPDATE_PRODUCTION_TASKS",
    "MANAGE_KDS",
    "MANAGE_CDS",
    "MANAGE_CAPACITY",
    "OPERATE_CAPACITY",
    "MANAGE_STALL_LOCATIONS",
    "MANAGE_STALL_SCHEDULES",
    "MANAGE_MARKET_EVENTS",
    "MANAGE_LINE_INTEGRATION",
    "MANAGE_DELIVERY_INTEGRATIONS",
    "MANAGE_PAYMENT_INTEGRATIONS",
    "REFUND_PROVIDER_PAYMENTS",
    "USE_ATTENDANCE",
    "MANAGE_ATTENDANCE",
  ],
  FINANCE_VIEWER: ["VIEW_REPORTS", "VIEW_BILLING", "VIEW_CASH_SHIFT"],
  STALL_MANAGER: [
    "VIEW_ORDERS",
    "CREATE_ORDERS",
    "UPDATE_ORDERS",
    "CHECKOUT_ORDERS",
    "MANAGE_PRINT_QUEUE",
    "VIEW_CASH_SHIFT",
    "MANAGE_CASH_SHIFT",
    "REVIEW_CASH_SHIFT",
    "APPROVE_DISCOUNT",
    "VIEW_DINING_FLOOR",
    "MANAGE_PRODUCTS",
    "MANAGE_ORDERING",
    "VIEW_REPORTS",
    "MANAGE_STAFF",
    "MANAGE_STALL",
    "MANAGE_OPERATIONAL_ALERTS",
    "VIEW_KDS",
    "UPDATE_PRODUCTION_TASKS",
    "MANAGE_KDS",
    "MANAGE_CDS",
    "MANAGE_CAPACITY",
    "OPERATE_CAPACITY",
    "MANAGE_STALL_LOCATIONS",
    "MANAGE_STALL_SCHEDULES",
    "MANAGE_LINE_INTEGRATION",
    "MANAGE_DELIVERY_INTEGRATIONS",
    "USE_ATTENDANCE",
    "MANAGE_ATTENDANCE",
  ],
  STAFF: ["VIEW_ORDERS", "CREATE_ORDERS", "UPDATE_ORDERS", "CHECKOUT_ORDERS", "MANAGE_PRINT_QUEUE", "VIEW_CASH_SHIFT", "MANAGE_CASH_SHIFT", "VIEW_DINING_FLOOR", "OPERATE_CAPACITY", "USE_ATTENDANCE"],
  KITCHEN: ["VIEW_KDS", "UPDATE_PRODUCTION_TASKS", "USE_ATTENDANCE"],
};

const primaryRoleOrder: readonly UserRole[] = [
  "PLATFORM_ADMIN",
  "ORGANIZATION_OWNER",
  "ORGANIZATION_ADMIN",
  "STALL_MANAGER",
  "STAFF",
  "KITCHEN",
  "FINANCE_VIEWER",
  "MERCHANT_OWNER",
  "MERCHANT_MANAGER",
];

const allowedOrderTransitions: Record<OrderStatus, readonly OrderStatus[]> = {
  WAITING_CONFIRMATION: ["CONFIRMED", "CANCELLED"],
  CONFIRMED: ["PREPARING", "PACKING", "READY", "CANCELLED"],
  PREPARING: ["PACKING", "READY", "CANCELLED"],
  PACKING: ["READY", "CANCELLED"],
  READY: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: [],
  EXPIRED: [],
};

export function hasPermission(role: UserRole, permission: Permission) {
  return rolePermissions[role].includes(permission);
}

export function authorizedStallIdsForPermission(
  stalls: readonly { id: string; roles: readonly UserRole[] }[],
  permission: Permission,
) {
  return stalls
    .filter((stall) => stall.roles.some((role) => hasPermission(role, permission)))
    .map((stall) => stall.id);
}

export function resolvePrimaryRole(roles: readonly UserRole[]) {
  const roleSet = new Set(roles);
  return primaryRoleOrder.find((role) => roleSet.has(role)) ?? null;
}

export function canTransitionOrder(current: OrderStatus, next: OrderStatus, role: UserRole) {
  if (!hasPermission(role, "UPDATE_ORDERS")) return false;
  if (!allowedOrderTransitions[current].includes(next)) return false;
  return true;
}

export const roleLabels: Record<UserRole, string> = {
  PLATFORM_ADMIN: "平台管理員",
  MERCHANT_OWNER: "舊版商戶擁有者",
  MERCHANT_MANAGER: "舊版商戶經理",
  ORGANIZATION_OWNER: "組織擁有者",
  ORGANIZATION_ADMIN: "組織管理員",
  FINANCE_VIEWER: "財務檢視者",
  STALL_MANAGER: "攤位經理",
  STAFF: "店員",
  KITCHEN: "廚房",
};
