import {useState} from 'react';
import {Redirect,router} from "expo-router";
import {Pressable,ScrollView,Text} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {applicationReadResultSchema} from "@stallorder/contracts/operations/v1";
import {useSession} from "../src/auth/session-context";
import {useNativeScope,useNativeRead} from "../src/operations/query";
import {nativeRequest} from "../src/api/operations";
export default function PlatformScreen(){const {bootstrapData,runAuthenticated}=useSession();const scope=useNativeScope();const[page,setPage]=useState(1);const list=useNativeRead(scope.data,"native-applications",{page},()=>runAuthenticated((token,device)=>nativeRequest(token,device,"/operations/admin-applications?pageSize=25&page="+page,applicationReadResultSchema)));if(!bootstrapData)return <Redirect href="/login"/>;if(bootstrapData.principal.platformRole!=="PLATFORM_ADMIN")return <Text accessibilityRole="alert">無權存取平台管理</Text>;return <SafeAreaView style={{flex:1}}><ScrollView contentContainerStyle={{padding:20,gap:12}}><Pressable accessibilityRole="button" style={{minHeight:48,minWidth:48}} onPress={()=>router.back()}><Text>返回</Text></Pressable><Text style={{fontSize:26}}>商家申請・唯讀</Text>{list.error&&<Text accessibilityRole="alert">無法取得申請資料</Text>}{!list.error&&list.data?.rows.map(row=><Pressable key={row.id} accessibilityRole="button" style={{minHeight:48,minWidth:48,padding:12,borderWidth:1}} onPress={()=>router.push({pathname:"/application/[applicationId]",params:{applicationId:row.id}})}><Text>{row.applicationNumber}・{row.merchantName}</Text></Pressable>)}<Pressable accessibilityRole="button" style={{minHeight:48,minWidth:48}} onPress={()=>router.push("/inbox")}><Text>通知與個人偏好</Text></Pressable><Text>第 {page} 頁</Text><Pressable accessibilityRole="button" disabled={page===1||list.isFetching} style={{minHeight:48,minWidth:48}} onPress={()=>setPage(p=>p-1)}><Text>上一頁</Text></Pressable><Pressable accessibilityRole="button" disabled={!list.data||page>=list.data.pagination.totalPages||list.isFetching} style={{minHeight:48,minWidth:48}} onPress={()=>setPage(p=>p+1)}><Text>下一頁</Text></Pressable></ScrollView></SafeAreaView>}
