import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const h = vi.hoisted(() => ({ principal: null as unknown, admin: false, csrf: true, mode: "ok", consent: false, events: [] as unknown[], db: { productFeedback: { create: vi.fn(), findFirst: vi.fn(), findMany: vi.fn(), updateMany: vi.fn(), findUniqueOrThrow: vi.fn() }, organizationMembership: { findFirst: vi.fn() }, stallMembership: { findFirst: vi.fn() }, auditLog: { findFirst: vi.fn() }, $transaction: vi.fn(), $executeRaw: vi.fn() }, rate: vi.fn(), audit: vi.fn() }));
vi.mock("@/lib/prisma", () => ({ prisma: h.db }));
vi.mock("@/lib/auth", () => ({ getRequestPrincipal: async () => h.principal }));
vi.mock("@/lib/authorization", () => ({ authorizePlatformAdminApiRequest: async () => h.admin ? { ok: true, principal: h.principal, requestId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa" } : { ok: false, response: Response.json({ error: "denied" }, { status: h.principal ? 404 : 401 }) } }));
vi.mock("@/lib/csrf", () => ({ validateCsrf: () => h.csrf }));
vi.mock("@/lib/rate-limit", () => ({ checkRateLimit: h.rate }));
vi.mock("@/lib/audit", () => ({ recordAuditEvent: h.audit }));
vi.mock("@/lib/security", () => ({ createRequestId: () => "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", hashClientIp: () => "test-ip" }));
vi.mock("@/server/analytics/product-analytics", async () => { const { createProductAnalytics } = await import("@/server/analytics/analytics-adapter"); return { productAnalytics: createProductAnalytics({ capture(event, signal) { if (h.mode === "throw")
            throw Error("sink"); if (h.mode === "reject")
            return Promise.reject(Error("sink")); if (h.mode === "hang")
            return new Promise(() => { }); if (!signal.aborted)
            h.events.push(event); return Promise.resolve(); }, reset() { h.events.length = 0; } }, async () => h.consent, () => "actor") }; });
import { feedbackHttp } from "./feedback-http";
import { cleanupExpiredFeedback } from "./feedback-service";
const actor = "11111111-1111-4111-8111-111111111111", org = "22222222-2222-4222-8222-222222222222", id = "33333333-3333-4333-8333-333333333333", reference = "44444444-4444-4444-8444-444444444444";
const principal = { sessionId: "session", user: { id: actor, platformRole: null } }, command = { organizationId: null, kind: "ISSUE", message: "<img src=x onerror=alert(1)>" };
const row = { id, organizationId: null, kind: "ISSUE", surface: "MERCHANT", message: command.message, requestId: null, status: "NEW", version: 1, createdAt: new Date("2026-10-01T00:00:00Z"), updatedAt: new Date("2026-10-01T00:00:00Z"), expiresAt: new Date("2026-12-30T00:00:00Z") };
const request = (body: unknown, headers: Record<string, string> = {}) => new Request("http://localhost/api/feedback", { method: "POST", headers: { "content-type": "application/json", ...headers }, body: typeof body === "string" ? body : JSON.stringify(body) });
const query = "from=2026-09-01T00:00:00.000Z&to=2026-10-03T00:00:00.000Z";
beforeEach(() => { vi.clearAllMocks(); h.principal = principal; h.admin = false; h.csrf = true; h.consent = false; h.mode = "ok"; h.events = []; h.rate.mockResolvedValue({ allowed: true }); h.db.productFeedback.create.mockImplementation(async () => ({ id, status: "NEW", version: 1, createdAt: row.createdAt })); h.db.organizationMembership.findFirst.mockResolvedValue(null); h.db.stallMembership.findFirst.mockResolvedValue(null); h.db.auditLog.findFirst.mockResolvedValue(null); h.db.$transaction.mockImplementation(async (fn) => fn(h.db)); h.db.productFeedback.findFirst.mockResolvedValue(row); h.db.productFeedback.findMany.mockResolvedValue([row]); h.db.productFeedback.updateMany.mockResolvedValue({ count: 1 }); h.db.productFeedback.findUniqueOrThrow.mockResolvedValue({ ...row, status: "CLOSED", version: 2 }); h.db.$executeRaw.mockResolvedValue(0); });
afterEach(() => vi.useRealTimers());
describe("actual feedback HTTP + persistence seam", () => {
    it("authenticates/CSRF before sensitive lookup or create", async () => { h.principal = null; expect((await feedbackHttp(request(command), "submit")).status).toBe(401); h.principal = principal; h.csrf = false; expect((await feedbackHttp(request(command), "submit")).status).toBe(403); expect(h.db.productFeedback.create).not.toHaveBeenCalled(); expect(h.db.organizationMembership.findFirst).not.toHaveBeenCalled(); });
    it.each([undefined, "1"])("enforces actual UTF8 12KB with Content-Length %s", async (length) => { const body = JSON.stringify({ ...command, message: "茶".repeat(5000) }); const result = await feedbackHttp(request(body, length ? { "content-length": length } : {}), "submit"); expect(result.status).toBe(413); expect(h.db.productFeedback.create).not.toHaveBeenCalled(); });
    it.each([{ ...command, profileId: actor }, { ...command, analyticsConsent: true }, { ...command, message: " " }, { ...command, message: "x".repeat(2001) }, { ...command, surface: "ADMIN" }])("rejects closed body violations", async (body) => { expect((await feedbackHttp(request(body), "submit")).status).toBe(400); expect(h.db.productFeedback.create).not.toHaveBeenCalled(); });
    it("stores deliberate applicant text only; no consent or org required, no submit request ID stored", async () => { const result = await feedbackHttp(request(command), "submit"); expect(result.status).toBe(201); expect(h.db.productFeedback.create).toHaveBeenCalledWith(expect.objectContaining({ data: { ...command, profileId: actor, surface: "MERCHANT" } })); expect(h.events).toEqual([]); expect(result.headers.get("cache-control")).toBe("private, no-store"); });
    it("requires current same-profile organization membership, never consent authority", async () => { h.consent = true; expect((await feedbackHttp(request({ ...command, organizationId: org }), "submit")).status).toBe(404); expect(h.db.productFeedback.create).not.toHaveBeenCalled(); expect(h.db.organizationMembership.findFirst).toHaveBeenCalledWith({ where: { profileId: actor, organizationId: org, isActive: true }, select: { id: true } }); h.db.stallMembership.findFirst.mockResolvedValue({ id: "membership" }); expect((await feedbackHttp(request({ ...command, organizationId: org }), "submit")).status).toBe(201); });
    it("applies the real per-principal five/hour and IP/global limiter", async () => { h.rate.mockImplementation(async (input) => ({ allowed: input.scope !== "feedback-submit", retryAfterSeconds: 3600 })); const result = await feedbackHttp(request(command), "submit"); expect(result.status).toBe(429); expect(result.headers.get("retry-after")).toBe("3600"); expect(h.rate).toHaveBeenCalledWith({ scope: "feedback-submit", identifier: actor, limit: 5, windowMs: 3600000 }); expect(h.db.productFeedback.create).not.toHaveBeenCalled(); });
    it("links only a current actor/scope FAILURE audit; unknown/foreign get identical denial and no insert", async () => { for (const found of [null, null]) {
        h.db.auditLog.findFirst.mockResolvedValue(found);
        expect((await feedbackHttp(request({ ...command, requestId: reference }), "submit")).status).toBe(400);
    } expect(h.db.productFeedback.create).not.toHaveBeenCalled(); expect(h.db.auditLog.findFirst).toHaveBeenCalledWith({ where: { requestId: reference, actorProfileId: actor, organizationId: null, outcome: "FAILURE", createdAt: { gte: expect.any(Date) } }, select: { id: true } }); h.db.auditLog.findFirst.mockResolvedValue({ id: "audit" }); h.consent = true; expect((await feedbackHttp(request({ ...command, requestId: reference }), "submit")).status).toBe(201); expect(h.events).toEqual([{ event: "feedback_submitted", surface: 1, kind: 1, outcome: 1 }]); });
    it.each(["throw", "reject", "hang"])("durably succeeds under %s analytics failure", async (mode) => { vi.useFakeTimers(); h.mode = mode; h.consent = true; const pending = feedbackHttp(request(command), "submit"); await vi.advanceTimersByTimeAsync(51); const response = await pending; expect(response.status).toBe(201); expect(h.db.productFeedback.create).toHaveBeenCalledTimes(1); expect(h.events).toEqual([]); });
    it("does not capture a failed durable create", async () => { h.consent = true; h.db.productFeedback.create.mockRejectedValue(Error("database")); expect((await feedbackHttp(request(command), "submit")).status).toBe(503); expect(h.events).toEqual([]); });
    it("denies nonadmin list/detail/update before reading a feedback row", async () => { for (const operation of ["list", "detail", "update"] as const)
        expect((await feedbackHttp(new Request(`http://localhost/api/admin/feedback?${query}`), operation, id)).status).toBe(404); expect(h.db.productFeedback.findFirst).not.toHaveBeenCalled(); expect(h.db.productFeedback.findMany).not.toHaveBeenCalled(); });
    it("bounds admin scope and keyset anchor using exact DB precision, audits safe DTO", async () => { h.admin = true; h.principal = { ...principal, user: { ...principal.user, platformRole: "PLATFORM_ADMIN" } }; const response = await feedbackHttp(new Request(`http://localhost/api/admin/feedback?${query}&status=NEW&organizationId=${org}&cursor=${id}`), "list"); expect(response.status).toBe(200); expect(h.db.productFeedback.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ organizationId: org, status: "NEW", id, expiresAt: { gt: expect.any(Date) } }) })); expect(h.db.productFeedback.findMany).toHaveBeenCalledWith(expect.objectContaining({ cursor: { id }, skip: 1, take: 26, orderBy: [{ createdAt: "desc" }, { id: "desc" }] })); expect(h.audit).toHaveBeenCalledWith(expect.objectContaining({ action: "PRODUCT_FEEDBACK_READ", actorProfileId: actor })); expect(JSON.stringify(await response.json())).not.toContain("profileId"); });
    it("CAS conflict cannot overwrite the current version", async () => { h.admin = true; h.principal = { ...principal, user: { ...principal.user, platformRole: "PLATFORM_ADMIN" } }; h.db.productFeedback.updateMany.mockResolvedValue({ count: 0 }); const response = await feedbackHttp(new Request(`http://localhost/api/admin/feedback/${id}?${query}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: 1, status: "CLOSED" }) }), "update", id); expect(response.status).toBe(409); expect(h.db.productFeedback.findUniqueOrThrow).not.toHaveBeenCalled(); });
    it("cleanup uses only bounded expiry SQL and isolated timeout transaction", async () => { await cleanupExpiredFeedback(); expect(h.db.$transaction).toHaveBeenCalledWith(expect.any(Function), { timeout: 1500, maxWait: 500 }); const sql = h.db.$executeRaw.mock.calls.map(call => String.raw({ raw: call[0] })).join(" "); expect(sql).toContain("expires_at <= now()"); expect(sql).toContain("limit 500 for update skip locked"); expect(sql).toContain("statement_timeout"); h.db.$transaction.mockRejectedValue(Error("timeout")); expect(await cleanupExpiredFeedback()).toBeNull(); });
});
