import Link from "next/link";
import { getAdminSubscriptions } from "@/lib/admin-billing-data";
import { subscriptionStatusLabels } from "@/lib/billing-labels";

export default async function AdminSubscriptionsPage() {
  const subscriptions = await getAdminSubscriptions();
  return <main className="mx-auto min-h-[calc(100vh-76px)] max-w-7xl px-4 py-7 md:px-8"><header><h1 className="text-3xl font-semibold">訂閱管理</h1><p className="mt-2 text-sm text-stone-600">查看方案版本、狀態、期間與近期對帳用量。</p></header><div className="mt-6 overflow-x-auto border-y border-stone-200"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-stone-50 text-stone-600"><tr><th className="px-3 py-3">商家</th><th className="px-3 py-3">方案版本</th><th className="px-3 py-3">狀態</th><th className="px-3 py-3">計費期間</th><th className="px-3 py-3 text-right">對帳訂單</th><th className="px-3 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-stone-200">{subscriptions.map((subscription) => <tr key={subscription.id}><td className="px-3 py-4 font-semibold">{subscription.organization.businessName}</td><td className="px-3 py-4">{subscription.planVersion.displayName} v{subscription.planVersion.version}</td><td className="px-3 py-4">{subscriptionStatusLabels[subscription.status] ?? subscription.status}</td><td className="px-3 py-4">{dateOnly(subscription.billingPeriodStart)} 至 {dateOnly(subscription.billingPeriodEnd)}</td><td className="px-3 py-4 text-right">{subscription.organization.billingUsageSummaries[0]?.billableOrderCount ?? 0}</td><td className="px-3 py-4 text-right"><Link href={`/admin/subscriptions/${subscription.id}`} className="font-semibold text-teal-800">管理</Link></td></tr>)}</tbody></table>{subscriptions.length === 0 ? <p className="px-3 py-8 text-sm text-stone-500">目前沒有訂閱。</p> : null}</div></main>;
}
function dateOnly(value: Date) { return value.toISOString().slice(0, 10); }
