import {readFileSync,writeFileSync} from 'node:fs';
import {loadEnvFile} from 'node:process';
import {registerHooks} from './node-hooks';
import assert from 'node:assert/strict';
import {captureFrozenResponsiveSource} from '../../responsive-build-provenance.mjs';
import {openGuardedDatabase,verifyLiveFixture} from '../../../docs/awesome-optimization/qa/live-fixture-guard.mjs';
const d='.superpowers/sdd/2026-10-01-awesome-optimization/batch-4b',[label,id,mode="retry"]=process.argv.slice(2);
assert.match(label,/^[a-z0-9-]+$/);assert.match(id,/^[a-f0-9-]{36}$/);assert.equal(captureFrozenResponsiveSource().sourceIdentity.sourceSha256,process.env.AWESOME_QA_EXPECTED_SOURCE_SHA256);
loadEnvFile('.env.local');process.env.REPORT_DELIVERY_MODE='simulate';process.env.REPORT_FROM_EMAIL='qa-report@example.test';process.env.RESEND_API_KEY='';
const db=await openGuardedDatabase();await verifyLiveFixture(db);
const extraFile=process.env.B4B_UI_EXTRA_RECEIPT!;assert.match(extraFile,/^authority-[0-9]+-ui-extra-fixtures\.json$/);const extra=JSON.parse(readFileSync(`${d}/${extraFile}`,'utf8')),base=JSON.parse(readFileSync(`${d}/operations-3-ui-fixtures.json`,'utf8'));assert.equal(extra.base,'operations-3-ui-fixtures.json');assert.ok(mode==="retry"||mode==="stall-denied");assert.equal(id,mode==="retry"?extra.extraIds.permitted:extra.stallDeactivation.deliveryId);
registerHooks({resolve(specifier,context,next){if(specifier==='server-only')return{url:new URL('../../../src/test/server-only.ts',import.meta.url).href,shortCircuit:true};return next(specifier,context);}});
globalThis.fetch=async()=>{throw Error('UI_RETRY_ALL_EXTERNAL_NETWORK_DENIED');};
try{const before=await db.reportDelivery.findUniqueOrThrow({where:{id}});assert.equal(before.organizationId,mode==="retry"?base.organizationId:extra.stallDeactivation.organizationId);assert.equal(before.attemptCount,mode==="retry"?1:0);assert.equal(before.status,'PROCESSING');assert.equal(before.effectState,mode==='retry'?'REJECTED':'NOT_STARTED');assert.equal(before.leaseToken,null);if(mode==='retry')assert.ok(before.snapshotHash);const provider=await import('../../../src/server/reports/report-email');assert.equal(provider.reportProviderBinding().binding,base.binding);assert.equal(provider.reportProviderBinding().mode,'SIMULATED');await(await import('../../../src/lib/report-delivery')).processReportDelivery(id);const after=await db.reportDelivery.findUniqueOrThrow({where:{id}});assert.equal(after.status,mode==='retry'?'SIMULATED':'FAILURE');assert.equal(after.attemptCount,mode==='retry'?2:1);if(mode==='stall-denied'){assert.equal(after.effectState,'SUPPRESSED');assert.equal(after.firstRequestAt,null);}assert.equal(after.snapshotHash,before.snapshotHash);assert.deepEqual(after.intentJson,before.intentJson);const corpus=(await verifyLiveFixture(db)).receipt;writeFileSync(`${d}/browser-${label}-${mode}-worker-result.json`,JSON.stringify({classification:'ORIGINAL_WORKER_ORIGINAL_ADAPTER_EXPLICIT_SIMULATE_NO_NETWORK',before,after,corpus},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:'PASS',id,simulated:true}));}finally{await db.$disconnect();await(await import('../../../src/lib/prisma')).prisma.$disconnect();}
