import {readFileSync,writeFileSync} from 'node:fs';
import {loadEnvFile} from 'node:process';
import {createRequire} from 'node:module';
import {registerHooks} from './node-hooks';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {captureFrozenResponsiveSource} from '../../responsive-build-provenance.mjs';
import {openGuardedDatabase,verifyLiveFixture} from '../../../docs/awesome-optimization/qa/live-fixture-guard.mjs';
const d='.superpowers/sdd/2026-10-01-awesome-optimization/batch-4b',label=process.argv[2];assert.match(label??'',/^[a-z0-9-]+$/);
assert.equal(captureFrozenResponsiveSource().sourceIdentity.sourceSha256,process.env.B4B_ROOT_RUNTIME_SOURCE);loadEnvFile('.env.local');
process.env.REPORT_DELIVERY_MODE='simulate';process.env.REPORT_FROM_EMAIL='qa-report@example.test';process.env.RESEND_API_KEY='';process.env.B4B_TEST_REPORT_BINDING='APP_SIMULATED';
const db=await openGuardedDatabase();await verifyLiveFixture(db);
const mockUrl=new URL('./mock-report-email.mts',import.meta.url).href,effectUrl=new URL('./report-effect-facade.cts',import.meta.url).href;let effectBindings=0;
registerHooks({resolve(specifier,context,next){if(specifier==='server-only')return{url:new URL('../../../src/test/server-only.ts',import.meta.url).href,shortCircuit:true};const result=next(specifier,context),path=result.url.replaceAll('\\','/'),parent=context.parentURL?.replaceAll('\\','/');if(path.endsWith('/src/server/reports/report-email.ts'))return{url:mockUrl,shortCircuit:true};if(path.endsWith('/src/server/reports/report-execution.ts')&&parent?.endsWith('/src/lib/report-delivery.ts')){effectBindings++;return{url:effectUrl,shortCircuit:true};}return result;}});
const require=createRequire(import.meta.url),mock=require('./mock-report-email.mts') as typeof import('./mock-report-email.mts'),effect=require('./report-effect-facade.cts') as typeof import('./report-effect-facade.cts');
const organizations=new Set<string>(),server=await mock.startReportMock(db,organizations),fetchBefore=globalThis.fetch;
globalThis.fetch=async(input,init)=>{const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);assert.equal(url.origin,server.origin);return fetchBefore(input,init);};
const results:unknown[]=[],fixtures:unknown[]=[],pending:Promise<unknown>[]=[];
try{
 const worker=await import('../../../src/lib/report-delivery'),execution=await import('../../../src/server/reports/report-execution'),operations=await import('../../../src/server/reports/report-operations'),http=await import('../../../src/server/reports/report-http'),auth=await import('../../../src/lib/auth');assert.ok(effectBindings>0);
 async function actor(role:'PLATFORM_ADMIN'|null=null){const id=randomUUID(),email=`awesome-b4b-ops-${id}@example.test`;await db.profile.create({data:{id,email,displayName:'SIMULATED report actor',platformRole:role,authIdentities:{create:{provider:'GOOGLE',providerSubject:`awesome-b4b-ops/${id}`,providerEmail:email,providerEmailVerified:true}}}});const deviceId=randomUUID(),session=await auth.createSession(id,{deviceId});writeFileSync(`${d}/${label}-actor-${id}.json`,JSON.stringify({id,email,role,deviceId,sessionId:session.id,preimage:'ABSENT'})+'\n',{flag:'wx'});return{id,deviceId,session};}
 const owner=await actor(),admin=await actor('PLATFORM_ADMIN'),finance=await actor(),outsider=await actor();
 const access=(who:typeof owner,org:string,manage=true)=>({organizationId:org,actorId:who.id,sessionId:who.session.id,deviceId:who.deviceId,requestId:randomUUID(),isPlatformAdmin:who.id===admin.id,canManage:manage,canUseAllStalls:true,authorizedStallIds:[]});
 function request(who:typeof owner,path:string,method='GET',body?:unknown,csrf=true){return new Request('http://127.0.0.1:3026'+path,{method,headers:{origin:'http://127.0.0.1:3026',cookie:`stallorder_session=${who.session.token}; stallorder_auth_device=${who.deviceId}; stallorder_csrf=${who.session.csrfToken}`,'content-type':'application/json',...(csrf?{'x-csrf-token':who.session.csrfToken}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}
 async function scope(){const id=randomUUID(),name='awesome-b4b-ops-'+id;writeFileSync(`${d}/${label}-reserved-${id}.json`,JSON.stringify({id,name})+'\n',{flag:'wx'});const organization=await db.organization.create({data:{id,slug:name,name:'合成報表 '+id.slice(0,6),businessName:'SIMULATED report',email:name+'@example.test',phone:'0000000000'}});organizations.add(id);const plan=await db.planVersion.findFirstOrThrow({where:{plan:{code:'TRIAL'}},orderBy:{version:'desc'}});const subscription=await db.subscription.create({data:{organizationId:id,planId:plan.planId,planVersionId:plan.id,status:'TRIALING',billingPeriodStart:new Date(),billingPeriodEnd:new Date(Date.now()+30*86400000),trialStartedAt:new Date(),trialEndsAt:new Date(Date.now()+30*86400000)}});const stall=await db.stall.create({data:{organizationId:id,name:'合成攤位',slug:name,code:'O'+id.slice(0,7),address:'SIMULATED',location:'SIMULATED',businessStatus:'CLOSED',orderingEnabled:false}});const membership=await db.organizationMembership.create({data:{organizationId:id,profileId:owner.id,role:'ORGANIZATION_OWNER',allStalls:true}});const schedule=await db.reportSchedule.create({data:{organizationId:id,name:'合成報表排程',reportType:'DAILY_SALES',recipients:['synthetic@example.test'],stallIds:[stall.id],nextRunAt:new Date(Date.now()+86400000),createdById:owner.id,updatedById:owner.id}});const f={organization,subscription,stall,membership,schedule};fixtures.push(f);writeFileSync(`${d}/${label}-scope-${id}.json`,JSON.stringify(f,null,2)+'\n',{flag:'wx'});return f;}
 async function delivery(f:Awaited<ReturnType<typeof scope>>,mode:Parameters<typeof mock.configureReport>[1]='ACCEPT'){const id=randomUUID();const row=await db.reportDelivery.create({data:{id,organizationId:f.organization.id,reportScheduleId:f.schedule.id,reportType:'DAILY_SALES',scheduledFor:new Date(),periodStart:new Date(),periodEnd:new Date(),recipients:['synthetic@example.test'],subject:'SIMULATED ops',attemptCount:0,effectState:'NOT_STARTED',nextAttemptAt:new Date(),intentJson:execution.createReportIntent(f.schedule,id),originRequestId:randomUUID()}});mock.configureReport(id,mode);writeFileSync(`${d}/${label}-delivery-${id}.json`,JSON.stringify(row,null,2)+'\n',{flag:'wx'});return row;}
 async function bounded<T>(promise:Promise<T>){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('OPERATIONS_CHECKPOINT_TIMEOUT')),10000);})]);}finally{if(timer)clearTimeout(timer);}}
 // Real lock proof on additive rows; neither the shared flag nor existing plan metadata is changed.
 const lockScope=await scope(),lockRow=await delivery(lockScope),addOn=await db.addOnCatalog.create({data:{code:'B4B_'+randomUUID().replaceAll('-','').toUpperCase(),displayName:'SIMULATED lock',billingType:'ONE_TIME',unitPrice:0,isPublic:false,featureCode:'SCHEDULED_REPORTS',availabilityStatus:'ENABLED'}}),item=await db.subscriptionItem.create({data:{organizationId:lockScope.organization.id,subscriptionId:lockScope.subscription.id,itemType:'ADD_ON',code:addOn.code,description:'SIMULATED lock',quantity:1,unitPrice:0}});
 writeFileSync(`${d}/${label}-lock-fixture.json`,JSON.stringify({addOn,item},null,2)+'\n',{flag:'wx'});
 await db.$transaction(async tx=>{await execution.assertCurrentReportEligibility(tx,lockRow);const checks=[];for(const [table,id]of[['subscription_items',item.id],['add_on_catalog',addOn.id]]){let blocked=false,errorCode:string|undefined;try{await db.$transaction(async other=>{await other.$queryRawUnsafe(`select id from public.${table} where id=$1::uuid for update nowait`,id);});}catch(error){assert.ok(error&&typeof error==='object'&&'meta'in error&&error.meta&&typeof error.meta==='object'&&'code'in error.meta);errorCode=String(error.meta.code);blocked=errorCode==='55P03';}checks.push({table,id,blocked,errorCode});}writeFileSync(`${d}/${label}-entitlement-lock-proof.json`,JSON.stringify({classification:'ACTUAL_TWO_CONNECTION_OWNED_ROWS_NO_DATA_MUTATION',checks},null,2)+'\n',{flag:'wx'});assert.ok(checks.every(check=>check.blocked),'CURRENT_ENTITLEMENT_ROWS_NOT_FENCED');},{timeout:20000});results.push({name:'owned-add-on-item-and-catalog-current-eligibility-locks',status:'PASS'});
 // Declared absence seam only; the shared flag is never inserted, deleted, or updated.
 await db.$transaction(async tx=>{let flagReads=0,tableLocks=0;const facade=new Proxy(tx,{get(target,key){if(key==='$queryRaw')return async(strings:TemplateStringsArray,...values:unknown[])=>{if(strings.join('?')==="select code from public.billing_feature_flags where code='OPEN_BETA_FREE_ACCESS_ENABLED' for share"){flagReads++;if(flagReads===1)return[];}return target.$queryRaw(strings,...values);};if(key==='$executeRaw')return async(strings:TemplateStringsArray,...values:unknown[])=>{if(strings.join('?')==='lock table public.billing_feature_flags in share mode')tableLocks++;return target.$executeRaw(strings,...values);};const value=Reflect.get(target,key);return typeof value==='function'?value.bind(target):value;}});await execution.assertCurrentReportEligibility(facade,lockRow);let code:string|undefined;try{await db.$transaction(async other=>{await other.$executeRaw`lock table public.billing_feature_flags in row exclusive mode nowait`;});}catch(error){assert.ok(error&&typeof error==='object'&&'meta'in error&&error.meta&&typeof error.meta==='object'&&'code'in error.meta);code=String(error.meta.code);}assert.equal(flagReads,2);assert.equal(tableLocks,1);assert.equal(code,'55P03');writeFileSync(`${d}/${label}-absent-flag-lock-proof.json`,JSON.stringify({classification:'DECLARED_FIRST_READ_ABSENCE_SEAM_WITH_ACTUAL_TABLE_LOCK_NO_SHARED_DATA_MUTATION',flagReads,tableLocks,competingWriteLockSqlstate:code,isolation:'ReadCommitted'},null,2)+'\n',{flag:'wx'});},{isolationLevel:'ReadCommitted',timeout:20000});results.push({name:'declared-absent-flag-reread-and-actual-table-lock',status:'PASS'});
 for(const mutation of ['schedule','subscription']){const f=await scope(),row=await delivery(f);effect.holdEffect(row.id);const running=worker.processReportDelivery(row.id);pending.push(running);await bounded(effect.heldEffect(row.id));const before=await db.reportDelivery.findUniqueOrThrow({where:{id:row.id}});assert.ok(before.snapshotHash);assert.equal(before.firstRequestAt,null);let response:Response;
  if(mutation==='schedule'){const route=await import('../../../src/app/api/merchant/organizations/[organizationId]/report-schedules/[scheduleId]/route');response=await route.DELETE(request(owner,`/api/merchant/organizations/${f.organization.id}/report-schedules/${f.schedule.id}`,'DELETE'),{params:Promise.resolve({organizationId:f.organization.id,scheduleId:f.schedule.id})});}
  else{const route=await import('../../../src/app/api/admin/billing/subscriptions/[subscriptionId]/route');response=await route.PATCH(request(admin,`/api/admin/billing/subscriptions/${f.subscription.id}`,'PATCH',{operation:'SUSPEND',reason:'SIMULATED report pre-effect revocation'}),{params:Promise.resolve({subscriptionId:f.subscription.id})});}
  const body=await response.json();assert.equal(response.status,200,JSON.stringify(body));effect.releaseEffect(row.id);await running;const after=await db.reportDelivery.findUniqueOrThrow({where:{id:row.id}});assert.equal(after.effectState,'SUPPRESSED');assert.equal(after.firstRequestAt,null);assert.equal(after.snapshotHash,before.snapshotHash);assert.equal(mock.events.filter(event=>event.key.endsWith(row.id)).length,0);results.push({name:`actual-${mutation}-revocation-after-snapshot-before-effect`,status:'PASS',id:row.id,before,after});
 }
 const f=await scope(),empty=await scope();await db.organizationMembership.create({data:{organizationId:f.organization.id,profileId:finance.id,role:'FINANCE_VIEWER',allStalls:true}});
 const accepted=await delivery(f),rejected=await delivery(f,'REJECT'),unknown=await delivery(f,'LOSS');for(const row of[accepted,rejected,unknown])await worker.processReportDelivery(row.id);
 const states=await db.reportDelivery.findMany({where:{id:{in:[accepted.id,rejected.id,unknown.id]}}});assert.equal(states.find(r=>r.id===accepted.id)!.status,'SIMULATED');assert.equal(states.find(r=>r.id===rejected.id)!.effectState,'REJECTED');assert.equal(states.find(r=>r.id===unknown.id)!.effectState,'UNKNOWN');
 async function api(who:typeof owner,operation:'list'|'detail'|'retry'|'reconcile',org:string,id?:string,body?:unknown,query='',csrf=true){const path=`/api/merchant/organizations/${org}/report-deliveries${id?'/'+id:''}${operation==='retry'||operation==='reconcile'?'/'+operation:''}${query?'?'+query:''}`;const response=await http.reportHttp(request(who,path,body===undefined?'GET':'POST',body,csrf),operation,org,id);const result={status:response.status,cache:response.headers.get('cache-control'),body:await response.json()};assert.equal(result.cache,'private, no-store');return result;}
 const list=await api(owner,'list',f.organization.id);assert.equal(list.status,200);assert.equal(list.body.items.length,3);assert.doesNotMatch(JSON.stringify(list.body),/recipients|snapshotJson|snapshotHash|providerMessageId|leaseToken|reconciliationEvidence/);
 const readOnly=await api(finance,'list',f.organization.id);assert.equal(readOnly.status,200);assert.ok(readOnly.body.items.every((r:{canRetry:boolean;canReconcile:boolean})=>!r.canRetry&&!r.canReconcile));assert.equal((await api(outsider,'list',f.organization.id)).status,404);assert.equal((await api(owner,'detail',empty.organization.id,accepted.id)).status,404);
 const rejectedState=states.find(r=>r.id===rejected.id)!,command={expectedVersion:rejectedState.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'};
 assert.equal((await api(finance,'retry',f.organization.id,rejected.id,command)).status,403);assert.equal((await api(owner,'retry',f.organization.id,rejected.id,command,'',false)).status,403);assert.equal((await api(owner,'retry',f.organization.id,rejected.id,{...command,expectedVersion:command.expectedVersion-1})).status,409);
 for(const query of ['limit=51','limit=1&limit=2','from=2020-01-01T00:00:00Z&to=2026-10-01T00:00:00Z','endpoint=https://example.test','profileId='+owner.id])assert.equal((await api(owner,'list',f.organization.id,undefined,undefined,query)).status,400);
 for(const row of [accepted,unknown])assert.equal((await api(owner,'retry',f.organization.id,row.id,{expectedVersion:states.find(r=>r.id===row.id)!.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'})).status,409);
 assert.equal((await api(owner,'retry',f.organization.id,rejected.id,{...command,confirmed:true})).status,400);
 results.push({name:'actual-cookie-route-view-manage-csrf-version-foreign-strict-dto',status:'PASS',organizationId:f.organization.id,ids:{accepted:accepted.id,rejected:rejected.id,unknown:unknown.id}});
 // Fresh INSERT timestamps exercise native microseconds; no existing timestamp is modified.
 const pageScope=await scope(),ids=[];for(let i=1;i<=25;i++){const id=randomUUID();ids.push(id);const intent=execution.createReportIntent(pageScope.schedule,id);await db.$executeRaw`insert into public.report_deliveries(id,organization_id,report_schedule_id,report_type,scheduled_for,period_start,period_end,recipients,subject,attempt_count,effect_state,next_attempt_at,intent_json,origin_request_id,created_at) values(${id}::uuid,${pageScope.organization.id}::uuid,${pageScope.schedule.id}::uuid,'DAILY_SALES',clock_timestamp(),clock_timestamp(),clock_timestamp(),array['synthetic@example.test'],'SIMULATED cursor',0,'NOT_STARTED',clock_timestamp()+interval '1 day',${JSON.stringify(intent)}::jsonb,${randomUUID()}::uuid,date_trunc('second',clock_timestamp())-interval '1 second'+${i}::integer*interval '1 microsecond')`;}
 const sqlOrder=await db.$queryRaw<Array<{id:string;created_text:string}>>`select id,created_at::text as created_text from public.report_deliveries where organization_id=${pageScope.organization.id}::uuid order by created_at desc,id desc`;
 const pages=[],seen=[];let cursor:string|undefined;do{const page=await api(owner,'list',pageScope.organization.id,undefined,undefined,'limit=10'+(cursor?'&cursor='+cursor:''));assert.equal(page.status,200);pages.push(page.body);seen.push(...page.body.items.map((r:{id:string})=>r.id));cursor=page.body.nextCursor;}while(cursor);
 assert.deepEqual(pages.map(page=>page.items.length),[10,10,5]);assert.deepEqual(seen,sqlOrder.map(row=>row.id));assert.equal(new Set(seen).size,25);assert.equal((await api(owner,'list',pageScope.organization.id,undefined,undefined,'cursor='+accepted.id)).status,404);assert.equal((await api(owner,'list',pageScope.organization.id,undefined,undefined,'outcome=FAILED&cursor='+seen[9])).status,400);
 results.push({name:'actual-database-microsecond-cursor-25-once-and-denials',status:'PASS',sqlOrder,pages});
 const fixtureReceipt={at:new Date().toISOString(),source:process.env.B4B_ROOT_RUNTIME_SOURCE,classification:'SIMULATED_FIXED_LOOPBACK_APP_COMPATIBLE_BINDING',binding:mock.reportProviderBinding().binding,mode:'simulate',from:'qa-report@example.test',resendKey:'EMPTY_OVERRIDE',ownerId:owner.id,adminId:admin.id,financeId:finance.id,outsiderId:outsider.id,organizationId:f.organization.id,organizationName:f.organization.name,emptyOrganizationId:empty.organization.id,emptyOrganizationName:empty.organization.name,ids:{accepted:accepted.id,rejected:rejected.id,unknown:unknown.id},states};writeFileSync(`${d}/${label}-ui-fixtures.json`,JSON.stringify(fixtureReceipt,null,2)+'\n',{flag:'wx'});
 console.log(JSON.stringify({status:'PASS',checks:results.length,simulated:true}));
}finally{effect.releaseAllEffects();globalThis.fetch=fetchBefore;await server.close();await Promise.allSettled(pending);writeFileSync(`${d}/${label}-operations-result.json`,JSON.stringify({at:new Date().toISOString(),results,fixtures,events:mock.events,effectBindings,simulated:true},null,2)+'\n',{flag:'wx'});writeFileSync(`${d}/${label}-mock-closed.json`,JSON.stringify({closed:true,origin:server.origin,at:new Date().toISOString()})+'\n',{flag:'wx'});await db.$disconnect();await(await import('../../../src/lib/prisma')).prisma.$disconnect();}
