import {fork,type ChildProcess} from 'node:child_process';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {loadEnvFile} from 'node:process';
import {createRequire} from 'node:module';
import {registerHooks} from './node-hooks';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {captureFrozenResponsiveSource} from '../../responsive-build-provenance.mjs';
import {openGuardedDatabase,verifyLiveFixture} from '../../../docs/awesome-optimization/qa/live-fixture-guard.mjs';
const d='.superpowers/sdd/2026-10-01-awesome-optimization/batch-4b',label=process.argv[2];assert.match(label??'',/^[a-z0-9-]+$/);
assert.equal(captureFrozenResponsiveSource().sourceIdentity.sourceSha256,process.env.B4B_ROOT_RUNTIME_SOURCE);loadEnvFile('.env.local');
process.env.REPORT_DELIVERY_MODE='simulate';process.env.REPORT_FROM_EMAIL='qa-report@example.test';process.env.RESEND_API_KEY='';process.env.B4B_TEST_REPORT_BINDING='APP_SIMULATED';
const db=await openGuardedDatabase();await verifyLiveFixture(db);
const mockUrl=new URL('./mock-report-email.mts',import.meta.url).href,effectUrl=new URL('./report-effect-facade.cts',import.meta.url).href;let effectBindings=0;
registerHooks({resolve(specifier,context,next){if(specifier==='server-only')return{url:new URL('../../../src/test/server-only.ts',import.meta.url).href,shortCircuit:true};const result=next(specifier,context),path=result.url.replaceAll('\\','/'),parent=context.parentURL?.replaceAll('\\','/');if(path.endsWith('/src/server/reports/report-email.ts'))return{url:mockUrl,shortCircuit:true};if(path.endsWith('/src/server/reports/report-execution.ts')&&parent?.endsWith('/src/lib/report-delivery.ts')){effectBindings++;return{url:effectUrl,shortCircuit:true};}return result;}});
const require=createRequire(import.meta.url),mock=require('./mock-report-email.mts') as typeof import('./mock-report-email.mts'),effect=require('./report-effect-facade.cts') as typeof import('./report-effect-facade.cts');
const organizations=new Set<string>(),server=await mock.startReportMock(db,organizations),fetchBefore=globalThis.fetch;
globalThis.fetch=async(input,init)=>{const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);assert.equal(url.origin,server.origin);return fetchBefore(input,init);};
const results:unknown[]=[],fixtures:unknown[]=[],pending:Promise<unknown>[]=[],children:ChildProcess[]=[];
try{
 const worker=await import('../../../src/lib/report-delivery'),execution=await import('../../../src/server/reports/report-execution'),operations=await import('../../../src/server/reports/report-operations'),http=await import('../../../src/server/reports/report-http'),auth=await import('../../../src/lib/auth');assert.ok(effectBindings>0);
 async function actor(role:'PLATFORM_ADMIN'|null=null){const id=randomUUID(),email=`awesome-b4b-ops-${id}@example.test`;await db.profile.create({data:{id,email,displayName:'SIMULATED report actor',platformRole:role,authIdentities:{create:{provider:'GOOGLE',providerSubject:`awesome-b4b-ops/${id}`,providerEmail:email,providerEmailVerified:true}}}});const deviceId=randomUUID(),session=await auth.createSession(id,{deviceId});writeFileSync(`${d}/${label}-actor-${id}.json`,JSON.stringify({id,email,role,deviceId,sessionId:session.id,preimage:'ABSENT'})+'\n',{flag:'wx'});return{id,deviceId,session};}
 const owner=await actor(),admin=await actor('PLATFORM_ADMIN'),finance=await actor(),outsider=await actor();
 const access=(who:typeof owner,org:string,manage=true)=>({organizationId:org,actorId:who.id,sessionId:who.session.id,deviceId:who.deviceId,requestId:randomUUID(),isPlatformAdmin:who.id===admin.id,canManage:manage,canUseAllStalls:true,authorizedStallIds:[]});
 function request(who:typeof owner,path:string,method='GET',body?:unknown,csrf=true){return new Request('http://127.0.0.1:3026'+path,{method,headers:{origin:'http://127.0.0.1:3026',cookie:`stallorder_session=${who.session.token}; stallorder_auth_device=${who.deviceId}; stallorder_csrf=${who.session.csrfToken}`,'content-type':'application/json',...(csrf?{'x-csrf-token':who.session.csrfToken}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}
 async function scope(){const id=randomUUID(),name='awesome-b4b-ops-'+id;writeFileSync(`${d}/${label}-reserved-${id}.json`,JSON.stringify({id,name})+'\n',{flag:'wx'});const organization=await db.organization.create({data:{id,slug:name,name:'合成報表 '+id.slice(0,6),businessName:'SIMULATED report',email:name+'@example.test',phone:'0000000000'}});organizations.add(id);const plan=await db.planVersion.findFirstOrThrow({where:{plan:{code:'TRIAL'}},orderBy:{version:'desc'}});const subscription=await db.subscription.create({data:{organizationId:id,planId:plan.planId,planVersionId:plan.id,status:'TRIALING',billingPeriodStart:new Date(),billingPeriodEnd:new Date(Date.now()+30*86400000),trialStartedAt:new Date(),trialEndsAt:new Date(Date.now()+30*86400000)}});const stall=await db.stall.create({data:{organizationId:id,name:'合成攤位',slug:name,code:'O'+id.slice(0,7),address:'SIMULATED',location:'SIMULATED',businessStatus:'CLOSED',orderingEnabled:false}});const membership=await db.organizationMembership.create({data:{organizationId:id,profileId:owner.id,role:'ORGANIZATION_OWNER',allStalls:true}});const schedule=await db.reportSchedule.create({data:{organizationId:id,name:'合成報表排程',reportType:'DAILY_SALES',recipients:['synthetic@example.test'],stallIds:[stall.id],nextRunAt:new Date(Date.now()+86400000),createdById:owner.id,updatedById:owner.id}});const f={organization,subscription,stall,membership,schedule};fixtures.push(f);writeFileSync(`${d}/${label}-scope-${id}.json`,JSON.stringify(f,null,2)+'\n',{flag:'wx'});return f;}
 async function delivery(f:Awaited<ReturnType<typeof scope>>,mode:Parameters<typeof mock.configureReport>[1]='ACCEPT'){const id=randomUUID();const row=await db.reportDelivery.create({data:{id,organizationId:f.organization.id,reportScheduleId:f.schedule.id,reportType:'DAILY_SALES',scheduledFor:new Date(),periodStart:new Date(),periodEnd:new Date(),recipients:['synthetic@example.test'],subject:'SIMULATED ops',attemptCount:0,effectState:'NOT_STARTED',nextAttemptAt:new Date(),intentJson:execution.createReportIntent(f.schedule,id),originRequestId:randomUUID()}});mock.configureReport(id,mode);writeFileSync(`${d}/${label}-delivery-${id}.json`,JSON.stringify(row,null,2)+'\n',{flag:'wx'});return row;}
 async function bounded<T>(promise:Promise<T>){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('OPERATIONS_CHECKPOINT_TIMEOUT')),10000);})]);}finally{if(timer)clearTimeout(timer);}}
 async function until(check:()=>Promise<boolean>,timeout=10000){const end=Date.now()+timeout;while(!await check()){assert.ok(Date.now()<end,'AUTHORITY_WAIT_EXPIRED');await new Promise(r=>setTimeout(r,25));}}
 const bundle=process.argv[3]??'full';assert.ok(['full','diagnostic-stall'].includes(bundle));
 for(const kind of bundle==='diagnostic-stall'?[]:['role','stall','session']){
  const f=await scope(),manager=await actor(),row=await delivery(f,'REJECT');
  const membership=await db.organizationMembership.create({data:{organizationId:f.organization.id,profileId:manager.id,role:'ORGANIZATION_ADMIN',allStalls:kind!=='stall'}});
  const assignment=kind==='stall'?await db.stallMembership.create({data:{organizationId:f.organization.id,stallId:f.stall.id,profileId:manager.id,role:'STALL_MANAGER'}}):null;
  await worker.processReportDelivery(row.id);const before=await db.reportDelivery.findUniqueOrThrow({where:{id:row.id}}),staleAccess={...access(manager,f.organization.id),canUseAllStalls:kind!=='stall',authorizedStallIds:kind==='stall'?[f.stall.id]:[]};
  let release!:()=>void,reached!:()=>void;const ready=new Promise<void>(r=>{reached=r;}),hold=new Promise<void>(r=>{release=r;});
  const locker=db.$transaction(async tx=>{await tx.$queryRaw`select id from public.report_deliveries where id=${row.id}::uuid for update`;reached();await hold;},{timeout:20000});pending.push(locker);await ready;
  const retry=operations.retryReportDelivery(staleAccess,row.id,{expectedVersion:before.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'}).then(value=>({value}),error=>({error:String(error)}));pending.push(retry);
  try{
   await until(async()=>{const waits=await db.$queryRaw<Array<{n:bigint}>>`select count(*)::bigint n from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like '%report_deliveries%'`;return Number(waits[0].n)>0;});
   if(kind==='session')await auth.revokeRequestSession(request(manager,'/api/auth/logout','POST',{}));
   else if(kind==='role'){const route=await import('../../../src/app/api/merchant/organizations/[organizationId]/memberships/[membershipId]/route');const response=await route.PATCH(request(owner,'/api/merchant/organizations/'+f.organization.id+'/memberships/'+membership.id,'PATCH',{role:'FINANCE_VIEWER',isActive:true,allStalls:true}),{params:Promise.resolve({organizationId:f.organization.id,membershipId:membership.id})});assert.equal(response.status,200,await response.text());}
   else{const route=await import('../../../src/app/api/merchant/stalls/[stallId]/memberships/[membershipId]/route');const response=await route.PATCH(request(owner,'/api/merchant/stalls/'+f.stall.id+'/memberships/'+assignment!.id,'PATCH',{role:'STALL_MANAGER',isActive:false}),{params:Promise.resolve({stallId:f.stall.id,membershipId:assignment!.id})});assert.equal(response.status,200,await response.text());}
  }finally{release();}await locker;const outcome=await retry;assert.match('error'in outcome?outcome.error:'',kind==='session'?/REPORT_SESSION_REVOKED/:/REPORT_MANAGE_REQUIRED/);const after=await db.reportDelivery.findUniqueOrThrow({where:{id:row.id}});assert.deepEqual(after,before);
  const response=await http.reportHttp(request(manager,'/api/merchant/organizations/'+f.organization.id+'/report-deliveries/'+row.id+'/retry','POST',{expectedVersion:before.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'}),'retry',f.organization.id,row.id);assert.ok([401,403,404].includes(response.status));results.push({name:'actual-held-retry-current-'+kind+'-revocation',status:'PASS',membership,assignment,before,after,apiStatus:response.status});
 }
 for(const kind of bundle==='diagnostic-stall'?['active-stall']:['platform-role','active-stall']){
  const f=await scope(),who=await actor('PLATFORM_ADMIN'),row=await delivery(f,'LOSS');await worker.processReportDelivery(row.id);const before=await db.reportDelivery.findUniqueOrThrow({where:{id:row.id}});mock.holdLookup(row.id);
  const reconcile=operations.reconcileReportDelivery({...access(who,f.organization.id),isPlatformAdmin:true},row.id,{expectedVersion:before.executionVersion}).then(value=>({value}),error=>({error:String(error)}));pending.push(reconcile);await until(async()=>mock.events.some(e=>e.key.endsWith(row.id)&&e.phase==='lookup-held'));
  let revoked:unknown;try{if(kind==='platform-role'){const preimage=await db.profile.findUniqueOrThrow({where:{id:who.id}});await db.profile.update({where:{id:who.id},data:{platformRole:null}});revoked={classification:'OWNED_SERVICE_ROLE_PROFILE_REVOCATION_NO_PLATFORM_ROLE_ROUTE',preimage};}
   else if(bundle==='full'){const preimage=await db.stall.findUniqueOrThrow({where:{id:f.stall.id}});await db.stall.update({where:{id:f.stall.id},data:{isActive:false}});revoked={classification:'OWNED_SERVICE_ROLE_STALL_REVOCATION_NOT_PUBLIC_API',preimage};}
   else{const route=await import('../../../src/app/api/merchant/stalls/[stallId]/route');const response=await route.PATCH(request(owner,'/api/merchant/stalls/'+f.stall.id,'PATCH',{operation:'UPDATE_OPERATIONS',businessStatus:'CLOSED',orderingEnabled:false,isActive:false,confirmation:'DEACTIVATE'}),{params:Promise.resolve({stallId:f.stall.id})});const responseText=await response.text();writeFileSync(`${d}/${label}-stall-api-response.json`,JSON.stringify({status:response.status,body:responseText,before:f.stall,after:await db.stall.findUniqueOrThrow({where:{id:f.stall.id}})},null,2)+'\n',{flag:'wx'});assert.equal(response.status,200,responseText);revoked={classification:'ACTUAL_STALL_DEACTIVATION_API',preimage:f.stall};}
  }finally{mock.releaseLookup(row.id);}const outcome=await reconcile;assert.match('error'in outcome?outcome.error:'',kind==='platform-role'?/REPORT_RECONCILE_REQUIRED/:/REPORT_CURRENT_SCOPE_CHANGED/);const after=await db.reportDelivery.findUniqueOrThrow({where:{id:row.id}});assert.deepEqual(after,before);results.push({name:'held-lookup-current-'+kind+'-revocation',status:'PASS',revoked,before,after});
 }
 if(bundle==='diagnostic-stall')throw Error('DIAGNOSTIC_STALL_UNEXPECTED_SUCCESS');
 // The fifth claim is reached only through four real local adapter rejections and authorized retries.
 const fifthScope=await scope(),fifth=await delivery(fifthScope,'REJECT');let first:Awaited<ReturnType<typeof db.reportDelivery.findUniqueOrThrow>>|undefined;
 for(let n=1;n<=4;n++){await worker.processReportDelivery(fifth.id);const row=await db.reportDelivery.findUniqueOrThrow({where:{id:fifth.id}});first??=row;assert.equal(row.attemptCount,n);await operations.retryReportDelivery(access(owner,fifthScope.organization.id),fifth.id,{expectedVersion:row.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'});}
 const child=fork(new URL('./crash-executor.mts',import.meta.url),['before-effect',fifth.id,fifth.organizationId,'4'],{execArgv:['--import','tsx'],silent:true,env:process.env});children.push(child);let out='',err='';child.stdout!.on('data',v=>{out+=v;});child.stderr!.on('data',v=>{err+=v;});
 const checkpointMessage=await new Promise<unknown>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('FIFTH_CHILD_CHECKPOINT_TIMEOUT')),20000);child.once('message',m=>{clearTimeout(timer);resolve(m);});child.once('exit',code=>{clearTimeout(timer);reject(Error('FIFTH_CHILD_EARLY_EXIT_'+code));});});assert.ok(checkpointMessage&&typeof checkpointMessage==='object'&&'pid'in checkpointMessage&&'claim'in checkpointMessage);const checkpoint=checkpointMessage as {pid:number;claim:Parameters<typeof execution.authorizeReportEffect>[0]};assert.equal(checkpoint.pid,child.pid);
 const atCrash=await db.reportDelivery.findUniqueOrThrow({where:{id:fifth.id}});assert.equal(atCrash.attemptCount,5);assert.equal(atCrash.effectState,'NOT_STARTED');const exited=new Promise(resolve=>child.once('exit',(code,signal)=>resolve({code,signal})));child.kill();const exit=await exited;writeFileSync(`${d}/${label}-fifth-child.stdout.log`,out,{flag:'wx'});writeFileSync(`${d}/${label}-fifth-child.stderr.log`,err,{flag:'wx'});writeFileSync(`${d}/${label}-fifth-crash.json`,JSON.stringify({checkpoint,atCrash,exit},null,2)+'\n',{flag:'wx'});
 const waitStart=new Date();while(Date.now()<=atCrash.leaseExpiresAt!.getTime()+100){assert.ok(Date.now()-waitStart.getTime()<100000);await new Promise(r=>setTimeout(r,1000));}
 const ownershipFiles=readdirSync(d).filter(name=>/^(?:(?:worker|claim|operations|authority)-[0-9]+-scope-[0-9a-f-]+|red-owned-fixtures|db-contract-fixture(?:-[46])?|db-contract-scope-[46])\.json$/.test(name)),owned=new Set(organizations);for(const file of ownershipFiles){const value=JSON.parse(readFileSync(`${d}/${file}`,'utf8')),id=value.organization?.id??value.organizationId;if(id)owned.add(id);}
 for(let cycle=0;cycle<10;cycle++){const row=await db.reportDelivery.findUniqueOrThrow({where:{id:fifth.id}});if(!row.leaseToken)break;const eligible=await db.$queryRaw<Array<{id:string;organization_id:string;database_now:Date}>>`select id,organization_id,clock_timestamp() database_now from public.report_deliveries where (status='PROCESSING' and lease_expires_at<=clock_timestamp()) or (status in ('PROCESSING','FAILURE') and intent_json is null and effect_state is null) order by created_at,id`;writeFileSync(`${d}/${label}-fifth-recovery-${cycle}-before.json`,JSON.stringify({ownershipFiles,owned:[...owned],eligible},null,2)+'\n',{flag:'wx'});assert.ok(eligible.length>0&&eligible.every(r=>owned.has(r.organization_id)),'GLOBAL_RECOVERY_UNOWNED_STOP');await execution.recoverReportDeliveries();}
 const terminal=await db.reportDelivery.findUniqueOrThrow({where:{id:fifth.id}});assert.equal(terminal.status,'FAILURE');assert.equal(terminal.effectState,'REJECTED');assert.equal(terminal.attemptCount,5);assert.equal(terminal.leaseToken,null);assert.equal(terminal.errorCode,'WORKER_ATTEMPTS_EXHAUSTED');assert.equal(terminal.nextAttemptAt,null);assert.equal(terminal.snapshotHash,first!.snapshotHash);assert.deepEqual(terminal.intentJson,first!.intentJson);assert.equal(mock.events.filter(e=>e.key.endsWith(fifth.id)&&e.phase==='request').length,4);await assert.rejects(operations.retryReportDelivery(access(owner,fifthScope.organization.id),fifth.id,{expectedVersion:terminal.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'}),/REPORT_RETRY_UNSAFE/);await assert.rejects(execution.authorizeReportEffect(checkpoint.claim,terminal.snapshotHash!),/REPORT_LEASE_STALE/);results.push({name:'actual-fifth-pre-effect-process-crash-natural-expiry-terminal-no-fifth-network',status:'PASS',waitStart,waitEnd:new Date(),terminal});
 // Additive independent rows for mounted retry, stale, held switch, and held logout flows.
 const ui=JSON.parse(readFileSync(`${d}/operations-3-ui-fixtures.json`,'utf8'));const uiSchedule=await db.reportSchedule.findFirstOrThrow({where:{organizationId:ui.organizationId}});const extraIds:Record<string,string>={};organizations.add(ui.organizationId);
 for(const name of ['permitted','stale','switch','logout']){const row=await delivery({organization:{id:ui.organizationId},schedule:uiSchedule} as Awaited<ReturnType<typeof scope>>,'REJECT');await worker.processReportDelivery(row.id);extraIds[name]=row.id;}
 const stallScope=await scope(),stallDelivery=await delivery(stallScope);const stallDeactivation={organizationId:stallScope.organization.id,stallId:stallScope.stall.id,actorId:owner.id,deliveryId:stallDelivery.id};
 writeFileSync(`${d}/${label}-ui-extra-fixtures.json`,JSON.stringify({base:'operations-3-ui-fixtures.json',extraIds,stallDeactivation,at:new Date().toISOString()},null,2)+'\n',{flag:'wx'});
 console.log(JSON.stringify({status:'PASS',checks:results.length,simulated:true}));
}catch(error){writeFileSync(`${d}/${label}-original-error.json`,JSON.stringify({error:String(error),stack:(error as Error).stack,results,at:new Date().toISOString()},null,2)+'\n',{flag:'wx'});throw error;}finally{effect.releaseAllEffects();for(const child of children)if(child.exitCode===null&&child.signalCode===null)child.kill();globalThis.fetch=fetchBefore;let cleanupError:unknown;try{await server.close();}catch(error){cleanupError=error;writeFileSync(`${d}/${label}-cleanup-error.json`,JSON.stringify({error:String(error),stack:(error as Error).stack})+'\n',{flag:'wx'});}await Promise.allSettled(pending);writeFileSync(`${d}/${label}-authority-result.json`,JSON.stringify({at:new Date().toISOString(),results,fixtures,events:mock.events,effectBindings,simulated:true},null,2)+'\n',{flag:'wx'});writeFileSync(`${d}/${label}-mock-closed.json`,JSON.stringify({closed:!cleanupError,origin:server.origin,at:new Date().toISOString()})+'\n',{flag:'wx'});await db.$disconnect();await(await import('../../../src/lib/prisma')).prisma.$disconnect();}
