import {Redirect,router,useLocalSearchParams} from "expo-router";
import {Pressable,ScrollView,Text,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {applicationDetailResultSchema} from "@stallorder/contracts/operations/v1";
import {useSession} from "../../src/auth/session-context";
import {useNativeScope,useNativeRead} from "../../src/operations/query";
import {nativeRequest} from "../../src/api/operations";
export default function ApplicationScreen(){const {applicationId}=useLocalSearchParams<{applicationId:string}>();const {bootstrapData,runAuthenticated}=useSession();const scope=useNativeScope();const detail=useNativeRead(scope.data,"native-application",{applicationId},()=>runAuthenticated((token,device)=>nativeRequest(token,device,"/operations/admin-applications/"+encodeURIComponent(applicationId),applicationDetailResultSchema)));if(!bootstrapData)return <Redirect href="/login"/>;if(bootstrapData.principal.platformRole!=="PLATFORM_ADMIN")return <Text accessibilityRole="alert">無權存取平台管理</Text>;return <SafeAreaView style={{flex:1}}><ScrollView contentContainerStyle={{padding:20,gap:12}}><Pressable accessibilityRole="button" style={{minHeight:48,minWidth:48}} onPress={()=>router.back()}><Text>返回</Text></Pressable><Text style={{fontSize:26}}>商家申請明細</Text>{detail.error&&<Text accessibilityRole="alert">無法讀取申請明細</Text>}{detail.data&&!detail.error&&<View style={{gap:12}}>{[
 ['申請編號',detail.data.detail.applicationNumber],['商家名稱',detail.data.detail.merchantName],['申請人',detail.data.detail.applicantDisplayName],['聯絡信箱',detail.data.detail.applicantEmail],['聯絡電話',detail.data.detail.phone],['攤位名稱',detail.data.detail.stallName],['營業地址',detail.data.detail.businessAddress],['城市',detail.data.detail.city],['業務說明',detail.data.detail.merchantDescription],['公開審核說明',detail.data.detail.publicReviewNote],['內部審核備註',detail.data.detail.internalReviewNote],['負責審核者',detail.data.detail.assignedReviewer?.displayName]
 ].map(([label,value])=><View key={label}><Text style={{fontWeight:'700'}}>{label}</Text><Text selectable>{value||'未提供'}</Text></View>)}</View>}<Text>行動版目前提供唯讀查詢，審核與高風險操作尚未開放。</Text><Pressable accessibilityRole="button" style={{minHeight:48,minWidth:48}} onPress={()=>router.push({pathname:"/inbox",params:{applicationId}})}><Text>此申請的通知</Text></Pressable></ScrollView></SafeAreaView>}
