import Link from "next/link";
import type { MerchantApplicationRiskLevel, MerchantApplicationStatus } from "@prisma/client";
import { getRequestAppLocale } from "@/lib/app-locale-server";
import { formatAppDate, formatAppNumber } from "@/lib/locale-format";
import { merchantApplicationStatusLabels } from "@/lib/merchant-application-contract";
import { createAdminTranslator, getAdminCodeLabel, type AdminMessageKey } from "@/lib/messages/admin";
import { listMerchantApplications, type MerchantApplicationListFilter } from "@/server/merchant-applications/merchant-application-admin-service";

const statuses = Object.keys(merchantApplicationStatusLabels) as MerchantApplicationStatus[];
const riskLevels: MerchantApplicationRiskLevel[] = ["LOW", "MEDIUM", "HIGH", "BLOCKED"];

export default async function MerchantApplicationsAdminPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [query, { locale }] = await Promise.all([searchParams, getRequestAppLocale()]);
  const applications = await listMerchantApplications(parseFilters(query));
  const m = createAdminTranslator(locale);
  const actionLabel = (status: MerchantApplicationStatus) => m(status === "PENDING_REVIEW" ? "Review" : status === "SUBMITTED" || status === "NEEDS_INFO" ? "Track" : "View record");

  return (
    <main className="mx-auto min-h-[calc(100vh-76px)] max-w-7xl px-4 py-7 md:px-8">
      <header><h1 className="text-3xl font-semibold">{m("Merchant application review")}</h1><p className="mt-2 text-sm text-stone-600">{m("All applications require manual approval. Submission does not create a merchant, and QR remains paused after approval.")}</p></header>
      <form className="mt-6 grid gap-3 border-y border-stone-200 py-4 sm:grid-cols-2 lg:grid-cols-6">
        <FilterSelect name="status" label={m("Status")} value={value(query.status)} allLabel={m("All")}>{statuses.map((status) => <option key={status} value={status}>{getAdminCodeLabel(locale, status)}</option>)}</FilterSelect>
        <FilterSelect name="riskLevel" label={m("Risk")} value={value(query.riskLevel)} allLabel={m("All")}>{riskLevels.map((risk) => <option key={risk} value={risk}>{getAdminCodeLabel(locale, risk)}</option>)}</FilterSelect>
        <FilterSelect name="duplicateReason" label={m("Duplicate signal")} value={value(query.duplicateReason)} allLabel={m("All")}><option value="DUPLICATE_EMAIL">{m("Email")}</option><option value="DUPLICATE_PHONE">{m("Phone")}</option><option value="DUPLICATE_SLUG">{m("URL / stall code")}</option></FilterSelect>
        <FilterSelect name="reviewer" label={m("Reviewer")} value={value(query.reviewer)} allLabel={m("All")}><option value="UNASSIGNED">{m("Unassigned")}</option><option value="ASSIGNED">{m("Assigned")}</option></FilterSelect>
        <FilterSelect name="submitted" label={m("Submitted time")} value={value(query.submitted)} allLabel={m("All")}><option value="TODAY">{m("Today")}</option><option value="OLDER_THAN_2_DAYS">{m("Older than 2 days")}</option></FilterSelect>
        <div className="flex items-end gap-2"><button type="submit" className="min-h-11 rounded-md bg-teal-700 px-4 text-sm font-semibold text-white">{m("Apply")}</button><Link href="/admin/merchant-applications" className="inline-flex min-h-11 items-center rounded-md px-3 text-sm font-semibold text-stone-700">{m("Clear")}</Link></div>
      </form>
      <div data-testid="merchant-applications-mobile-list" className="mt-5 grid gap-3 md:hidden">
        {applications.map((application) => <article key={application.id} className="rounded-md border border-stone-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold text-teal-800">{application.applicationNumber}</p><h2 className="mt-1 break-words text-lg font-semibold">{application.merchantName ?? m("Not entered")}</h2><p className="mt-1 break-all text-sm text-stone-500">{application.applicantDisplayName} · {application.applicantEmail}</p></div><span className={`shrink-0 rounded-md px-2 py-1 text-xs font-semibold ${application.riskLevel === "HIGH" || application.riskLevel === "BLOCKED" ? "bg-red-50 text-red-800" : application.riskLevel === "MEDIUM" ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}>{m("Risk: {risk}", { risk: getAdminCodeLabel(locale, application.riskLevel) })}</span></div><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><MobileDetail label={m("Status")} value={getAdminCodeLabel(locale, application.status)} /><MobileDetail label={m("Submitted date")} value={application.submittedAt ? formatAppDate(locale, application.submittedAt) : "-"} /><MobileDetail label={m("Business types")} value={application.businessType ? getAdminCodeLabel(locale, application.businessType) : "-"} /><MobileDetail label={m("Estimated daily orders")} value={application.estimatedDailyOrders === null ? "-" : formatAppNumber(locale, application.estimatedDailyOrders)} /><MobileDetail label={m("Plan")} value={application.requestedPlanCode} /><MobileDetail label={m("Reviewer")} value={application.assignedReviewer?.displayName ?? m("Unassigned")} /></dl><Link href={`/admin/merchant-applications/${application.id}`} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-md border border-teal-700 px-4 text-sm font-semibold text-teal-800">{actionLabel(application.status)}</Link></article>)}
      </div>
      <div data-testid="merchant-applications-desktop-table" className="mt-5 hidden overflow-x-auto border-y border-stone-200 md:block"><table className="w-full min-w-[1320px] text-left text-sm"><thead className="bg-stone-50 text-stone-600"><tr>{(["Application number", "Merchant", "Applicant", "Phone", "Type", "Plan", "Daily orders", "Status", "Risk", "Submitted date", "Reviewer", "Actions"] as AdminMessageKey[]).map((label) => <th key={label} className="px-3 py-3">{m(label)}</th>)}</tr></thead><tbody className="divide-y divide-stone-200">{applications.map((application) => <tr key={application.id}><td className="px-3 py-4 font-semibold">{application.applicationNumber}</td><td className="px-3 py-4">{application.merchantName ?? m("Not entered")}</td><td className="px-3 py-4"><span className="block">{application.applicantDisplayName}</span><span className="text-xs text-stone-500">{application.applicantEmail}</span></td><td className="px-3 py-4">{application.phone ?? "-"}</td><td className="px-3 py-4">{application.businessType ? getAdminCodeLabel(locale, application.businessType) : "-"}</td><td className="px-3 py-4">{application.requestedPlanCode}</td><td className="px-3 py-4 text-right">{application.estimatedDailyOrders === null ? "-" : formatAppNumber(locale, application.estimatedDailyOrders)}</td><td className="px-3 py-4">{getAdminCodeLabel(locale, application.status)}</td><td className="px-3 py-4 font-semibold">{getAdminCodeLabel(locale, application.riskLevel)}</td><td className="px-3 py-4">{application.submittedAt ? formatAppDate(locale, application.submittedAt) : "-"}</td><td className="px-3 py-4">{application.assignedReviewer?.displayName ?? m("Unassigned")}</td><td className="px-3 py-4 text-right"><Link href={`/admin/merchant-applications/${application.id}`} className="font-semibold text-teal-800">{actionLabel(application.status)}</Link></td></tr>)}</tbody></table></div>
      {applications.length === 0 ? <p className="mt-5 border-y border-stone-200 px-3 py-8 text-sm text-stone-500">{m("There are no matching applications.")}</p> : null}
    </main>
  );
}

function FilterSelect({ name, label, value: selected, allLabel, children }: { name: string; label: string; value: string; allLabel: string; children: React.ReactNode }) { return <label className="text-sm font-medium"><span className="mb-1 block">{label}</span><select name={name} defaultValue={selected} className="min-h-11 w-full border border-stone-300 bg-white px-3"><option value="">{allLabel}</option>{children}</select></label>; }
function MobileDetail({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-xs font-semibold text-stone-500">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>; }
function parseFilters(query: Record<string, string | string[] | undefined>): MerchantApplicationListFilter { const status = value(query.status); const riskLevel = value(query.riskLevel); const duplicateReason = value(query.duplicateReason); const reviewer = value(query.reviewer); const submitted = value(query.submitted); return { status: statuses.includes(status as MerchantApplicationStatus) ? status as MerchantApplicationStatus : undefined, riskLevel: riskLevels.includes(riskLevel as MerchantApplicationRiskLevel) ? riskLevel as MerchantApplicationRiskLevel : undefined, duplicateReason: ["DUPLICATE_EMAIL", "DUPLICATE_PHONE", "DUPLICATE_SLUG"].includes(duplicateReason) ? duplicateReason as MerchantApplicationListFilter["duplicateReason"] : undefined, reviewer: ["ASSIGNED", "UNASSIGNED"].includes(reviewer) ? reviewer as MerchantApplicationListFilter["reviewer"] : undefined, submitted: ["TODAY", "OLDER_THAN_2_DAYS"].includes(submitted) ? submitted as MerchantApplicationListFilter["submitted"] : undefined }; }
function value(input: string | string[] | undefined) { return typeof input === "string" ? input : ""; }
