import {beforeEach,describe,expect,it,vi} from 'vitest';
const state=vi.hoisted(()=>({jobs:[] as Array<{id:string;status:string;outcome:string;mode:string;firstRequest:string|null;intent:boolean}>,integration:{id:'33333333-3333-4333-8333-333333333333',status:'ACTIVE',publicIdentifier:'1111111111',secretReference:'44444444-4444-4444-8444-444444444444',updatedAt:new Date('2026-01-01Z'),settingsJson:{displayName:'Merchant',officialAccountUrl:'',notifyConfirmed:true,notifyReady:true,notifyCancelled:true,webhookManagement:{version:2,localMock:true,messagingChannelId:'2222222222',senderPolicy:'MERCHANT_OA'}}}}));
const transaction=vi.hoisted(()=>({notificationIntegration:{findFirst:vi.fn(async()=>state.integration),update:vi.fn(async()=>state.integration)},notificationJob:{updateMany:vi.fn(async({where,data})=>{for(const job of state.jobs)if(where.status.in.includes(job.status))Object.assign(job,data);return{count:state.jobs.length};})},$queryRaw:vi.fn(async()=>[{id:state.integration.id}]),$executeRaw:vi.fn(async(strings:TemplateStringsArray,...values:unknown[])=>{const sql=strings.join('?');let count=0;for(const job of state.jobs){if(!['PENDING','FAILED'].includes(job.status))continue;if(sql.includes("delivery_mode='LEGACY'")&&job.mode!=='LEGACY')continue;if(sql.includes("outcome in ('QUEUED','RETRY_SCHEDULED')")&&!['QUEUED','RETRY_SCHEDULED'].includes(job.outcome))continue;if(sql.includes('first_request_at is null')&&job.firstRequest)continue;if(sql.includes('legacy_intent_json is not null')&&!job.intent)continue;job.status='CANCELLED';job.outcome='SUPPRESSED';count++;}return count;})}));
vi.mock('@/lib/prisma',()=>({prisma:{notificationIntegration:{findFirst:vi.fn(async()=>state.integration)},$transaction:vi.fn(async callback=>callback(transaction))}}));
vi.mock('@/server/billing/entitlement-service',()=>({entitlementService:{assertFeatureIncluded:vi.fn(),assertFeatureEnabled:vi.fn()}}));
vi.mock('./notification-secrets',()=>({deleteNotificationSecret:vi.fn(),storeNotificationSecret:vi.fn()}));
import {getLineIntegrationManagerData,disableLineIntegration} from './line-integration-service';
beforeEach(()=>{vi.clearAllMocks();state.jobs=[{id:'queued',status:'PENDING',outcome:'QUEUED',mode:'LEGACY',firstRequest:null,intent:true},{id:'unknown',status:'FAILED',outcome:'MANUAL_REVIEW',mode:'LEGACY',firstRequest:'granted',intent:true},{id:'terminal',status:'FAILED',outcome:'FAILED',mode:'LEGACY',firstRequest:null,intent:true},{id:'platform',status:'PENDING',outcome:'QUEUED',mode:'PLATFORM_OA',firstRequest:null,intent:false},{id:'granted-retry',status:'FAILED',outcome:'RETRY_SCHEDULED',mode:'LEGACY',firstRequest:'granted',intent:true},{id:'historical',status:'FAILED',outcome:'QUEUED',mode:'LEGACY',firstRequest:null,intent:false}];});
describe('legacy integration management compatibility',()=>{
 it('returns the original public settings without admin Messaging/test metadata',async()=>{
  const result=await getLineIntegrationManagerData('org','stall');expect(result.settings).toEqual({displayName:'Merchant',officialAccountUrl:'',notifyConfirmed:true,notifyReady:true,notifyCancelled:true});
 });
 it('disables only known pre-effect legacy work and retains unknown, granted, terminal, platform and historical facts',async()=>{
  const protectedBefore=structuredClone(state.jobs.slice(1));await disableLineIntegration('org','stall');expect(state.jobs[0].status).toBe('CANCELLED');expect(state.jobs.slice(1)).toEqual(protectedBefore);
 });
});
