import { createMessageCatalog } from "@/lib/message-catalog";

export const onboardingStatusMessages = createMessageCatalog(
  {
    applicationTitle: "商家申請", statusDraft: "草稿", statusSubmitted: "已送出", statusPending: "等待審核", statusNeedsInfo: "需要補件", statusApproved: "已核准", statusRejected: "未核准", statusWithdrawn: "已撤回", statusExpired: "已逾期",
    submittedDate: "送出日期", notSubmitted: "尚未送出", lastUpdated: "最後更新", requestedStall: "申請攤位", notProvided: "尚未填寫", publicIdentifier: "公開識別名稱", platformNote: "平台說明", nextStep: "下一步",
    nextSubmitted: "申請已送出，平台將依資料完整性與風險狀態進行人工審核。", nextNeedsInfo: "請依平台說明補充資料並重新送出。", nextApproved: "申請已核准，請完成商家設定與測試訂單；完成前 QR 仍不會開放接單。", nextRejected: "本次申請未核准；如允許重新申請，頁面會顯示重新申請入口。", nextWithdrawn: "本次申請已結束；你可以沿用原資料重新提出新申請，舊案仍會保留供日後查閱。", nextExpired: "申請已逾期，請聯絡平台管理員確認後續處理方式。",
    addInformation: "補充申請資料", merchantSetup: "前往商家設定", reapply: "重新提出申請", invitationTitle: "已有待接受的工作區邀請", invitationDescription: "請使用邀請訊息中的連結，並以受邀的同一個已驗證電子郵件登入。完成邀請前不會建立新的商家申請。", backToLogin: "返回登入",
    withdraw: "撤回申請", withdrawPrompt: "撤回後本次申請將結束，確定要撤回嗎？", confirmWithdraw: "確認撤回", keepApplication: "保留申請", withdrawError: "目前無法撤回申請。", networkError: "目前無法連線，請稍後再試。",
  },
  {
    en: {
      applicationTitle: "Merchant application", statusDraft: "Draft", statusSubmitted: "Submitted", statusPending: "Pending review", statusNeedsInfo: "More information needed", statusApproved: "Approved", statusRejected: "Not approved", statusWithdrawn: "Withdrawn", statusExpired: "Expired",
      submittedDate: "Submitted", notSubmitted: "Not submitted", lastUpdated: "Last updated", requestedStall: "Requested stall", notProvided: "Not provided", publicIdentifier: "Public identifier", platformNote: "Platform note", nextStep: "Next step",
      nextSubmitted: "Your application was submitted and will be reviewed manually for completeness and risk.", nextNeedsInfo: "Add the information requested by the platform and submit again.", nextApproved: "Your application is approved. Complete merchant setup and a test order before QR ordering opens.", nextRejected: "This application was not approved. If reapplication is allowed, a reapply action appears here.", nextWithdrawn: "This application is closed. You can reuse its details in a new application while the old record remains available.", nextExpired: "This application expired. Contact the platform administrator about the next step.",
      addInformation: "Add application details", merchantSetup: "Go to merchant setup", reapply: "Apply again", invitationTitle: "You have a pending workspace invitation", invitationDescription: "Use the link in the invitation and sign in with the same verified email address. A new merchant application will not be created until the invitation is resolved.", backToLogin: "Back to sign in",
      withdraw: "Withdraw application", withdrawPrompt: "Withdrawing closes this application. Are you sure?", confirmWithdraw: "Confirm withdrawal", keepApplication: "Keep application", withdrawError: "The application cannot be withdrawn right now.", networkError: "Unable to connect. Try again later.",
    },
    ja: {
      applicationTitle: "商家申請", statusDraft: "下書き", statusSubmitted: "送信済み", statusPending: "審査待ち", statusNeedsInfo: "追加情報が必要", statusApproved: "承認済み", statusRejected: "未承認", statusWithdrawn: "取り下げ済み", statusExpired: "期限切れ", submittedDate: "送信日", notSubmitted: "未送信", lastUpdated: "最終更新", requestedStall: "申請店舗", notProvided: "未入力", publicIdentifier: "公開識別名", platformNote: "プラットフォームからのお知らせ", nextStep: "次のステップ", nextSubmitted: "申請は送信済みです。情報の完全性とリスクを確認するため手動審査を行います。", nextNeedsInfo: "案内に従って情報を追加し、再送信してください。", nextApproved: "申請は承認されました。QR注文を開始する前に商家設定とテスト注文を完了してください。", nextRejected: "申請は承認されませんでした。再申請可能な場合は、このページに操作が表示されます。", nextWithdrawn: "申請は終了しました。以前の情報を使って新規申請でき、旧申請は履歴に残ります。", nextExpired: "申請の期限が切れました。今後の対応は管理者にお問い合わせください。", addInformation: "申請情報を追加", merchantSetup: "商家設定へ", reapply: "再申請", invitationTitle: "未承諾のワークスペース招待があります", invitationDescription: "招待メッセージのリンクを使い、招待された確認済みメールアドレスでログインしてください。招待が完了するまで新しい商家申請は作成されません。", backToLogin: "ログインに戻る", withdraw: "申請を取り下げる", withdrawPrompt: "取り下げるとこの申請は終了します。よろしいですか？", confirmWithdraw: "取り下げを確定", keepApplication: "申請を残す", withdrawError: "現在、申請を取り下げられません。", networkError: "接続できません。後でもう一度お試しください。",
    },
    ko: {
      applicationTitle: "상점 신청", statusDraft: "초안", statusSubmitted: "제출됨", statusPending: "심사 대기", statusNeedsInfo: "추가 정보 필요", statusApproved: "승인됨", statusRejected: "미승인", statusWithdrawn: "철회됨", statusExpired: "만료됨", submittedDate: "제출일", notSubmitted: "제출되지 않음", lastUpdated: "마지막 업데이트", requestedStall: "신청 매장", notProvided: "입력되지 않음", publicIdentifier: "공개 식별자", platformNote: "플랫폼 안내", nextStep: "다음 단계", nextSubmitted: "신청이 제출되었으며 정보 완성도와 위험 상태를 수동으로 심사합니다.", nextNeedsInfo: "플랫폼 안내에 따라 정보를 보완하고 다시 제출해 주세요.", nextApproved: "신청이 승인되었습니다. QR 주문을 열기 전에 상점 설정과 테스트 주문을 완료하세요.", nextRejected: "이번 신청은 승인되지 않았습니다. 재신청이 허용되면 이 페이지에 재신청 버튼이 표시됩니다.", nextWithdrawn: "신청이 종료되었습니다. 기존 정보를 사용해 새로 신청할 수 있으며 이전 기록은 보관됩니다.", nextExpired: "신청이 만료되었습니다. 다음 절차는 플랫폼 관리자에게 문의하세요.", addInformation: "신청 정보 보완", merchantSetup: "상점 설정으로", reapply: "다시 신청", invitationTitle: "수락 대기 중인 작업 공간 초대가 있습니다", invitationDescription: "초대 메시지의 링크를 사용하고 초대받은 동일한 인증 이메일로 로그인하세요. 초대가 처리될 때까지 새 상점 신청은 생성되지 않습니다.", backToLogin: "로그인으로 돌아가기", withdraw: "신청 철회", withdrawPrompt: "철회하면 이번 신청이 종료됩니다. 철회할까요?", confirmWithdraw: "철회 확인", keepApplication: "신청 유지", withdrawError: "현재 신청을 철회할 수 없습니다.", networkError: "연결할 수 없습니다. 잠시 후 다시 시도해 주세요.",
    },
    vi: {
      applicationTitle: "Đăng ký cửa hàng", statusDraft: "Bản nháp", statusSubmitted: "Đã gửi", statusPending: "Chờ xét duyệt", statusNeedsInfo: "Cần bổ sung", statusApproved: "Đã duyệt", statusRejected: "Không được duyệt", statusWithdrawn: "Đã rút", statusExpired: "Đã hết hạn", submittedDate: "Ngày gửi", notSubmitted: "Chưa gửi", lastUpdated: "Cập nhật lần cuối", requestedStall: "Cửa hàng đăng ký", notProvided: "Chưa điền", publicIdentifier: "Mã công khai", platformNote: "Thông báo từ nền tảng", nextStep: "Bước tiếp theo", nextSubmitted: "Hồ sơ đã được gửi và sẽ được xét duyệt thủ công về độ đầy đủ và rủi ro.", nextNeedsInfo: "Bổ sung thông tin theo yêu cầu của nền tảng rồi gửi lại.", nextApproved: "Hồ sơ đã được duyệt. Hoàn tất cài đặt cửa hàng và đơn thử trước khi mở đặt món QR.", nextRejected: "Hồ sơ lần này không được duyệt. Nếu được phép đăng ký lại, nút đăng ký lại sẽ xuất hiện ở đây.", nextWithdrawn: "Hồ sơ này đã kết thúc. Bạn có thể dùng lại dữ liệu cho hồ sơ mới; hồ sơ cũ vẫn được lưu.", nextExpired: "Hồ sơ đã hết hạn. Hãy liên hệ quản trị viên nền tảng để biết bước tiếp theo.", addInformation: "Bổ sung hồ sơ", merchantSetup: "Đến cài đặt cửa hàng", reapply: "Đăng ký lại", invitationTitle: "Bạn có lời mời vào không gian làm việc đang chờ", invitationDescription: "Dùng liên kết trong lời mời và đăng nhập bằng đúng email đã xác minh được mời. Hệ thống sẽ không tạo hồ sơ cửa hàng mới trước khi xử lý lời mời.", backToLogin: "Quay lại đăng nhập", withdraw: "Rút hồ sơ", withdrawPrompt: "Rút hồ sơ sẽ kết thúc lần đăng ký này. Bạn chắc chắn chứ?", confirmWithdraw: "Xác nhận rút", keepApplication: "Giữ hồ sơ", withdrawError: "Hiện không thể rút hồ sơ.", networkError: "Không thể kết nối. Vui lòng thử lại sau.",
    },
    th: {
      applicationTitle: "ใบสมัครร้าน", statusDraft: "ฉบับร่าง", statusSubmitted: "ส่งแล้ว", statusPending: "รอตรวจสอบ", statusNeedsInfo: "ต้องเพิ่มข้อมูล", statusApproved: "อนุมัติแล้ว", statusRejected: "ไม่อนุมัติ", statusWithdrawn: "ถอนแล้ว", statusExpired: "หมดอายุ", submittedDate: "วันที่ส่ง", notSubmitted: "ยังไม่ส่ง", lastUpdated: "อัปเดตล่าสุด", requestedStall: "ร้านที่สมัคร", notProvided: "ยังไม่กรอก", publicIdentifier: "รหัสสาธารณะ", platformNote: "ข้อความจากแพลตฟอร์ม", nextStep: "ขั้นตอนถัดไป", nextSubmitted: "ส่งใบสมัครแล้ว แพลตฟอร์มจะตรวจสอบความครบถ้วนและความเสี่ยงด้วยตนเอง", nextNeedsInfo: "เพิ่มข้อมูลตามคำแนะนำของแพลตฟอร์มแล้วส่งอีกครั้ง", nextApproved: "ใบสมัครได้รับอนุมัติ โปรดตั้งค่าร้านและทำคำสั่งซื้อทดสอบก่อนเปิดรับออร์เดอร์ QR", nextRejected: "ใบสมัครนี้ไม่ได้รับอนุมัติ หากสมัครใหม่ได้ ปุ่มสมัครใหม่จะแสดงที่นี่", nextWithdrawn: "ใบสมัครนี้สิ้นสุดแล้ว คุณใช้ข้อมูลเดิมสมัครใหม่ได้ และประวัติเดิมจะยังคงอยู่", nextExpired: "ใบสมัครหมดอายุ โปรดติดต่อผู้ดูแลแพลตฟอร์มเพื่อสอบถามขั้นตอนต่อไป", addInformation: "เพิ่มข้อมูลใบสมัคร", merchantSetup: "ไปยังการตั้งค่าร้าน", reapply: "สมัครอีกครั้ง", invitationTitle: "คุณมีคำเชิญเข้าพื้นที่ทำงานที่รอการตอบรับ", invitationDescription: "ใช้ลิงก์ในข้อความเชิญและเข้าสู่ระบบด้วยอีเมลที่ยืนยันแล้วซึ่งได้รับเชิญ ระบบจะไม่สร้างใบสมัครร้านใหม่จนกว่าจะจัดการคำเชิญ", backToLogin: "กลับไปเข้าสู่ระบบ", withdraw: "ถอนใบสมัคร", withdrawPrompt: "การถอนจะสิ้นสุดใบสมัครนี้ ยืนยันถอนหรือไม่?", confirmWithdraw: "ยืนยันถอน", keepApplication: "เก็บใบสมัคร", withdrawError: "ขณะนี้ไม่สามารถถอนใบสมัครได้", networkError: "เชื่อมต่อไม่ได้ โปรดลองอีกครั้งภายหลัง",
    },
  },
);
