import { createMessageCatalog } from "@/lib/message-catalog";

export const onboardingMessages = createMessageCatalog(
  {
    stepApplicant: "申請人", stepMerchant: "商家資料", stepStall: "第一個攤位", stepConsent: "試用與同意",
    slugSuggestionError: "目前無法自動產生公開識別名稱。", slugSuggestionManual: "目前無法自動產生，請自行輸入公開識別名稱。",
    checkFields: "請檢查標示欄位後再繼續。", slugTakenSubmit: "此公開識別名稱已被使用，請更換後再送出。", slugInvalidOrTaken: "此公開識別名稱格式不正確或已被其他攤位使用。", submitError: "目前無法送出商家申請，請稍後再試。", networkError: "目前無法連線，請確認網路後重試。", saveError: "目前無法儲存草稿。", draftSaved: "草稿已儲存", slugPattern: "公開識別名稱只能使用小寫英文字母、數字與連字號，且首尾必須是英文字母或數字。", slugTaken: "此公開識別名稱已被其他攤位使用，請更換後再試。",
    reapplyTitle: "重新申請商家", applicationTitle: "商家申請", reapplyDescription: "已帶入前次資料；送出後會建立新的申請編號並重新進入人工審核。", applicationDescription: "送出後由平台人工審核，不會立即建立商家工作區。", progress: "申請進度", reapplyHistory: "前次申請會保留為歷史紀錄，不會被修改或重新開啟。請重新確認資料與同意事項後再送出。", needsInfo: "平台補件說明：{note}", previous: "上一步", saveDraft: "儲存草稿", next: "下一步", submitting: "送出中...", submit: "送出商家申請",
    emailMissing: "未提供電子郵件", verifiedIdentity: "已驗證登入身分", fieldPhone: "聯絡電話", fieldLineId: "LINE ID（選填）", fieldContactMethod: "偏好聯絡方式", contactPhone: "電話", contactLine: "LINE", contactEmail: "電子郵件",
    fieldMerchantName: "商家或品牌名稱", fieldBusinessType: "營業類型", fieldRegistration: "統一編號（選填）", fieldContactName: "負責聯絡人", fieldBusinessPhone: "商家電話", fieldCity: "縣市", selectCity: "請選擇縣市", fieldAddress: "商家地址", fieldDescription: "商家簡介（選填）",
    fieldStallName: "第一個攤位名稱", fieldStallLocation: "主要營業地點", fieldStartDate: "預計開始日期", fieldDailyOrders: "預估每日訂單", fieldSlug: "公開識別名稱", fieldPlan: "申請方案", slugChecking: "檢查中...", slugAvailable: "此公開識別名稱可使用", slugInvalid: "格式不正確或已被使用", slugGenerating: "正在依商家名稱產生建議...", slugManual: "目前使用自行修改的名稱，系統不會覆蓋。", slugAutomatic: "已依商家名稱自動產生，可直接使用或自行修改。", slugRegenerate: "依商家名稱重新產生",
    multiStaff: "預計邀請其他員工共同使用", multiStaffDescription: "開通後可邀請店員、廚房人員或管理者使用各自帳號。", kitchenView: "預計使用廚房生產看板（KDS）", kitchenViewDescription: "開通後可在廚房看板接收訂單，並更新製作與完成狀態。",
    trialDays: "試用天數", stalls: "攤位", staff: "員工", products: "商品", completedOrders: "完成訂單", daysValue: "{count} 天", stallsValue: "{count} 個", staffValue: "{count} 人", productsValue: "{count} 項", qrValue: "{count} 個", ordersValue: "{count} 筆", trialNotice: "試用期從平台核准日起算；核准後仍需完成設定與測試訂單才會開放接單。", terms: "我同意服務條款", privacy: "我同意隱私權政策", dataProcessing: "我同意資料處理告知事項", confirmInformation: "我確認上述申請資料正確",
    validationCheck: "請勾選「{label}」。", validationFill: "請填寫「{label}」。", validationTooShort: "「{label}」至少需要 {count} 個字元。", validationTooLong: "「{label}」輸入內容過長。", validationFormat: "「{label}」格式不正確，請確認後再試。", validationRange: "「{label}」的數值不在允許範圍內。", validationGeneric: "「{label}」的格式或內容不符合輸入要求。",
    identifierRulesTitle: "公開識別名稱規則", identifierRuleLetters: "只能使用小寫英文字母 a-z", identifierRuleNumbers: "可使用數字 0-9", identifierRuleHyphen: "可使用連字號 -", identifierRuleLength: "長度 3～50 字元", identifierRuleEnds: "第一個與最後一個字元必須是英文字母或數字", identifierRuleUnique: "不可和其他攤位重複",
  },
  {
    en: {
      stepApplicant: "Applicant", stepMerchant: "Merchant details", stepStall: "First stall", stepConsent: "Trial and consent",
      slugSuggestionError: "A public identifier cannot be generated right now.", slugSuggestionManual: "Automatic generation is unavailable. Enter a public identifier manually.", checkFields: "Review the highlighted fields before continuing.", slugTakenSubmit: "This public identifier is already in use. Choose another one before submitting.", slugInvalidOrTaken: "This public identifier is invalid or already used by another stall.", submitError: "The merchant application cannot be submitted right now. Try again later.", networkError: "Unable to connect. Check your network and try again.", saveError: "The draft cannot be saved right now.", draftSaved: "Draft saved", slugPattern: "Use lowercase letters, numbers, and hyphens; the first and last characters must be letters or numbers.", slugTaken: "This public identifier is used by another stall. Choose another one.",
      reapplyTitle: "Reapply as a merchant", applicationTitle: "Merchant application", reapplyDescription: "Your previous details are prefilled. Submitting creates a new application number for manual review.", applicationDescription: "The platform reviews applications manually. A merchant workspace is not created immediately.", progress: "Application progress", reapplyHistory: "The previous application remains in history and will not be changed or reopened. Review all details and consents before submitting.", needsInfo: "Platform request: {note}", previous: "Previous", saveDraft: "Save draft", next: "Next", submitting: "Submitting...", submit: "Submit merchant application",
      emailMissing: "No email provided", verifiedIdentity: "Verified sign-in identity", fieldPhone: "Contact phone", fieldLineId: "LINE ID (optional)", fieldContactMethod: "Preferred contact method", contactPhone: "Phone", contactLine: "LINE", contactEmail: "Email",
      fieldMerchantName: "Merchant or brand name", fieldBusinessType: "Business type", fieldRegistration: "Business registration number (optional)", fieldContactName: "Primary contact", fieldBusinessPhone: "Business phone", fieldCity: "City / county", selectCity: "Select a city or county", fieldAddress: "Business address", fieldDescription: "Business description (optional)",
      fieldStallName: "First stall name", fieldStallLocation: "Primary operating location", fieldStartDate: "Expected start date", fieldDailyOrders: "Estimated daily orders", fieldSlug: "Public identifier", fieldPlan: "Requested plan", slugChecking: "Checking...", slugAvailable: "This public identifier is available", slugInvalid: "Invalid or already in use", slugGenerating: "Generating from the merchant name...", slugManual: "You edited this name, so the system will not overwrite it.", slugAutomatic: "Generated from the merchant name; use it or edit it.", slugRegenerate: "Generate again from merchant name",
      multiStaff: "Invite other staff to use the workspace", multiStaffDescription: "After activation, staff, kitchen members, and managers can use their own accounts.", kitchenView: "Use the kitchen display system (KDS)", kitchenViewDescription: "After activation, the kitchen can receive orders and update preparation status.",
      trialDays: "Trial days", stalls: "Stalls", staff: "Staff", products: "Products", completedOrders: "Completed orders", daysValue: "{count} days", stallsValue: "{count}", staffValue: "{count}", productsValue: "{count}", qrValue: "{count}", ordersValue: "{count}", trialNotice: "The trial starts when the platform approves the application. Setup and a test order are required before accepting orders.", terms: "I agree to the Terms of Service", privacy: "I agree to the Privacy Policy", dataProcessing: "I agree to the data processing notice", confirmInformation: "I confirm the application information is accurate",
      validationCheck: "Select “{label}”.", validationFill: "Complete “{label}”.", validationTooShort: "“{label}” must contain at least {count} characters.", validationTooLong: "“{label}” is too long.", validationFormat: "“{label}” has an invalid format.", validationRange: "“{label}” is outside the allowed range.", validationGeneric: "“{label}” does not meet the input requirements.",
      identifierRulesTitle: "Public identifier rules", identifierRuleLetters: "Use lowercase letters a-z only", identifierRuleNumbers: "Numbers 0-9 are allowed", identifierRuleHyphen: "Hyphens (-) are allowed", identifierRuleLength: "Use 3 to 50 characters", identifierRuleEnds: "The first and last characters must be letters or numbers", identifierRuleUnique: "Must not duplicate another stall",
    },
    ja: {
      stepApplicant: "申請者", stepMerchant: "商家情報", stepStall: "最初の店舗", stepConsent: "試用と同意", slugSuggestionError: "現在、公開識別名を自動生成できません。", slugSuggestionManual: "自動生成できません。公開識別名を手動で入力してください。", checkFields: "強調表示された項目を確認してください。", slugTakenSubmit: "この公開識別名は使用済みです。変更してから送信してください。", slugInvalidOrTaken: "公開識別名が無効、または別の店舗で使用されています。", submitError: "現在、商家申請を送信できません。後でもう一度お試しください。", networkError: "接続できません。ネットワークを確認して再試行してください。", saveError: "現在、下書きを保存できません。", draftSaved: "下書きを保存しました", slugPattern: "小文字英字、数字、ハイフンのみ使用でき、先頭と末尾は英数字にしてください。", slugTaken: "この公開識別名は別の店舗で使用されています。変更してください。",
      reapplyTitle: "商家として再申請", applicationTitle: "商家申請", reapplyDescription: "前回の情報を入力済みです。送信すると新しい申請番号で再審査されます。", applicationDescription: "送信後にプラットフォームが手動審査します。商家ワークスペースはすぐには作成されません。", progress: "申請の進捗", reapplyHistory: "前回の申請は履歴として保持され、変更や再開はされません。情報と同意事項を確認して送信してください。", needsInfo: "プラットフォームからの補足依頼：{note}", previous: "前へ", saveDraft: "下書きを保存", next: "次へ", submitting: "送信中...", submit: "商家申請を送信",
      emailMissing: "メール未登録", verifiedIdentity: "確認済みログインID", fieldPhone: "連絡先電話", fieldLineId: "LINE ID（任意）", fieldContactMethod: "希望連絡方法", contactPhone: "電話", contactLine: "LINE", contactEmail: "メール",
      fieldMerchantName: "商家・ブランド名", fieldBusinessType: "業種", fieldRegistration: "事業者番号（任意）", fieldContactName: "担当者", fieldBusinessPhone: "商家電話", fieldCity: "市・県", selectCity: "市・県を選択", fieldAddress: "商家住所", fieldDescription: "商家紹介（任意）", fieldStallName: "最初の店舗名", fieldStallLocation: "主な営業場所", fieldStartDate: "営業開始予定日", fieldDailyOrders: "1日の予想注文数", fieldSlug: "公開識別名", fieldPlan: "申請プラン", slugChecking: "確認中...", slugAvailable: "この公開識別名は使用できます", slugInvalid: "無効または使用済み", slugGenerating: "商家名から候補を生成中...", slugManual: "手動編集済みのためシステムは上書きしません。", slugAutomatic: "商家名から自動生成しました。そのまま使用または編集できます。", slugRegenerate: "商家名から再生成",
      multiStaff: "ほかのスタッフを招待して利用", multiStaffDescription: "開通後、スタッフ、厨房、管理者が各自のアカウントを利用できます。", kitchenView: "厨房ディスプレイ（KDS）を利用", kitchenViewDescription: "開通後、厨房で注文を受信し調理状況を更新できます。", trialDays: "試用日数", stalls: "店舗", staff: "スタッフ", products: "商品", completedOrders: "完了注文", daysValue: "{count}日", stallsValue: "{count}店", staffValue: "{count}人", productsValue: "{count}品", qrValue: "{count}個", ordersValue: "{count}件", trialNotice: "試用期間は承認日から開始します。注文受付には設定とテスト注文の完了が必要です。", terms: "利用規約に同意します", privacy: "プライバシーポリシーに同意します", dataProcessing: "データ処理通知に同意します", confirmInformation: "申請情報が正しいことを確認します", validationCheck: "「{label}」を選択してください。", validationFill: "「{label}」を入力してください。", validationTooShort: "「{label}」は{count}文字以上必要です。", validationTooLong: "「{label}」が長すぎます。", validationFormat: "「{label}」の形式が正しくありません。", validationRange: "「{label}」が許可範囲外です。", validationGeneric: "「{label}」は入力要件を満たしていません。", identifierRulesTitle: "公開識別名のルール", identifierRuleLetters: "小文字英字 a-z のみ使用可能", identifierRuleNumbers: "数字 0-9 を使用可能", identifierRuleHyphen: "ハイフン（-）を使用可能", identifierRuleLength: "3～50文字", identifierRuleEnds: "先頭と末尾は英数字", identifierRuleUnique: "ほかの店舗と重複不可",
    },
    ko: {
      stepApplicant: "신청자", stepMerchant: "상점 정보", stepStall: "첫 매장", stepConsent: "체험 및 동의", slugSuggestionError: "현재 공개 식별자를 자동 생성할 수 없습니다.", slugSuggestionManual: "자동 생성할 수 없습니다. 공개 식별자를 직접 입력해 주세요.", checkFields: "표시된 항목을 확인한 후 계속해 주세요.", slugTakenSubmit: "이 공개 식별자는 이미 사용 중입니다. 변경 후 제출해 주세요.", slugInvalidOrTaken: "공개 식별자가 올바르지 않거나 다른 매장에서 사용 중입니다.", submitError: "현재 상점 신청을 제출할 수 없습니다. 잠시 후 다시 시도해 주세요.", networkError: "연결할 수 없습니다. 네트워크를 확인하고 다시 시도해 주세요.", saveError: "현재 초안을 저장할 수 없습니다.", draftSaved: "초안 저장됨", slugPattern: "소문자 영문, 숫자, 하이픈만 사용할 수 있고 처음과 끝은 영숫자여야 합니다.", slugTaken: "이 공개 식별자는 다른 매장에서 사용 중입니다. 변경해 주세요.",
      reapplyTitle: "상점 재신청", applicationTitle: "상점 신청", reapplyDescription: "이전 정보가 입력되었습니다. 제출하면 새 신청 번호로 다시 심사됩니다.", applicationDescription: "제출 후 플랫폼이 수동 심사하며 상점 작업 공간은 즉시 생성되지 않습니다.", progress: "신청 진행", reapplyHistory: "이전 신청은 기록으로 보관되며 수정되거나 다시 열리지 않습니다. 정보와 동의 사항을 확인해 주세요.", needsInfo: "플랫폼 보완 요청: {note}", previous: "이전", saveDraft: "초안 저장", next: "다음", submitting: "제출 중...", submit: "상점 신청 제출", emailMissing: "이메일 없음", verifiedIdentity: "인증된 로그인 계정", fieldPhone: "연락 전화", fieldLineId: "LINE ID(선택)", fieldContactMethod: "선호 연락 방법", contactPhone: "전화", contactLine: "LINE", contactEmail: "이메일",
      fieldMerchantName: "상점 또는 브랜드명", fieldBusinessType: "업종", fieldRegistration: "사업자 번호(선택)", fieldContactName: "담당자", fieldBusinessPhone: "상점 전화", fieldCity: "시/군", selectCity: "시/군 선택", fieldAddress: "상점 주소", fieldDescription: "상점 소개(선택)", fieldStallName: "첫 매장명", fieldStallLocation: "주요 영업 위치", fieldStartDate: "예상 시작일", fieldDailyOrders: "예상 일일 주문", fieldSlug: "공개 식별자", fieldPlan: "신청 요금제", slugChecking: "확인 중...", slugAvailable: "사용 가능한 공개 식별자입니다", slugInvalid: "형식 오류 또는 사용 중", slugGenerating: "상점명으로 제안 생성 중...", slugManual: "직접 수정한 이름이므로 시스템이 덮어쓰지 않습니다.", slugAutomatic: "상점명으로 자동 생성했습니다. 그대로 사용하거나 수정하세요.", slugRegenerate: "상점명으로 다시 생성",
      multiStaff: "다른 직원을 초대해 함께 사용", multiStaffDescription: "개통 후 직원, 주방 및 관리자가 각자 계정을 사용할 수 있습니다.", kitchenView: "주방 디스플레이(KDS) 사용", kitchenViewDescription: "개통 후 주방에서 주문을 받고 제작 상태를 업데이트할 수 있습니다.", trialDays: "체험 일수", stalls: "매장", staff: "직원", products: "상품", completedOrders: "완료 주문", daysValue: "{count}일", stallsValue: "{count}개", staffValue: "{count}명", productsValue: "{count}개", qrValue: "{count}개", ordersValue: "{count}건", trialNotice: "체험은 플랫폼 승인일부터 시작됩니다. 주문 접수 전 설정과 테스트 주문을 완료해야 합니다.", terms: "서비스 약관에 동의합니다", privacy: "개인정보 처리방침에 동의합니다", dataProcessing: "데이터 처리 안내에 동의합니다", confirmInformation: "신청 정보가 정확함을 확인합니다", validationCheck: "‘{label}’을 선택해 주세요.", validationFill: "‘{label}’을 입력해 주세요.", validationTooShort: "‘{label}’은 최소 {count}자여야 합니다.", validationTooLong: "‘{label}’이 너무 깁니다.", validationFormat: "‘{label}’ 형식이 올바르지 않습니다.", validationRange: "‘{label}’ 값이 허용 범위를 벗어났습니다.", validationGeneric: "‘{label}’이 입력 요건을 충족하지 않습니다.", identifierRulesTitle: "공개 식별자 규칙", identifierRuleLetters: "영문 소문자 a-z만 사용", identifierRuleNumbers: "숫자 0-9 사용 가능", identifierRuleHyphen: "하이픈(-) 사용 가능", identifierRuleLength: "3~50자", identifierRuleEnds: "첫 글자와 마지막 글자는 영문자 또는 숫자", identifierRuleUnique: "다른 매장과 중복 불가",
    },
    vi: {
      stepApplicant: "Người đăng ký", stepMerchant: "Thông tin cửa hàng", stepStall: "Cửa hàng đầu tiên", stepConsent: "Dùng thử và đồng ý", slugSuggestionError: "Hiện không thể tự tạo mã công khai.", slugSuggestionManual: "Không thể tự tạo. Vui lòng nhập mã công khai.", checkFields: "Kiểm tra các trường được đánh dấu trước khi tiếp tục.", slugTakenSubmit: "Mã công khai này đã được sử dụng. Hãy đổi trước khi gửi.", slugInvalidOrTaken: "Mã công khai không hợp lệ hoặc đã được cửa hàng khác sử dụng.", submitError: "Hiện không thể gửi đơn đăng ký cửa hàng. Vui lòng thử lại sau.", networkError: "Không thể kết nối. Kiểm tra mạng và thử lại.", saveError: "Hiện không thể lưu bản nháp.", draftSaved: "Đã lưu bản nháp", slugPattern: "Chỉ dùng chữ thường, số và dấu gạch nối; ký tự đầu và cuối phải là chữ hoặc số.", slugTaken: "Mã công khai đã được cửa hàng khác sử dụng. Vui lòng đổi.",
      reapplyTitle: "Đăng ký lại cửa hàng", applicationTitle: "Đăng ký cửa hàng", reapplyDescription: "Dữ liệu cũ đã được điền. Khi gửi, hệ thống tạo mã hồ sơ mới để xét duyệt lại.", applicationDescription: "Nền tảng sẽ xét duyệt thủ công sau khi gửi và chưa tạo ngay không gian làm việc.", progress: "Tiến độ đăng ký", reapplyHistory: "Hồ sơ cũ được giữ làm lịch sử và không bị sửa hay mở lại. Hãy kiểm tra dữ liệu và các mục đồng ý trước khi gửi.", needsInfo: "Yêu cầu bổ sung từ nền tảng: {note}", previous: "Trước", saveDraft: "Lưu bản nháp", next: "Tiếp", submitting: "Đang gửi...", submit: "Gửi đăng ký cửa hàng", emailMissing: "Chưa cung cấp email", verifiedIdentity: "Danh tính đăng nhập đã xác minh", fieldPhone: "Điện thoại liên hệ", fieldLineId: "LINE ID (không bắt buộc)", fieldContactMethod: "Cách liên hệ ưu tiên", contactPhone: "Điện thoại", contactLine: "LINE", contactEmail: "Email",
      fieldMerchantName: "Tên cửa hàng hoặc thương hiệu", fieldBusinessType: "Loại hình kinh doanh", fieldRegistration: "Mã đăng ký kinh doanh (không bắt buộc)", fieldContactName: "Người liên hệ", fieldBusinessPhone: "Điện thoại cửa hàng", fieldCity: "Thành phố / huyện", selectCity: "Chọn thành phố / huyện", fieldAddress: "Địa chỉ cửa hàng", fieldDescription: "Giới thiệu cửa hàng (không bắt buộc)", fieldStallName: "Tên cửa hàng đầu tiên", fieldStallLocation: "Địa điểm kinh doanh chính", fieldStartDate: "Ngày dự kiến bắt đầu", fieldDailyOrders: "Số đơn dự kiến mỗi ngày", fieldSlug: "Mã công khai", fieldPlan: "Gói đăng ký", slugChecking: "Đang kiểm tra...", slugAvailable: "Mã công khai này có thể dùng", slugInvalid: "Sai định dạng hoặc đã được dùng", slugGenerating: "Đang tạo gợi ý từ tên cửa hàng...", slugManual: "Bạn đã tự sửa nên hệ thống sẽ không ghi đè.", slugAutomatic: "Đã tự tạo từ tên cửa hàng; có thể dùng hoặc chỉnh sửa.", slugRegenerate: "Tạo lại từ tên cửa hàng",
      multiStaff: "Mời nhân viên khác cùng sử dụng", multiStaffDescription: "Sau khi kích hoạt, nhân viên, bếp và quản lý có thể dùng tài khoản riêng.", kitchenView: "Dùng màn hình bếp (KDS)", kitchenViewDescription: "Sau khi kích hoạt, bếp có thể nhận đơn và cập nhật trạng thái chế biến.", trialDays: "Số ngày dùng thử", stalls: "Cửa hàng", staff: "Nhân viên", products: "Sản phẩm", completedOrders: "Đơn hoàn tất", daysValue: "{count} ngày", stallsValue: "{count}", staffValue: "{count} người", productsValue: "{count} món", qrValue: "{count}", ordersValue: "{count} đơn", trialNotice: "Thời gian dùng thử bắt đầu từ ngày nền tảng phê duyệt. Cần hoàn tất cài đặt và đơn thử trước khi nhận đơn.", terms: "Tôi đồng ý Điều khoản dịch vụ", privacy: "Tôi đồng ý Chính sách quyền riêng tư", dataProcessing: "Tôi đồng ý thông báo xử lý dữ liệu", confirmInformation: "Tôi xác nhận thông tin đăng ký là chính xác", validationCheck: "Hãy chọn “{label}”.", validationFill: "Hãy điền “{label}”.", validationTooShort: "“{label}” cần ít nhất {count} ký tự.", validationTooLong: "“{label}” quá dài.", validationFormat: "Định dạng “{label}” không hợp lệ.", validationRange: "Giá trị “{label}” nằm ngoài phạm vi cho phép.", validationGeneric: "“{label}” không đáp ứng yêu cầu nhập.", identifierRulesTitle: "Quy tắc mã công khai", identifierRuleLetters: "Chỉ dùng chữ thường a-z", identifierRuleNumbers: "Có thể dùng số 0-9", identifierRuleHyphen: "Có thể dùng dấu gạch nối (-)", identifierRuleLength: "Từ 3 đến 50 ký tự", identifierRuleEnds: "Ký tự đầu và cuối phải là chữ hoặc số", identifierRuleUnique: "Không được trùng với cửa hàng khác",
    },
    th: {
      stepApplicant: "ผู้สมัคร", stepMerchant: "ข้อมูลร้าน", stepStall: "ร้านแรก", stepConsent: "ทดลองใช้และยินยอม", slugSuggestionError: "ขณะนี้ไม่สามารถสร้างรหัสสาธารณะอัตโนมัติได้", slugSuggestionManual: "ไม่สามารถสร้างอัตโนมัติ โปรดกรอกรหัสสาธารณะเอง", checkFields: "ตรวจสอบช่องที่ทำเครื่องหมายก่อนดำเนินการต่อ", slugTakenSubmit: "รหัสสาธารณะนี้ถูกใช้แล้ว โปรดเปลี่ยนก่อนส่ง", slugInvalidOrTaken: "รหัสสาธารณะไม่ถูกต้องหรือร้านอื่นใช้แล้ว", submitError: "ขณะนี้ไม่สามารถส่งใบสมัครร้านได้ โปรดลองอีกครั้งภายหลัง", networkError: "เชื่อมต่อไม่ได้ โปรดตรวจสอบเครือข่ายแล้วลองใหม่", saveError: "ขณะนี้ไม่สามารถบันทึกร่างได้", draftSaved: "บันทึกร่างแล้ว", slugPattern: "ใช้ตัวอักษรอังกฤษพิมพ์เล็ก ตัวเลข และขีดกลาง โดยตัวแรกและสุดท้ายต้องเป็นตัวอักษรหรือตัวเลข", slugTaken: "รหัสสาธารณะนี้ถูกใช้โดยร้านอื่น โปรดเปลี่ยน",
      reapplyTitle: "สมัครร้านอีกครั้ง", applicationTitle: "สมัครร้าน", reapplyDescription: "กรอกข้อมูลเดิมให้แล้ว เมื่อส่งจะสร้างเลขใบสมัครใหม่เพื่อพิจารณาอีกครั้ง", applicationDescription: "แพลตฟอร์มจะตรวจสอบด้วยตนเองหลังส่ง และยังไม่สร้างพื้นที่ทำงานทันที", progress: "ความคืบหน้าการสมัคร", reapplyHistory: "ใบสมัครเดิมจะเก็บเป็นประวัติและไม่ถูกแก้ไขหรือเปิดใหม่ โปรดตรวจสอบข้อมูลและการยินยอมก่อนส่ง", needsInfo: "คำขอข้อมูลเพิ่มจากแพลตฟอร์ม: {note}", previous: "ก่อนหน้า", saveDraft: "บันทึกร่าง", next: "ถัดไป", submitting: "กำลังส่ง...", submit: "ส่งใบสมัครร้าน", emailMissing: "ไม่ได้ระบุอีเมล", verifiedIdentity: "ยืนยันบัญชีเข้าสู่ระบบแล้ว", fieldPhone: "โทรศัพท์ติดต่อ", fieldLineId: "LINE ID (ไม่บังคับ)", fieldContactMethod: "วิธีติดต่อที่ต้องการ", contactPhone: "โทรศัพท์", contactLine: "LINE", contactEmail: "อีเมล",
      fieldMerchantName: "ชื่อร้านหรือแบรนด์", fieldBusinessType: "ประเภทธุรกิจ", fieldRegistration: "เลขทะเบียนธุรกิจ (ไม่บังคับ)", fieldContactName: "ผู้ติดต่อหลัก", fieldBusinessPhone: "โทรศัพท์ร้าน", fieldCity: "เมือง / เขต", selectCity: "เลือกเมือง / เขต", fieldAddress: "ที่อยู่ร้าน", fieldDescription: "แนะนำร้าน (ไม่บังคับ)", fieldStallName: "ชื่อร้านแรก", fieldStallLocation: "สถานที่ขายหลัก", fieldStartDate: "วันที่คาดว่าจะเริ่ม", fieldDailyOrders: "คำสั่งซื้อโดยประมาณต่อวัน", fieldSlug: "รหัสสาธารณะ", fieldPlan: "แผนที่สมัคร", slugChecking: "กำลังตรวจสอบ...", slugAvailable: "รหัสสาธารณะนี้ใช้ได้", slugInvalid: "รูปแบบไม่ถูกต้องหรือถูกใช้แล้ว", slugGenerating: "กำลังสร้างคำแนะนำจากชื่อร้าน...", slugManual: "คุณแก้ไขเอง ระบบจะไม่เขียนทับ", slugAutomatic: "สร้างจากชื่อร้านอัตโนมัติ ใช้ได้เลยหรือแก้ไข", slugRegenerate: "สร้างใหม่จากชื่อร้าน",
      multiStaff: "เชิญพนักงานอื่นมาใช้ร่วมกัน", multiStaffDescription: "หลังเปิดใช้งาน พนักงาน ครัว และผู้จัดการใช้บัญชีของตนเองได้", kitchenView: "ใช้จอแสดงผลครัว (KDS)", kitchenViewDescription: "หลังเปิดใช้งาน ครัวรับคำสั่งซื้อและอัปเดตสถานะการทำได้", trialDays: "วันทดลอง", stalls: "ร้าน", staff: "พนักงาน", products: "สินค้า", completedOrders: "คำสั่งซื้อที่เสร็จ", daysValue: "{count} วัน", stallsValue: "{count}", staffValue: "{count} คน", productsValue: "{count} รายการ", qrValue: "{count}", ordersValue: "{count} รายการ", trialNotice: "ช่วงทดลองเริ่มจากวันที่แพลตฟอร์มอนุมัติ ต้องตั้งค่าและทำคำสั่งซื้อทดสอบให้เสร็จก่อนรับออร์เดอร์", terms: "ฉันยอมรับข้อกำหนดการใช้บริการ", privacy: "ฉันยอมรับนโยบายความเป็นส่วนตัว", dataProcessing: "ฉันยอมรับประกาศการประมวลผลข้อมูล", confirmInformation: "ฉันยืนยันว่าข้อมูลสมัครถูกต้อง", validationCheck: "โปรดเลือก “{label}”", validationFill: "โปรดกรอก “{label}”", validationTooShort: "“{label}” ต้องมีอย่างน้อย {count} ตัวอักษร", validationTooLong: "“{label}” ยาวเกินไป", validationFormat: "รูปแบบ “{label}” ไม่ถูกต้อง", validationRange: "ค่า “{label}” อยู่นอกช่วงที่อนุญาต", validationGeneric: "“{label}” ไม่ตรงตามข้อกำหนดการกรอก", identifierRulesTitle: "กฎรหัสสาธารณะ", identifierRuleLetters: "ใช้เฉพาะตัวอักษรพิมพ์เล็ก a-z", identifierRuleNumbers: "ใช้ตัวเลข 0-9 ได้", identifierRuleHyphen: "ใช้ขีดกลาง (-) ได้", identifierRuleLength: "ความยาว 3 ถึง 50 ตัวอักษร", identifierRuleEnds: "ตัวแรกและตัวสุดท้ายต้องเป็นตัวอักษรหรือตัวเลข", identifierRuleUnique: "ต้องไม่ซ้ำกับร้านอื่น",
    },
  },
);
