import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {assertPreClient,projectOldSession,oldSessionFields,sha,evidence} from './database-guard.mjs';
import {assertApplicationOverlaySchema,projectLegacyApplications} from '../../../docs/awesome-optimization/qa/native-session-schema-overlay-v1.mjs';
const source='a'.repeat(64),env={RESPONSIVE_QA_RUN:'true',PLAYWRIGHT_APP_URL:'http://127.0.0.1:3026',PRIMARY_SUPABASE_URL:'http://127.0.0.1:56821',DATABASE_URL:'postgres://test:test@127.0.0.1:56822/postgres',DIRECT_URL:'postgres://test:test@localhost:56822/postgres',B5_ROOT_SOURCE:source};
const pins=JSON.parse(readFileSync(evidence+'/database-helper-pins-v1.json','utf8'));
test('accept exact local source-bound pre-client package',()=>assertPreClient(env,source,pins));
for(const [key,value]of [['DATABASE_URL','postgres://test:test@remote.test:56822/postgres'],['DIRECT_URL','postgres://test:test@localhost:5432/postgres'],['DR_DATABASE_URL','postgres://test:test@remote.test:56822/postgres'],['DR_DIRECT_URL','postgres://test:test@localhost:56822/other'],['PLAYWRIGHT_APP_URL','http://127.0.0.1:3000'],['PRIMARY_SUPABASE_URL','https://remote.test'],['VERCEL','1'],['B5_ROOT_SOURCE','b'.repeat(64)]])test('reject target/source '+key,()=>assert.throws(()=>assertPreClient({...env,[key]:value},source,pins)));
test('reject missing mandatory direct URL',()=>assert.throws(()=>assertPreClient({...env,DIRECT_URL:''},source,pins)));
test('reject pinned input mutation',()=>assert.throws(()=>assertPreClient(env,source,pins,()=>Buffer.from('changed'))));
test('reject current schema drift without accepting it as baseline',()=>assert.throws(()=>assertApplicationOverlaySchema(Buffer.from('changed'))));
const old=JSON.parse(readFileSync('.superpowers/sdd/2026-10-01-awesome-optimization/batch-4c/fix-1/repair-final-readback-before.json','utf8')).sessions[0];
test('old session exact 18 fields survive only additive WEB',()=>{assert.equal(Object.keys(old).length,18);assert.deepEqual(projectOldSession({...old,clientKind:'WEB'}),old);assert.deepEqual(Object.keys(projectOldSession({...old,clientKind:'WEB'})),oldSessionFields);});
test('reject old session audience or unknown field or missing original field',()=>{assert.throws(()=>projectOldSession({...old,clientKind:'NATIVE'}));assert.throws(()=>projectOldSession({...old,clientKind:'WEB',unknown:1}));const row={...old,clientKind:'WEB'};delete row.tokenHash;assert.throws(()=>projectOldSession(row));});
test('session compatibility does not erase an old-field mutation',()=>{const row={...old,clientKind:'WEB',deviceLabel:'changed'};assert.notDeepEqual(projectOldSession(row),old);});
const app=JSON.parse(readFileSync('.superpowers/sdd/2026-10-01-awesome-optimization/batch-2/repair-1/approval-postimages.json','utf8')).cases[0].data.application;
const current=Object.fromEntries(Object.entries(app).flatMap(([key,value])=>key==='currentStep'?[[key,value],['draftVersion',0]]:[[key,value]]));
test('literal Native schema overlay preserves exact old application',()=>assert.deepEqual(projectLegacyApplications([current]),[app]));
test('reject nonzero application default and unknown fields',()=>{assert.throws(()=>projectLegacyApplications([{...current,draftVersion:1}]));assert.throws(()=>projectLegacyApplications([{...current,unknown:1}]));});
test('application compatibility does not erase old-field mutation',()=>assert.notDeepEqual(projectLegacyApplications([{...current,merchantName:'changed'}]),[app]));
test('migration has exactly reviewed 3 statements without comment splitting',()=>{const plan=JSON.parse(readFileSync(evidence+'/database-bundle-v1.json','utf8'));const sql=readFileSync(plan.migration.path,'utf8');assert.equal(sha(sql),plan.migration.sha256);const commands=sql.match(/(?:CREATE TYPE|ALTER TABLE|INSERT INTO)[\s\S]*?;/g);assert.equal(commands.length,3);assert.ok(commands[0].startsWith('CREATE TYPE'));assert.ok(commands[1].startsWith('ALTER TABLE'));assert.ok(commands[2].endsWith('ON CONFLICT (code) DO NOTHING;'));});
test('fixture contains 500 distinct orders and 500 distinct items with no overlap',()=>{const {fixture:f}=JSON.parse(readFileSync(evidence+'/database-bundle-v1.json','utf8'));assert.equal(f.orders.length,500);assert.equal(f.itemIds.length,500);assert.equal(new Set([...f.orders,...f.itemIds]).size,1000);});
