import {randomUUID,createHash} from 'node:crypto';
import {writeFileSync,existsSync} from 'node:fs';
import {test,expect,type Page} from '@playwright/test';
import type {PrismaClient} from '@prisma/client';
import {establishLocalTestSession,gotoLocalPath,dismissStaffStartReminder} from '../local-navigation';
import {openGuardedDatabase,verifyLiveFixture,actors,bindOwnedSession} from '../../docs/awesome-optimization/qa/live-fixture-guard.mjs';
import {readResponsiveBuildProvenance} from '../../scripts/responsive-build-provenance.mjs';
import {proveStaffPushRejection} from '../../scripts/awesome-optimization/batch-4a/mock-staff-push.mjs';
let db:PrismaClient;
const marker=`awesome-b4a-${randomUUID()}`;
const proof:{fixtures:unknown[];checks:unknown[];[key:string]:unknown}={marker,syntheticLocalOnly:true,fixtures:[],checks:[]};
const prefix=`.superpowers/sdd/2026-10-01-awesome-optimization/batch-4a/browser-${process.env.BATCH4A_RECEIPT_LABEL??'first'}`;
test.beforeAll(async()=>{if(existsSync(`${prefix}.json`))throw Error('B4A_IMMUTABLE_RECEIPT_EXISTS');proof.runtime=readResponsiveBuildProvenance({expectedSourceSha256:process.env.AWESOME_QA_EXPECTED_SOURCE_SHA256});db=await openGuardedDatabase();proof.corpus=(await verifyLiveFixture(db)).receipt;});
test.afterAll(async()=>{proof.finishedAt=new Date().toISOString();proof.corpusAfter=(await verifyLiveFixture(db)).receipt;writeFileSync(`${prefix}.json`,JSON.stringify(proof,null,2)+'\n',{flag:'wx'});await db.$disconnect();});
async function profile(){const id=randomUUID(),email=`${marker}-${id}@stallorder.test`;expect(await db.profile.count({where:{id}})).toBe(0);proof.fixtures.push({id,email,preimage:'ABSENT',retained:true});await db.profile.create({data:{id,email,displayName:'通知合成使用者',authIdentities:{create:{provider:'GOOGLE',providerSubject:`${marker}/${id}`,providerEmail:email,providerEmailVerified:true}}}});return id;}
async function login(page:Page,id:string){const row=await db.profile.findUniqueOrThrow({where:{id}});expect(row.email?.startsWith(marker)).toBe(true);await establishLocalTestSession(page,db,id);await gotoLocalPath(page,'/notifications?kind=PERSONAL');}
async function api(page:Page,path:string,method='GET',body?:unknown){return page.evaluate(async({path,method,body})=>{const csrf=document.cookie.split(';').map(v=>v.trim()).find(v=>v.startsWith('stallorder_csrf='))?.slice('stallorder_csrf='.length)??'';const response=await fetch(path,{method,cache:'no-store',headers:{'content-type':'application/json','x-csrf-token':decodeURIComponent(csrf)},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,cache:response.headers.get('cache-control'),body:await response.json()};},{path,method,body});}
async function pendingApplication(id:string){
 const appId=randomUUID(),slug=`b4a-${appId.slice(0,8)}`,p=await db.profile.findUniqueOrThrow({where:{id}});
 const {hashApplicationIdentifier}=await import('../../src/server/merchant-applications/application-identifiers');
 const row=await db.merchantApplication.create({data:{id:appId,applicantProfileId:id,applicantEmail:p.email!,applicantDisplayName:p.displayName,phone:'0967777777',phoneHash:hashApplicationIdentifier('phone',`0967777777-${appId}`),preferredContactMethod:'PHONE',merchantName:'B4a 合成商家',businessType:'NIGHT_MARKET_STALL',contactName:'合成使用者',businessPhone:'0967777777',businessAddress:'臺北市合成路100號',city:'臺北市',stallName:'B4a 合成攤位',stallLocation:'本機測試',requestedSlug:slug,needsMultipleStaff:false,needsKitchenView:false,requestedPlanCode:'TRIAL',termsAccepted:true,privacyAccepted:true,dataProcessingAccepted:true,informationConfirmed:true,status:'PENDING_REVIEW',currentStep:4,draftVersion:3,submittedAt:new Date(),consentedAt:new Date()}});
 proof.fixtures.push({applicationId:row.id,preimage:'ABSENT',retained:true});return row;
}

test('strict cookie API, default consent, empty UI, CAS, CSRF and hydration readiness',async({page,browser},testInfo)=>{
 test.setTimeout(120000);const id=await profile();await login(page,id);await expect(page.getByText('目前篩選範圍沒有通知。',{exact:true})).toBeVisible();
 const prefs=await api(page,'/api/notification-preferences');expect(prefs.status).toBe(200);expect(prefs.cache).toBe('private, no-store');expect(prefs.body.preferences).toEqual({version:1,billingVisible:true,applicationVisible:true,staffOrderVisible:true,analyticsConsent:false});
 for(const path of ['/api/notifications?kind=PERSONAL&profileId='+id,'/api/notifications?kind=PERSONAL&limit=500','/api/notifications?kind=PERSONAL&kind=PERSONAL','/api/notifications?kind=PERSONAL&from=2020-01-01T00:00:00Z&to=2026-09-01T00:00:00Z'])expect((await api(page,path)).status).toBe(400);
 expect((await api(page,'/api/notification-preferences','PATCH',{analyticsConsent:true})).status).toBe(400);
 expect((await api(page,'/api/notification-preferences','PATCH',{version:1,analyticsConsent:true,profileId:id})).status).toBe(400);
 expect(await page.evaluate(async()=> (await fetch('/api/notification-preferences',{method:'PATCH',headers:{'content-type':'application/json','x-csrf-token':'invalid'},body:JSON.stringify({version:1,analyticsConsent:true})})).status)).toBe(403);
 const simultaneous=await Promise.all([api(page,'/api/notification-preferences','PATCH',{version:1,billingVisible:false}),api(page,'/api/notification-preferences','PATCH',{version:1,applicationVisible:false})]);expect(simultaneous.map(v=>v.status).sort()).toEqual([200,409]);expect((await api(page,'/api/notification-preferences')).body.preferences.analyticsConsent).toBe(false);
 await page.reload();await expect(page.getByLabel('同意非必要產品分析（預設關閉）')).not.toBeChecked();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:960});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const targets=await page.locator('main button,main select,main input:not([type=checkbox]),main label:has(input[type=checkbox])').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().height>0).map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));expect(targets.every(v=>v.width>=48&&v.height>=48)).toBe(true);await page.screenshot({path:testInfo.outputPath(`inbox-empty-${width}.png`),fullPage:true});}
 const noJs=await browser.newContext({javaScriptEnabled:false,baseURL:'http://127.0.0.1:3026'});await noJs.addCookies(await page.context().cookies());const staticPage=await noJs.newPage();await staticPage.goto('/notifications?kind=PERSONAL');expect(await staticPage.locator('main button:enabled').count()).toBe(0);await noJs.close();
 const anonymous=await browser.newContext({baseURL:'http://127.0.0.1:3026'});expect((await anonymous.request.get('/api/notifications?kind=PERSONAL')).status()).toBe(401);await anonymous.close();proof.checks.push({case:'real emptyUI/3203907681440/48px/strictAPI/currentCAS/CSRF/defaultfalse/prehydration disabled',status:'PASS',profileId:id});
});

test('actual approval and order trigger→original worker→local418→coalesced Inbox, independent reads and destinations',async({page,browser},testInfo)=>{
 test.setTimeout(300000);const id=await profile();await login(page,id);const application=await pendingApplication(id);
 const adminContext=await browser.newContext({baseURL:'http://127.0.0.1:3026'}),admin=await adminContext.newPage();await establishLocalTestSession(admin,db,actors.admin.id);await bindOwnedSession(db,adminContext,actors.admin);await gotoLocalPath(admin,`/admin/merchant-applications/${application.id}`);
 expect((await api(admin,`/api/admin/merchant-applications/${application.id}`,'PATCH',{action:'APPROVE'})).status).toBe(200);
 const approved=await db.merchantApplication.findUniqueOrThrow({where:{id:application.id}}),organizationId=approved.approvedOrganizationId!;
 const setup=await db.merchantSetupProgress.findUniqueOrThrow({where:{organizationId},include:{stall:true}});const stallId=setup.stallId,slug=setup.stall.slug;
 proof.fixtures.push({organizationId,stallId,source:'actual authorized approval',retained:true});
 const notice=await db.merchantApplicationNotification.findFirstOrThrow({where:{applicationId:application.id,profileId:id},orderBy:{createdAt:'desc'}});
 const adminQuery=`kind=ADMIN_APPLICATION&applicationId=${application.id}`;
 await gotoLocalPath(admin,`/notifications?${adminQuery}`);await admin.getByRole('button',{name:new RegExp(notice.title)}).click();await expect(admin.getByRole('region',{name:'通知詳情'})).toBeVisible();await admin.getByRole('button',{name:'標記為已讀',exact:true}).click();await expect(admin.getByText('已儲存您的已讀紀錄。',{exact:true})).toBeVisible();expect((await db.merchantApplicationNotification.findUniqueOrThrow({where:{id:notice.id}})).readAt).toBeNull();
 await gotoLocalPath(page,'/onboarding/status');await expect(page.getByRole('link',{name:/通知中心/})).toBeVisible();await page.getByRole('link',{name:/通知中心/}).click();await page.getByRole('button',{name:new RegExp(notice.title)}).click();await expect(page.getByRole('region',{name:'通知詳情'}).getByText('尚未標記為已讀。')).toBeVisible();await expect(page.getByRole('link',{name:'開啟相關頁面'})).toHaveAttribute('href','/onboarding/status');await page.getByRole('button',{name:'標記為已讀',exact:true}).click();await expect(page.getByText('已儲存您的已讀紀錄。',{exact:true})).toBeVisible();expect(await db.notificationReadReceipt.count({where:{applicationNotificationId:notice.id}})).toBe(2);
 const staffQuery=`kind=STALL&stallSlug=${slug}`;
 expect((await api(page,`/api/notifications?${staffQuery}`)).body.items).toHaveLength(0);
 for(const step of ['MERCHANT_PROFILE','STALL_PROFILE','CATALOG','PAYMENT_OPTIONS','TEAM','QR_PREVIEW'])expect((await api(page,`/api/merchant/organizations/${organizationId}/setup`,'PATCH',{action:'COMPLETE_STEP',step})).status).toBe(200);
 const token=(await page.context().cookies()).find(v=>v.name==='stallorder_session')!.value;const session=await db.authSession.findUniqueOrThrow({where:{tokenHash:createHash('sha256').update(token).digest('hex')}});
 const chain=await proveStaffPushRejection(db,id,stallId,session.id,async()=>{expect((await api(page,`/api/merchant/organizations/${organizationId}/setup`,'PATCH',{action:'CREATE_TEST_ORDER'})).status).toBe(200);return(await db.order.findFirstOrThrow({where:{organizationId,isTest:true,source:'MERCHANT_SETUP_TEST'}})).id;});proof.checks.push(chain);
 const orderId=chain.orderId;const inbox=await api(page,`/api/notifications?${staffQuery}`);expect(inbox.status).toBe(200);expect(inbox.body.items).toHaveLength(1);expect(inbox.body.items[0].id).toBe(orderId);expect(inbox.body.unreadCount).toBe(1);expect(JSON.stringify(inbox.body)).not.toMatch(/endpoint|receiptToken|encryptedSubscription|customerName|customerPhone|vapid/i);
 await gotoLocalPath(page,`/staff/${slug}`);await dismissStaffStartReminder(page);await page.getByRole('link',{name:/通知中心/}).click();await page.getByRole('button',{name:/StallOrder · 新訂單/}).click();await expect(page.getByRole('link',{name:'開啟相關頁面'})).toHaveAttribute('href',`/staff/${slug}`);await page.getByRole('button',{name:'標記為已讀',exact:true}).click();await expect(page.getByText('已儲存您的已讀紀錄。',{exact:true})).toBeVisible();expect(await db.notificationReadReceipt.count({where:{profileId:id,staffOrderId:orderId}})).toBe(1);
 const secondContext=await browser.newContext({baseURL:'http://127.0.0.1:3026'}),second=await secondContext.newPage();await login(second,id);expect((await api(second,`/api/notifications?${staffQuery}`)).body.unreadCount).toBe(0);const receipt=await db.notificationReadReceipt.findFirstOrThrow({where:{profileId:id,staffOrderId:orderId}});expect(chain.deliveryIds).toContain(receipt.staffDeliveryId);
 const deliveries=await db.staffPushDelivery.findMany({where:{orderId}});await db.staffPushSubscription.updateMany({where:{id:{in:deliveries.map(v=>v.subscriptionId)}},data:{enabled:false}});expect((await api(second,`/api/notifications?${staffQuery}`)).body.items).toHaveLength(1);expect(await db.staffPushDelivery.findMany({where:{orderId}})).toEqual(deliveries);
 const createdAt=new Date(Date.now()-1000);const billingIds=Array.from({length:25},()=>randomUUID());await db.billingNotification.createMany({data:billingIds.map((noticeId,n)=>({id:noticeId,organizationId,notificationType:'TRIAL_ENDING_7_DAYS',title:`合成帳務通知 ${String(n).padStart(2,'0')}`,message:'此為本機通知投影測試。'.repeat(12),createdAt}))});proof.fixtures.push({billingIds,preimage:'ABSENT',syntheticSourceFacts:true});
 const billingQuery=`kind=ORGANIZATION&organizationId=${organizationId}`;const first=await api(page,`/api/notifications?${billingQuery}&limit=10`);const next=await api(page,`/api/notifications?${billingQuery}&limit=10&cursor=${encodeURIComponent(first.body.nextCursor)}`);expect(first.body.items).toHaveLength(10);expect(next.body.items).toHaveLength(10);expect(new Set([...first.body.items,...next.body.items].map(v=>v.id)).size).toBe(20);expect(first.body.unreadCount).toBe(25);expect(next.body.unreadCount).toBe(25);expect((await api(page,`/api/notifications?${billingQuery}&limit=10&cursor=${first.body.nextCursor}x`)).status).toBe(400);
 const peerId=await profile();await db.organizationMembership.create({data:{organizationId,profileId:peerId,role:'FINANCE_VIEWER',allStalls:true}});const peerContext=await browser.newContext({baseURL:'http://127.0.0.1:3026'}),peer=await peerContext.newPage();await login(peer,peerId);
 const billingId=first.body.items[0].id;expect((await api(page,`/api/notifications/BILLING/${billingId}/read?${billingQuery}`,'PATCH',{})).status).toBe(200);expect((await api(peer,`/api/notifications?${billingQuery}`)).body.unreadCount).toBe(25);expect((await db.billingNotification.findUniqueOrThrow({where:{id:billingId}})).readAt).toBeNull();expect((await api(peer,`/api/notifications?${staffQuery}`)).status).toBe(404);
 expect((await page.request.get(`/merchant/billing?organizationId=${organizationId}`)).status()).toBe(404);proof.checks.push({case:'existing billing feature-off guard',status:'PASS',featureOnBillingUi:'NOT_RUN_FEATURE_DISABLED'});
 await gotoLocalPath(page,`/merchant/dashboard?organizationId=${organizationId}`);const merchantEntry=page.getByRole('link',{name:/通知中心/});const entryBox=await merchantEntry.boundingBox();expect(!!entryBox&&entryBox.width>=48&&entryBox.height>=48).toBe(true);await page.getByRole('link',{name:/通知中心/}).click();await expect(page.getByRole('region',{name:'通知列表'})).toBeVisible();await page.getByLabel('只看未讀').check();await page.getByRole('button',{name:'套用篩選',exact:true}).click();await expect(page.getByRole('heading',{name:'未讀 24 則',exact:true})).toBeVisible();await page.getByRole('region',{name:'通知列表'}).getByRole('button').first().focus();await page.keyboard.press('Enter');await expect(page.getByRole('region',{name:'通知詳情'})).toBeVisible();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:960});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:testInfo.outputPath(`inbox-detail-${width}.png`),fullPage:true});}
 await page.getByLabel('顯示帳務通知').uncheck();await page.getByRole('button',{name:'儲存偏好',exact:true}).click();await expect(page.getByText('偏好已儲存。',{exact:true})).toBeVisible();await expect(page.getByText('目前篩選範圍沒有通知。',{exact:true})).toBeVisible();await page.reload();await expect(page.getByLabel('顯示帳務通知')).not.toBeChecked();await expect(page.getByLabel('同意非必要產品分析（預設關閉）')).not.toBeChecked();expect((await api(peer,`/api/notifications?${billingQuery}`)).body.unreadCount).toBe(25);
 const foreignId=await profile(),foreignContext=await browser.newContext({baseURL:'http://127.0.0.1:3026'}),foreign=await foreignContext.newPage();await login(foreign,foreignId);for(const q of [billingQuery,staffQuery,adminQuery])expect((await api(foreign,`/api/notifications?${q}`)).status).toBe(404);expect((await api(foreign,`/api/notifications/APPLICATION/${notice.id}?kind=PERSONAL`)).status).toBe(404);
 await db.stallMembership.create({data:{organizationId,stallId,profileId:foreignId,role:'STAFF'}});expect((await api(foreign,`/api/notifications?${staffQuery}`)).body.items).toHaveLength(0);expect((await api(foreign,`/api/notifications/STAFF_ORDER/${orderId}?${staffQuery}`)).status).toBe(404);
 await gotoLocalPath(page,`/staff/${slug}`);await dismissStaffStartReminder(page);const order=await db.order.findUniqueOrThrow({where:{id:orderId}});await page.getByTestId('staff-order-list-pane').getByRole('button').filter({hasText:order.orderNo}).click();const actions=page.getByTestId('staff-order-actions-pane');await actions.getByRole('button',{name:'確認接單',exact:true}).click();await actions.getByRole('button',{name:'完成訂單',exact:true}).click();await expect.poll(async()=>(await db.order.findUniqueOrThrow({where:{id:orderId}})).status).toBe('COMPLETED');expect(await db.usageEvent.count({where:{organizationId,referenceId:orderId,eventType:'BILLABLE_ORDER_COMPLETED'}})).toBe(0);
 await gotoLocalPath(peer,`/notifications?${billingQuery}`);await expect(peer.getByRole('region',{name:'通知列表'})).toBeVisible();await expect(peer.getByRole('button',{name:/合成帳務通知/}).first()).toBeVisible();
 const membership=await db.organizationMembership.findFirstOrThrow({where:{organizationId,profileId:peerId}});proof.fixtures.push({revocationBefore:membership});await db.organizationMembership.update({where:{id:membership.id},data:{isActive:false}});expect((await api(peer,`/api/notifications?${billingQuery}`)).status).toBe(404);await peer.getByRole('button',{name:'套用篩選',exact:true}).click();await expect(peer.getByText('登入或權限已變更，通知內容已清除。',{exact:true})).toBeVisible();await expect(peer.getByRole('region',{name:'通知列表'})).not.toBeVisible();const deniedPage=await peer.goto(`/notifications?${billingQuery}`);expect(deniedPage?.status()).toBe(404);const billingRedirect=await peer.request.get(`/merchant/billing?organizationId=${organizationId}`,{maxRedirects:0});expect(billingRedirect.status()).toBe(307);expect(billingRedirect.headers().location).toBe('/onboarding');expect(await billingRedirect.text()).not.toContain('合成帳務通知');await expect(peer.getByText('合成帳務通知 00',{exact:true})).not.toBeVisible();
 proof.checks.push({case:'actual merchant/applicant/platform/staff consumers; current independent read, two devices one order, failedPush history, pagination/CAS visibility/foreign/revoked destination',status:'PASS',organizationId,orderId,profileId:id});await Promise.all([adminContext.close(),secondContext.close(),peerContext.close(),foreignContext.close()]);
});

test('mounted loading, retry, throttling, late response, manual invalidation and direct session revocation',async({page},testInfo)=>{
 test.setTimeout(120000);const id=await profile();await login(page,id);
 let release:(()=>void)|undefined;const pending=new Promise<void>(resolve=>{release=resolve;});await page.route('**/api/notifications?*',async route=>{await pending;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({version:'v1',code:'INBOX_UNAVAILABLE'})});});await page.reload();await expect(page.getByText('正在讀取通知…',{exact:true})).toBeVisible();release!();await expect(page.getByRole('button',{name:'重試通知',exact:true})).toBeVisible();await page.unroute('**/api/notifications?*');await page.getByRole('button',{name:'重試通知',exact:true}).click();await expect(page.getByText('目前篩選範圍沒有通知。',{exact:true})).toBeVisible();
 let calls=0;await page.route('**/api/notification-preferences',async route=>{if(route.request().method()==='PATCH'){calls++;await route.fulfill({status:429,headers:{'retry-after':'1'},contentType:'application/json',body:'{}'});}else await route.continue();});await page.getByRole('button',{name:'儲存偏好',exact:true}).click();await expect(page.getByRole('button',{name:'儲存偏好',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'儲存偏好',exact:true})).toBeEnabled({timeout:5000});expect(calls).toBe(1);await page.unroute('**/api/notification-preferences');
 await page.route('**/api/notifications?*',route=>route.fulfill({status:401,contentType:'text/html',body:'Session expired'}));await page.getByRole('button',{name:'套用篩選',exact:true}).click();await expect(page.getByText('登入或權限已變更，通知內容已清除。',{exact:true})).toBeVisible();await expect(page.getByRole('region',{name:'通知偏好'})).not.toBeVisible();await page.unroute('**/api/notifications?*');await page.reload();await expect(page.getByText('目前篩選範圍沒有通知。',{exact:true})).toBeVisible();
 let lateRelease:(()=>void)|undefined;const late=new Promise<void>(resolve=>{lateRelease=resolve;});await page.route('**/api/notifications?*',async route=>{const response=await route.fetch();await late;await route.fulfill({response});});await page.getByRole('button',{name:'套用篩選',exact:true}).click();await expect(page.getByText('正在讀取通知…',{exact:true})).toBeVisible();await page.evaluate(()=>{localStorage.setItem('awesome-b4a-pending-pos-sentinel','retained');window.dispatchEvent(new Event('stallorder:private-view-invalidated'));});await expect(page.getByText('登入或權限已變更，通知內容已清除。',{exact:true})).toBeVisible();lateRelease!();await expect(page.getByRole('region',{name:'通知列表'})).not.toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('awesome-b4a-pending-pos-sentinel'))).toBe('retained');await page.screenshot({path:testInfo.outputPath('denial-cleared.png'),fullPage:true});await page.unroute('**/api/notifications?*');
 await db.authSession.updateMany({where:{profileId:id,revokedAt:null},data:{revokedAt:new Date()}});expect((await api(page,'/api/notifications?kind=PERSONAL')).status).toBe(401);proof.checks.push({case:'mounted loading503retry/429noautoretry/late callback and auth invalidation clears private UI/pendingPOSsentinel retained/current revoked session',status:'PASS'});
});
