import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {spawn} from 'node:child_process';
import {test,expect,type Page} from '@playwright/test';
import type {PrismaClient} from '@prisma/client';
import {establishLocalTestSession,gotoLocalPath} from '../local-navigation';
import {openGuardedDatabase,verifyLiveFixture} from '../../docs/awesome-optimization/qa/live-fixture-guard.mjs';
import {readResponsiveBuildProvenance} from '../../scripts/responsive-build-provenance.mjs';
let db:PrismaClient;
const d='.superpowers/sdd/2026-10-01-awesome-optimization/batch-4b',label=process.env.BATCH4B_RECEIPT_LABEL!;
const f=JSON.parse(readFileSync(`${d}/operations-3-ui-fixtures.json`,'utf8')),extraFile=process.env.B4B_UI_EXTRA_RECEIPT!,extra=JSON.parse(readFileSync(`${d}/${extraFile}`,'utf8')).extraIds;
const proof:{checks:unknown[];[key:string]:unknown}={checks:[],classification:'MOUNTED_LOCAL_SIMULATED_REPORTS'},path=(org=f.organizationId)=>`/merchant/report-schedules?organizationId=${org}`;
test.beforeAll(async()=>{if(!/^authority-[0-9]+-ui-extra-fixtures\.json$/.test(extraFile)||!/^[a-z0-9-]+$/.test(label)||existsSync(`${d}/browser-${label}.json`))throw Error('IMMUTABLE_BROWSER_LABEL_REQUIRED');proof.runtime=readResponsiveBuildProvenance({expectedSourceSha256:process.env.AWESOME_QA_EXPECTED_SOURCE_SHA256});db=await openGuardedDatabase();proof.corpus=(await verifyLiveFixture(db)).receipt;await preserveStaff();});
test.afterAll(async()=>{proof.corpusAfter=(await verifyLiveFixture(db)).receipt;await preserveStaff();proof.finishedAt=new Date().toISOString();writeFileSync(`${d}/browser-${label}.json`,JSON.stringify(proof,null,2)+'\n',{flag:'wx'});await db.$disconnect();});
async function preserveStaff(){const staff=JSON.parse(readFileSync(`${d}/../batch-4a/fix-1/staff-final.json`,'utf8'));const deliveries=await db.staffPushDelivery.findMany({where:{id:{in:staff.deliveries.map((r:{id:string})=>r.id)}},orderBy:{id:'asc'}}),subscriptions=await db.staffPushSubscription.findMany({where:{id:{in:staff.subscriptions.map((r:{id:string})=>r.id)}},orderBy:{id:'asc'}});expect(JSON.stringify(deliveries)===JSON.stringify(staff.deliveries),'protected Staff deliveries unchanged').toBe(true);expect(JSON.stringify(subscriptions)===JSON.stringify(staff.subscriptions),'protected Staff subscriptions unchanged').toBe(true);}
async function login(page:Page,id=f.ownerId){const actor=await db.profile.findUniqueOrThrow({where:{id}});expect(actor.email).toMatch(/^awesome-b4b-ops-/);await establishLocalTestSession(page,db,id);}
const region=(page:Page)=>page.getByRole('region',{name:'報表工作與失敗處理'}),card=(page:Page,id:string)=>page.locator(`[data-report-id="${id}"]`);
async function open(page:Page,id=f.ownerId,org=f.organizationId){await login(page,id);await gotoLocalPath(page,path(org));await expect(region(page)).toBeVisible();}
async function api(page:Page,route:string,body?:unknown,method?:string){return page.evaluate(async({route,body,method})=>{const csrf=decodeURIComponent(document.cookie.split(';').map(v=>v.trim()).find(v=>v.startsWith('stallorder_csrf='))?.slice(16)??'');const response=await fetch(route,{method:method??(body===undefined?'GET':'POST'),cache:'no-store',headers:{'content-type':'application/json','x-csrf-token':csrf},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,body:await response.json()};},{route,body,method});}
function retryPath(id:string){return`/api/merchant/organizations/${f.organizationId}/report-deliveries/${id}/retry`;}
test('mounted report summaries, 48px four widths, keyboard permitted retry through original worker',async({page},testInfo)=>{
 test.setTimeout(120000);await open(page);await expect(card(page,f.ids.accepted)).toContainText('模擬接受（SIMULATED）');await expect(card(page,f.ids.unknown)).toContainText('結果未知・停止重送');await expect(card(page,f.ids.rejected)).toContainText('累計 1／5 次');await expect(card(page,f.ids.accepted).getByRole('button',{name:'重試已確認未接受的工作'})).toBeDisabled();await expect(card(page,f.ids.unknown).getByRole('button',{name:'重試已確認未接受的工作'})).toBeDisabled();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:960});expect(await region(page).evaluate(node=>node.scrollWidth<=window.innerWidth)).toBe(true);const targets=await region(page).locator('button,select').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().height>0).map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));expect(targets.every(v=>v.width>=48&&v.height>=48)).toBe(true);await page.screenshot({path:testInfo.outputPath(`reports-${width}.png`),fullPage:true});}
 const before=await db.reportDelivery.findUniqueOrThrow({where:{id:extra.permitted}});const button=card(page,extra.permitted).getByRole('button',{name:'重試已確認未接受的工作'});await button.focus();await page.keyboard.press('Enter');await expect(region(page).getByText('已排入重試，累計次數保留，最多 5 次。',{exact:true})).toBeVisible();const queued=await db.reportDelivery.findUniqueOrThrow({where:{id:extra.permitted}});expect(queued.status).toBe('PROCESSING');expect(queued.attemptCount).toBe(before.attemptCount);
 const child=spawn(process.execPath,['--import','tsx','scripts/awesome-optimization/batch-4b/process-ui-retry.mts',label,extra.permitted],{env:process.env,windowsHide:true,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>{stdout+=v;});child.stderr.on('data',v=>{stderr+=v;});const exitCode=await new Promise(resolve=>child.once('exit',resolve));writeFileSync(`${d}/browser-${label}-worker.stdout.log`,stdout,{flag:'wx'});writeFileSync(`${d}/browser-${label}-worker.stderr.log`,stderr,{flag:'wx'});expect(exitCode,stderr).toBe(0);
 await region(page).getByRole('button',{name:'重新讀取',exact:true}).click();await expect(card(page,extra.permitted)).toContainText('模擬接受（SIMULATED）');await expect(card(page,extra.permitted)).toContainText('累計 2／5 次');const after=await db.reportDelivery.findUniqueOrThrow({where:{id:extra.permitted}});expect(after.snapshotHash).toBe(before.snapshotHash);expect(after.intentJson).toEqual(before.intentJson);proof.checks.push({case:'mounted48/fourwidth/keyboard/retry actual API→queue→original worker→accepted',before,after});
});
test('mounted actual stall PATCH succeeds and original report worker suppresses revoked scope',async({page},testInfo)=>{
 test.setTimeout(120000);const target=JSON.parse(readFileSync(`${d}/${extraFile}`,'utf8')).stallDeactivation;await open(page,target.actorId,target.organizationId);await expect(card(page,target.deliveryId)).toBeVisible();const before=await db.stall.findUniqueOrThrow({where:{id:target.stallId}});const response=await api(page,`/api/merchant/stalls/${target.stallId}`,{operation:'UPDATE_OPERATIONS',businessStatus:'CLOSED',orderingEnabled:false,isActive:false,confirmation:'DEACTIVATE'},'PATCH');expect(response.status,JSON.stringify(response.body)).toBe(200);expect((await db.stall.findUniqueOrThrow({where:{id:target.stallId}})).isActive).toBe(false);
 const child=spawn(process.execPath,['--import','tsx','scripts/awesome-optimization/batch-4b/process-ui-retry.mts',label,target.deliveryId,'stall-denied'],{env:process.env,windowsHide:true,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',v=>{stdout+=v;});child.stderr.on('data',v=>{stderr+=v;});const exitCode=await new Promise(resolve=>child.once('exit',resolve));writeFileSync(`${d}/browser-${label}-stall-worker.stdout.log`,stdout,{flag:'wx'});writeFileSync(`${d}/browser-${label}-stall-worker.stderr.log`,stderr,{flag:'wx'});expect(exitCode,stderr).toBe(0);await region(page).getByRole('button',{name:'重新讀取',exact:true}).click();await expect(card(page,target.deliveryId)).toContainText('已停止');await expect(card(page,target.deliveryId)).toContainText('REPORT_PRE_EFFECT_DENIED');await page.screenshot({path:testInfo.outputPath('actual-stall-revocation.png'),fullPage:true});proof.checks.push({case:'actual mounted stall PATCH200→readback→original worker scope suppressed no request',before,after:await db.stall.findUniqueOrThrow({where:{id:target.stallId}}),delivery:await db.reportDelivery.findUniqueOrThrow({where:{id:target.deliveryId}})});
});
test('mounted loading, failure retry, empty and finance denied controls',async({page},testInfo)=>{
 test.setTimeout(120000);await login(page);let release!:()=>void;const held=new Promise<void>(r=>{release=r;});await page.route('**/api/merchant/organizations/*/report-deliveries?*',async route=>{await held;await route.fulfill({status:503,contentType:'application/json',body:'{}'});});await gotoLocalPath(page,path());await expect(region(page).getByText('正在讀取報表工作…',{exact:true})).toBeVisible();release();await expect(region(page).getByRole('button',{name:'重試讀取',exact:true})).toBeVisible();await page.unroute('**/api/merchant/organizations/*/report-deliveries?*');await region(page).getByRole('button',{name:'重試讀取',exact:true}).click();await expect(card(page,f.ids.accepted)).toBeVisible();await gotoLocalPath(page,path(f.emptyOrganizationId));await expect(region(page).getByText('目前範圍內沒有報表工作。',{exact:true})).toBeVisible();await page.screenshot({path:testInfo.outputPath('reports-empty.png'),fullPage:true});
 await open(page,f.financeId);await expect(card(page,f.ids.rejected)).toBeVisible();await expect(region(page).getByRole('button',{name:'重試已確認未接受的工作'}).first()).toBeDisabled();expect((await api(page,retryPath(f.ids.rejected),{expectedVersion:4,reason:'RETRY_CONFIRMED_FAILURE'})).status).toBe(403);proof.checks.push({case:'mounted loading503retry/empty/finance VIEW with denied mutations',status:'PASS'});
});
test('mounted stale version refresh and real adapter unsupported reconciliation preserves UNKNOWN',async({page},testInfo)=>{
 test.setTimeout(120000);await open(page);await expect(card(page,extra.stale)).toBeVisible();const before=await db.reportDelivery.findUniqueOrThrow({where:{id:extra.stale}});expect((await api(page,retryPath(extra.stale),{expectedVersion:before.executionVersion,reason:'RETRY_CONFIRMED_FAILURE'})).status).toBe(200);await card(page,extra.stale).getByRole('button',{name:'重試已確認未接受的工作'}).click();await expect(region(page).getByText('工作已更新，請重新讀取後再操作。',{exact:true})).toBeVisible();await expect(card(page,extra.stale)).toContainText('等待執行');expect((await db.reportDelivery.findUniqueOrThrow({where:{id:extra.stale}})).attemptCount).toBe(1);
 await open(page,f.adminId);await expect(card(page,f.ids.unknown)).toBeVisible();const unknown=await db.reportDelivery.findUniqueOrThrow({where:{id:f.ids.unknown}});await card(page,f.ids.unknown).getByRole('button',{name:'核對供應商結果'}).click();await expect(region(page).getByText('尚無可信的供應商結果，工作維持未知且不會重新寄送。',{exact:true})).toBeVisible();expect(await db.reportDelivery.findUniqueOrThrow({where:{id:f.ids.unknown}})).toEqual(unknown);await page.screenshot({path:testInfo.outputPath('reports-unknown.png'),fullPage:true});proof.checks.push({case:'actual mounted stale409 refresh and fixed adapter unsupported reconcile no state change',status:'PASS'});
});
test('mounted held response and authority invalidation immediately clear private report data',async({page},testInfo)=>{
 test.setTimeout(120000);await open(page);await expect(card(page,f.ids.accepted)).toBeVisible();let release!:()=>void;const held=new Promise<void>(r=>{release=r;});await page.route('**/api/merchant/organizations/*/report-deliveries?*',async route=>{const response=await route.fetch();await held;await route.fulfill({response}).catch(()=>{});});await region(page).getByRole('button',{name:'重新讀取',exact:true}).click();await expect(region(page).getByText('正在讀取報表工作…',{exact:true})).toBeVisible();try{await page.evaluate(()=>{localStorage.setItem('awesome-b4b-pending-pos-sentinel','retained');window.dispatchEvent(new Event('stallorder:private-view-invalidated'));});await expect(region(page).getByText('登入或權限已變更，報表工作已清除。',{exact:true})).toBeVisible();}finally{release();}await expect(page.locator('[data-report-id]')).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('awesome-b4b-pending-pos-sentinel'))).toBe('retained');await page.screenshot({path:testInfo.outputPath('reports-authority-cleared.png'),fullPage:true});proof.checks.push({case:'mounted held load + shared authority invalidation no late private repopulation',status:'PASS'});
});
test('actual workspace switch and logout reject held report mutation and load callbacks',async({page},testInfo)=>{
 test.setTimeout(180000);const {getWorkspaceAccess}=await import('../../src/lib/workspace');const destinations=await getWorkspaceAccess(f.ownerId,null),current=destinations.find(v=>v.id===f.organizationId)!,targetIndex=destinations.findIndex(v=>v.id===f.emptyOrganizationId);expect(current).toBeDefined();expect(targetIndex).toBeGreaterThanOrEqual(0);
 for(const heldKind of ['load','mutation'] as const)for(const operation of ['switch','logout'] as const){
  await login(page);await gotoLocalPath(page,`/merchant/dashboard?organizationId=${f.organizationId}`);await gotoLocalPath(page,path());await expect(card(page,f.ids.accepted)).toBeVisible();let release!:()=>void,reached!:()=>void,settled!:()=>void;const held=new Promise<void>(r=>{release=r;}),ready=new Promise<void>(r=>{reached=r;}),finished=new Promise<void>(r=>{settled=r;});const pattern=heldKind==='load'?`**/api/merchant/organizations/${f.organizationId}/report-deliveries?*`:'**/report-deliveries/'+extra[operation]+'/retry';
  await page.route(pattern,async route=>{try{const response=await route.fetch();reached();await held;await route.fulfill({response}).catch(()=>{});}finally{settled();}},{times:1});
  if(heldKind==='load')await region(page).getByRole('button',{name:'重新讀取',exact:true}).click();else await card(page,extra[operation]).getByRole('button',{name:'重試已確認未接受的工作'}).click();await ready;
  const token=(await page.context().cookies()).find(v=>v.name==='stallorder_session')!.value,session=await db.authSession.findUniqueOrThrow({where:{tokenHash:createHash('sha256').update(token).digest('hex')}});await page.goBack();
  try{if(operation==='switch'){await page.getByRole('button',{name:'選擇商家：'+current.businessName,exact:true}).click();const options=page.getByRole('dialog',{name:'選擇商家',exact:true}).getByTestId('compact-switcher-option');expect(await options.allTextContents()).toEqual(destinations.map(v=>v.businessName));await options.nth(targetIndex).click();await page.waitForURL(url=>url.pathname==='/merchant/dashboard'&&url.searchParams.get('organizationId')===f.emptyOrganizationId);await gotoLocalPath(page,path(f.emptyOrganizationId));await expect(region(page).getByText('目前範圍內沒有報表工作。',{exact:true})).toBeVisible();}
   else{const logoutResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/auth/logout'&&response.request().method()==='POST');await page.getByRole('button',{name:'登出',exact:true}).click();expect((await logoutResponse).status()).toBe(200);await page.waitForURL(url=>url.pathname==='/login');expect((await db.authSession.findUniqueOrThrow({where:{id:session.id}})).revokedAt).not.toBeNull();expect((await page.request.get(`/api/merchant/organizations/${f.organizationId}/report-deliveries`)).status()).toBe(401);expect((await page.context().cookies()).some(v=>v.name==='stallorder_session')).toBe(false);}
  }finally{release();await finished;}await expect(page.locator('[data-report-id]')).toHaveCount(0);await expect(page.getByText('已排入重試，累計次數保留，最多 5 次。',{exact:true})).not.toBeVisible();await page.screenshot({path:testInfo.outputPath(`held-${heldKind}-${operation}.png`),fullPage:true});await page.unroute(pattern);proof.checks.push({case:`actual-${operation}-held-${heldKind}-late-callback-discarded`,status:'PASS',sessionId:session.id});
 }
});
