import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {test,expect,type Page} from '@playwright/test';
import type {PrismaClient} from '@prisma/client';
import {establishLocalTestSession,gotoLocalPath} from '../local-navigation';
import {openGuardedDatabase} from '../../docs/awesome-optimization/qa/live-fixture-guard.mjs';
import {preserveOriginals} from '../../docs/awesome-optimization/qa/preserve-originals.mjs';
let db:PrismaClient;
const base='.superpowers/sdd/2026-10-01-awesome-optimization/batch-4b',d=base+'/fix-1',label=process.env.B4B_FIX_LABEL!,f=JSON.parse(readFileSync(base+'/operations-3-ui-fixtures.json','utf8')),historic=JSON.parse(readFileSync(d+'/historical-result.json','utf8'));
const proof:{checks:unknown[];[key:string]:unknown}={checks:[],classification:'ACTUAL_MOUNTED_LOCAL_SYNTHETIC_SESSION_NOT_OAUTH'};
const region=(page:Page)=>page.getByRole('region',{name:'報表工作與失敗處理'}),card=(page:Page,id:string)=>page.locator(`[data-report-id="${id}"]`),apiPath=(org=f.organizationId)=>`/api/merchant/organizations/${org}/report-deliveries`;
test.beforeAll(async()=>{expect(label).toMatch(/^[a-z0-9-]+$/);db=await openGuardedDatabase();proof.before=await preserveAll();});
test.afterAll(async()=>{proof.after=await preserveAll();writeFileSync(d+'/'+label+'-proof.json',JSON.stringify(proof,null,2)+'\n',{flag:'wx'});await db.$disconnect();});
async function preserveAll(){const original=await preserveOriginals(db),old=JSON.parse(readFileSync(base+'/final-report-rows.json','utf8')),staff=JSON.parse(readFileSync(base+'/../batch-4a/fix-1/staff-final.json','utf8'));expect(JSON.stringify(await db.reportDelivery.findMany({where:{id:{in:old.map((r:{id:string})=>r.id)}},orderBy:{id:'asc'}}))===JSON.stringify(old)).toBe(true);const deliveries=await db.staffPushDelivery.findMany({where:{id:{in:staff.deliveries.map((r:{id:string})=>r.id)}},orderBy:{id:'asc'}}),subscriptions=await db.staffPushSubscription.findMany({where:{id:{in:staff.subscriptions.map((r:{id:string})=>r.id)}},orderBy:{id:'asc'}});expect(JSON.stringify(deliveries)===JSON.stringify(staff.deliveries)).toBe(true);expect(JSON.stringify(subscriptions)===JSON.stringify(staff.subscriptions)).toBe(true);return{original,old104FullRowsUnchanged:true,staffFullMetadataUnchanged:true};}
async function open(page:Page,actorId=f.ownerId){const actor=await db.profile.findUniqueOrThrow({where:{id:actorId}});expect(actor.email).toMatch(/^awesome-b4b-ops-/);await establishLocalTestSession(page,db,actorId);await gotoLocalPath(page,`/merchant/report-schedules?organizationId=${f.organizationId}`);await expect(region(page)).toBeVisible();}
test('older unresolved report is reachable in bounded organization calendar range',async({page},testInfo)=>{
 test.setTimeout(120000);await open(page,f.adminId);await expect(card(page,f.ids.unknown)).toBeVisible();const historicalResponse=await page.request.get(apiPath()+'?'+new URLSearchParams({from:historic.range.from,to:historic.range.to,outcome:'UNKNOWN'}));expect(historicalResponse.status()).toBe(200);expect((await historicalResponse.json()).items.some((r:{id:string})=>r.id===historic.id)).toBe(true);await expect(card(page,historic.id)).toHaveCount(0);
 proof.checks.push({case:'historical fixture API visible but absent in today UI before range selection',status:'PASS',id:historic.id});
 const from=region(page).getByLabel('工作開始日期',{exact:true}),to=region(page).getByLabel('工作結束日期',{exact:true});await expect(from).toBeVisible();await from.fill(historic.date);await to.fill(historic.date);const request=page.waitForRequest(r=>new URL(r.url()).pathname===apiPath()&&r.method()==='GET');await region(page).getByRole('button',{name:'套用日期範圍',exact:true}).click();const query=new URL((await request).url()).searchParams;expect(query.get('from')).toBe(historic.range.from);expect(query.get('to')).toBe(historic.range.to);await expect(card(page,historic.id)).toBeVisible();await expect(card(page,historic.id).getByRole('button',{name:'重試已確認未接受的工作'})).toBeDisabled();
 await region(page).getByRole('combobox',{name:'工作狀態',exact:true}).selectOption('UNKNOWN');await expect(card(page,historic.id)).toBeVisible();expect(await from.inputValue()).toBe(historic.date);expect(await to.inputValue()).toBe(historic.date);
 const before=await db.reportDelivery.findUniqueOrThrow({where:{id:historic.id}});await card(page,historic.id).getByRole('button',{name:'核對供應商結果'}).click();await expect(region(page).getByText('尚無可信的供應商結果，工作維持未知且不會重新寄送。',{exact:true})).toBeVisible();expect(await db.reportDelivery.findUniqueOrThrow({where:{id:historic.id}})).toEqual(before);
 expect((await page.request.get(apiPath(f.emptyOrganizationId)+'/'+historic.id)).status()).toBe(404);expect((await page.request.get(apiPath()+'?'+new URLSearchParams({from:'2025-01-01T00:00:00.000Z',to:'2025-05-01T00:00:00.000Z'}))).status()).toBe(400);
 await page.screenshot({path:testInfo.outputPath('historical-unknown.png'),fullPage:true});
 await from.fill('2025-01-01');await to.fill('2025-05-01');await region(page).getByRole('button',{name:'套用日期範圍',exact:true}).click();await expect(region(page).getByRole('alert')).toContainText('最多 90 天');await expect(card(page,historic.id)).toBeVisible();
 const {calendarDateInTimeZone,zonedCalendarDateRangeUtc}=await import('../../src/lib/date-time');const today=calendarDateInTimeZone(new Date(),historic.timezone),expectedRange=zonedCalendarDateRangeUtc(historic.date,today,historic.timezone);await from.fill(historic.date);await to.fill(today);await region(page).getByRole('combobox',{name:'工作狀態',exact:true}).selectOption('ALL');await expect(region(page).getByText('正在讀取報表工作…',{exact:true})).not.toBeVisible();await region(page).getByRole('button',{name:'套用日期範圍',exact:true}).click();await expect(region(page).getByRole('button',{name:'載入更多',exact:true})).toBeVisible();
 const nextRequest=page.waitForRequest(r=>new URL(r.url()).pathname===apiPath()&&new URL(r.url()).searchParams.has('cursor'));await region(page).getByRole('button',{name:'載入更多',exact:true}).click();const paged=new URL((await nextRequest).url()).searchParams;expect(paged.get('from')).toBe(expectedRange.from.toISOString());expect(paged.get('to')).toBe(expectedRange.to.toISOString());expect(paged.get('outcome')).toBe('ALL');await expect(card(page,historic.id)).toBeVisible();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:960});expect(await region(page).evaluate(node=>node.scrollWidth<=window.innerWidth)).toBe(true);const targets=await region(page).locator('button,select,input').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().height>0).map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));expect(targets.every(v=>v.width>=48&&v.height>=48)).toBe(true);await page.screenshot({path:testInfo.outputPath('date-controls-'+width+'.png'),fullPage:true});}
 proof.checks.push({case:'historical calendar selection/filter/unsafe retry denial/unsupported reconcile/foreign404/range400',status:'PASS'});
});
for(const operation of ['retry','reconcile'] as const)test(`actual current session revoked then ${operation}401 clears private report state without event`,async({page},testInfo)=>{
 test.setTimeout(120000);const id=operation==='retry'?f.ids.rejected:f.ids.unknown;await open(page,operation==='retry'?f.ownerId:f.adminId);await expect(card(page,id)).toBeVisible();const before=await db.reportDelivery.findUniqueOrThrow({where:{id}});
 await page.evaluate(()=>{localStorage.setItem('awesome-b4b-fix-pos-sentinel','retained');(window as typeof window&{b4bInvalidationEvents:number}).b4bInvalidationEvents=0;window.addEventListener('stallorder:private-view-invalidated',()=>{(window as typeof window&{b4bInvalidationEvents:number}).b4bInvalidationEvents++;});});
 const token=(await page.context().cookies()).find(v=>v.name==='stallorder_session')!.value,session=await db.authSession.findUniqueOrThrow({where:{tokenHash:createHash('sha256').update(token).digest('hex')}});const {revokeRequestSession}=await import('../../src/lib/auth');await revokeRequestSession(new Request('http://127.0.0.1:3026/api/auth/logout',{headers:{cookie:'stallorder_session='+token}}));expect((await db.authSession.findUniqueOrThrow({where:{id:session.id}})).revokedAt).not.toBeNull();
 const response=page.waitForResponse(r=>new URL(r.url()).pathname===apiPath()+'/'+id+'/'+operation&&r.request().method()==='POST');await card(page,id).getByRole('button',{name:operation==='retry'?'重試已確認未接受的工作':'核對供應商結果'}).click();expect((await response).status()).toBe(401);expect(await db.reportDelivery.findUniqueOrThrow({where:{id}})).toEqual(before);proof.checks.push({case:operation+' actual original service session revoke→mounted401, unchanged row',status:'PASS',sessionId:session.id});
 await expect(region(page).getByText('登入或權限已變更，報表工作已清除。',{exact:true})).toBeVisible();await expect(page.locator('[data-report-id]')).toHaveCount(0);await expect(region(page).getByRole('button',{name:'載入更多',exact:true})).toHaveCount(0);await expect(region(page).getByRole('status')).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('awesome-b4b-fix-pos-sentinel'))).toBe('retained');expect(await page.evaluate(()=>(window as typeof window&{b4bInvalidationEvents:number}).b4bInvalidationEvents)).toBe(0);await page.screenshot({path:testInfo.outputPath(operation+'-401-cleared.png'),fullPage:true});proof.checks.push({case:operation+'401 synchronous private cleanup/no stale notice/no event/POS preserved',status:'PASS'});
});

for(const kind of ['manage','view'] as const)test(`actual current ${kind} permission loss rechecks read authority after mutation403`,async({page,browser},testInfo)=>{
 test.setTimeout(120000);const fixture=JSON.parse(readFileSync(d+'/authority-6-ui-extra-fixtures.json','utf8')).authority[kind],id=f.ids.rejected;await open(page,fixture.actorId);await expect(card(page,id)).toBeVisible();const before=await db.reportDelivery.findUniqueOrThrow({where:{id}});const context=await browser.newContext({baseURL:'http://127.0.0.1:3026'}),ownerPage=await context.newPage();
 try{await open(ownerPage);const changed=await ownerPage.evaluate(async({org,membership,kind})=>{const csrf=decodeURIComponent(document.cookie.split(';').map(v=>v.trim()).find(v=>v.startsWith('stallorder_csrf='))?.slice(16)??'');const response=await fetch('/api/merchant/organizations/'+org+'/memberships/'+membership,{method:'PATCH',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({role:kind==='manage'?'FINANCE_VIEWER':'ORGANIZATION_ADMIN',isActive:kind==='manage',allStalls:true})});return{status:response.status,body:await response.json()};},{org:f.organizationId,membership:fixture.membershipId,kind});expect(changed.status,JSON.stringify(changed.body)).toBe(200);
 const mutation=page.waitForResponse(r=>new URL(r.url()).pathname===apiPath()+'/'+id+'/retry'&&r.request().method()==='POST'),read=page.waitForResponse(r=>new URL(r.url()).pathname===apiPath()&&r.request().method()==='GET');await card(page,id).getByRole('button',{name:'重試已確認未接受的工作'}).click();expect((await mutation).status()).toBe(403);expect((await read).status()).toBe(kind==='manage'?200:403);expect(await db.reportDelivery.findUniqueOrThrow({where:{id}})).toEqual(before);
 if(kind==='manage'){await expect(card(page,id)).toBeVisible();await expect(card(page,id).getByRole('button',{name:'重試已確認未接受的工作'})).toBeDisabled();await expect(region(page).getByText('登入或權限已變更，報表工作已清除。',{exact:true})).toHaveCount(0);}else{await expect(region(page).getByText('登入或權限已變更，報表工作已清除。',{exact:true})).toBeVisible();await expect(page.locator('[data-report-id]')).toHaveCount(0);}await page.screenshot({path:testInfo.outputPath(kind+'-permission-rechecked.png'),fullPage:true});proof.checks.push({case:kind+' actual public membership PATCH→mutation403→currentread authority',status:'PASS',actorId:fixture.actorId,membership:await db.organizationMembership.findUniqueOrThrow({where:{id:fixture.membershipId}})});
 }finally{await context.close();}
});
