import { afterAll, beforeAll, expect, it } from 'vitest';
import { build } from 'esbuild';
import { chromium, type Browser } from '@playwright/test';
import { readFileSync } from 'node:fs';
import path from 'node:path';
type TestWindow = Window & { finish: () => void; testRoot: { unmount: () => void }; live: boolean; patches: number; refreshes: number };
let browser: Browser, javascript: string;
beforeAll(async()=>{
 const mock=(text:string)=>({contents:text,loader:'ts' as const});
 const result=await build({stdin:{contents:`import {StrictMode} from 'react';import {createRoot} from 'react-dom/client';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import {AdminMerchantApplicationActions} from './src/components/admin-merchant-application-actions';window.live=true;window.refreshes=0;window.denials=0;window.patches=0;window.fetch=()=>{window.patches++;return new Promise(resolve=>window.finish=()=>resolve(Response.json({})));};window.testRoot=createRoot(document.getElementById('root'));window.testRoot.render(<StrictMode><QueryClientProvider client={new QueryClient()}><AdminMerchantApplicationActions applicationId="00000000-0000-4000-8000-000000000001" status="PENDING_REVIEW" reviewers={[]}/></QueryClientProvider></StrictMode>);`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'},plugins:[{name:'actual-action-seams',setup(b){b.onResolve({filter:/^next\/navigation$|^@\/components\/operations-query-provider$|^@\/lib\/messages\/admin-client$|^@\/lib\/csrf-client$/},a=>({path:a.path,namespace:'seam'}));b.onLoad({filter:/.*/,namespace:'seam'},a=>mock(a.path==='@/lib/csrf-client'?'export const csrfHeaders=()=>({"content-type":"application/json"});':a.path==='next/navigation'?'export const useRouter=()=>({refresh:()=>window.refreshes++});':a.path.includes('admin-client')?'export const useAdminLocale=()=>({locale:"zh-TW",m:(key)=>key});':'export const useOperationsAuthority=()=>({scope:{},capture:()=>()=>window.live,deny:()=>window.denials++});'));b.onResolve({filter:/^@\//},a=>({path:path.resolve('src',a.path.slice(2)+'.ts')}));if(process.env.AWESOME_QA_STRICTMODE_PREIMAGE==='1')b.onLoad({filter:/admin-merchant-application-actions\.tsx$/},()=>({contents:readFileSync('.superpowers/sdd/2026-10-01-awesome-optimization/batch-2/repair-1/before/src__components__admin-merchant-application-actions.tsx.before','utf8'),loader:'tsx',resolveDir:path.resolve('src/components')}));}}]});javascript=result.outputFiles[0].text;browser=await chromium.launch();
},30000);
afterAll(async()=>{await browser?.close();},30000);
async function mounted(){const page=await browser.newPage();await page.setContent('<div id="root"></div>');await page.addScriptTag({content:javascript});await page.getByPlaceholder('Internal review note, hidden from the applicant').fill('Synthetic note');await page.getByRole('button',{name:'Save internal note',exact:true}).click();await page.waitForFunction(()=>typeof (window as unknown as TestWindow).finish==='function');return page;}
it('StrictMode replay still accepts one action response and clears busy',async()=>{const page=await mounted();await page.evaluate(()=> (window as unknown as TestWindow).finish());await page.getByText('Internal note saved.',{exact:true}).waitFor();expect(await page.getByRole('button',{name:'Save internal note',exact:true}).isDisabled()).toBe(true);expect(await page.getByPlaceholder('Internal review note, hidden from the applicant').inputValue()).toBe('');expect(await page.evaluate(()=>({patches:(window as unknown as TestWindow).patches,refreshes:(window as unknown as TestWindow).refreshes}))).toEqual({patches:1,refreshes:1});await page.getByPlaceholder('Internal review note, hidden from the applicant').fill('Another note');expect(await page.getByRole('button',{name:'Save internal note',exact:true}).isEnabled()).toBe(true);await page.close();},30000);
it.each(['unmount','authority-loss'])('late %s action result stays ignored',async mode=>{const page=await mounted();await page.evaluate(mode=>{if(mode==='unmount')(window as unknown as TestWindow).testRoot.unmount();else(window as unknown as TestWindow).live=false;(window as unknown as TestWindow).finish();},mode);await page.waitForTimeout(100);expect(await page.evaluate(()=>(window as unknown as TestWindow).refreshes)).toBe(0);expect(await page.getByText('Internal note saved.',{exact:true}).count()).toBe(0);await page.close();},30000);
