import {afterEach,describe,expect,it} from 'vitest';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,unlinkSync,utimesSync,symlinkSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {assertRootAudit,auditPackageSet,inspectImports,parseClientReferenceManifest,prepareWebAudit,verifyWebArtifact,verifyRscOwnerMapping,verifyKnownNativeExclusion,verifyGeneratedPrisma} from './web-release-dependency-audit.mjs';
const temporary=[];
afterEach(()=>{for(const root of temporary.splice(0))rmSync(root,{recursive:true,force:true});});
const audit={metadata:{vulnerabilities:{total:0}},vulnerabilities:{}};
const sbom={bomFormat:'CycloneDX',components:[{name:'safe',version:'1.0.0'}]};
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'stallorder-web-audit-'));temporary.push(root);
 const write=(path,value)=>{mkdirSync(join(root,path,'..'),{recursive:true});writeFileSync(join(root,path),value);};
 write('package.json',JSON.stringify({dependencies:{safe:'1.0.0'}}));write('package-lock.json',JSON.stringify({packages:{'node_modules/safe':{version:'1.0.0'}}}));
 write('packages/contracts/package.json',JSON.stringify({name:'@stallorder/contracts',dependencies:{}}));write('src/page.ts',"import 'safe';");
 execFileSync('git',['init','--quiet'],{cwd:root});execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['-c','user.name=Synthetic QA','-c','user.email=qa@example.invalid','commit','--quiet','-m','synthetic fixture'],{cwd:root});
 const baseline=prepareWebAudit(root);
 write('node_modules/safe/package.json',JSON.stringify({name:'safe',version:'1.0.0'}));write('node_modules/safe/index.js','module.exports=1;');
 write('.next/BUILD_ID','synthetic-build');utimesSync(join(root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(baseline.preparedAt)+1000));
 write('.next/server/page.js',"require('safe');");write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../node_modules/safe/index.js']}));
 write('.next/server/app/page_client-reference-manifest.js','globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {}; globalThis.__RSC_MANIFEST["/page"] = {"clientModules":{}};');
 write('.next/server/server-reference-manifest.json',JSON.stringify({node:{},edge:{}}));
 return {root,write,baseline,verify:()=>verifyWebArtifact(root,baseline,audit,sbom)};
}
describe('Web artifact dependency scope',()=>{
 it('parses manifests as literal data without executing code',()=>{expect(parseClientReferenceManifest('globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {}; globalThis.__RSC_MANIFEST["/page"] = {"chunks":[]};')).toEqual({chunks:[]});expect(()=>parseClientReferenceManifest('globalThis.__RSC_MANIFEST = {}; globalThis.__RSC_MANIFEST["/page"] = fetch("https://evil.test");')).toThrow('NOT_LITERAL');});
 it('rejects absent client chunks referenced by manifests',()=>{const f=fixture();f.write('.next/server/app/page_client-reference-manifest.js','globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {}; globalThis.__RSC_MANIFEST["/page"] = {"chunks":["/_next/static/absent.js"]};');expect(f.verify).toThrow('MANIFEST_REFERENCE_INVALID');});
 it('keeps unreviewed server action maps failclosed',()=>{const f=fixture();f.write('.next/server/server-reference-manifest.json',JSON.stringify({node:{action:{workers:{unknown:1}}},edge:{}}));expect(f.verify).toThrow('SERVER_ACTION_CLOSURE_UNREVIEWED');});
 it('requires valid zero-vulnerability root audit, not a successful network request alone',()=>{assertRootAudit(audit);expect(()=>assertRootAudit({error:{code:'network'}})).toThrow('INVALID');expect(()=>assertRootAudit({metadata:{vulnerabilities:{total:1}},vulnerabilities:{vulnerable:{}}})).toThrow('VULNERABILITIES');});
 it('rejects native SBOM entries and packages absent from locked closure',()=>{expect(()=>auditPackageSet({...sbom,components:[{name:'expo',version:'57'}]},{packages:{}})).toThrow('NATIVE');expect(()=>auditPackageSet(sbom,{packages:{}})).toThrow('LOCK_MISMATCH');});
 it('identifies unknown dynamic loaders and literal native imports with the AST',()=>{expect(inspectImports("import(name);require(target);import 'expo';",'test.js')).toMatchObject({imports:['expo'],unknown:[{kind:'import'},{kind:'require'}]});});
 it('binds a synthetic fresh artifact to source, HEAD, lock and every trace',()=>{const f=fixture();expect(f.verify()).toMatchObject({status:'PASS',traces:1,tracedFiles:1,buildId:'synthetic-build',head:f.baseline.head,lockSha256:f.baseline.lockSha256});expect(f.verify().artifactSha256).toMatch(/^[a-f0-9]{64}$/);});
 it('does not claim Deno-only Edge helpers are part of Web publication',()=>{const f=fixture();f.write('supabase/functions/_shared/supabase.ts',"import 'npm:@supabase/supabase-js@2.110.2';");f.baseline=prepareWebAudit(f.root);f.baseline.oldBuildId=null;utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(f.baseline.preparedAt)+1000));expect(verifyWebArtifact(f.root,f.baseline,audit,sbom)).toMatchObject({status:'PASS',sourceScope:{edgeFunctions:'NOT_VERIFIED_DENO_QA_REQUIRED'}});});
 it('a Web import reaching shared Edge code is still checked against Web audited packages',()=>{const f=fixture();f.write('src/page.ts',"import '../supabase/functions/_shared/reachable';");f.write('supabase/functions/_shared/reachable.ts',"import './nested';");f.write('supabase/functions/_shared/nested.ts',"import 'npm:zod@4.2.1';");f.baseline=prepareWebAudit(f.root);f.baseline.oldBuildId=null;utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(f.baseline.preparedAt)+1000));expect(verifyWebArtifact(f.root,f.baseline,audit,sbom)).toMatchObject({status:'INCOMPLETE',problems:expect.arrayContaining([{path:expect.stringContaining('nested.ts'),code:'SOURCE_PACKAGE_OUTSIDE_AUDITED_CLOSURE'}])});});
 it('rejects product-source drift after prepare',()=>{const f=fixture();f.write('src/page.ts','export const changed=true;');expect(f.verify).toThrow('WEB_SOURCE_CHANGED');});
 it('rejects changes to the verifier after prepare',()=>{const f=fixture();f.write('scripts/verify-web-install-scope.mjs','export const compromised=true;');expect(f.verify).toThrow('WEB_SOURCE_CHANGED');});
 it('binds runner and workflow files against mutation after prepare',()=>{for(const file of ['scripts/verify-web-release-scope.mjs','.github/workflows/production-readiness.yml']){const f=fixture();f.write(file,'synthetic gate original');const baseline=prepareWebAudit(f.root);baseline.oldBuildId=null;utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(baseline.preparedAt)+1000));f.write(file,'mutated gate');expect(()=>verifyWebArtifact(f.root,baseline,audit,sbom)).toThrow('WEB_SOURCE_CHANGED');}});
 it('rejects reused builds even if the file timestamp is fresh',()=>{const f=fixture();f.baseline.oldBuildId='synthetic-build';expect(f.verify).toThrow('FRESH_BUILD');});
 it('rejects absent trace evidence',()=>{const f=fixture();unlinkSync(join(f.root,'.next/server/page.js.nft.json'));expect(f.verify).toThrow('ARTIFACT_EMPTY');});
 it('rejects missing traced files',()=>{const f=fixture();unlinkSync(join(f.root,'node_modules/safe/index.js'));expect(f.verify).toThrow('TRACE_FILE_MISSING');});
 it('rejects trace escape outside the checkout',()=>{const f=fixture();const outside=join(f.root,'..','escape-web-audit.txt');writeFileSync(outside,'synthetic');try{f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../../escape-web-audit.txt']}));expect(f.verify).toThrow('ESCAPES_ROOT');}finally{unlinkSync(outside);}});
 it('rejects a compiled dependency outside the audited root graph',()=>{const f=fixture();f.write('node_modules/safe/package.json',JSON.stringify({name:'node-forge',version:'1.4.0'}));expect(f.verify()).toMatchObject({status:'INCOMPLETE',problems:[{code:'TRACE_PACKAGE_OUTSIDE_AUDITED_CLOSURE'}]});});
 it('attributes vendored metadata to its actual locked package boundary',()=>{const f=fixture();f.write('node_modules/safe/compiled/vendor/package.json',JSON.stringify({name:'vendored-internal',version:'1'}));f.write('node_modules/safe/compiled/vendor/index.js','synthetic');f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../node_modules/safe/compiled/vendor/index.js']}));expect(f.verify()).toMatchObject({status:'PASS'});});
 it('never approves unknown compiled loading even in a framework-named runtime',()=>{const f=fixture();f.write('.next/server/[turbopack]_runtime.js','require(resolved);');expect(f.verify()).toMatchObject({status:'INCOMPLETE',problems:[{code:'UNKNOWN_COMPILED_IMPORT'}]});});
 it('rejects bundled literal native imports',()=>{const f=fixture();f.write('.next/server/page.js',"require('expo-router');");expect(f.verify()).toMatchObject({status:'INCOMPLETE',problems:[{code:'NATIVE_COMPILED_IMPORT'}]});});
 it('requires shared contracts dependencies to be explicitly audited',()=>{const f=fixture();f.write('packages/contracts/package.json',JSON.stringify({name:'@stallorder/contracts',dependencies:{'node-forge':'1.4.0'}}));f.baseline=prepareWebAudit(f.root);utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(f.baseline.preparedAt)+1000));f.baseline.oldBuildId=null;expect(()=>verifyWebArtifact(f.root,f.baseline,audit,sbom)).toThrow('CONTRACTS_DEPENDENCY');});
});

describe('RSC route owner closure',()=>{
 function rsc(){const f=fixture();f.write('.next/server/app/page.js','module.exports={};');f.write('.next/server/chunks/owned.js','module.exports=[7,8,e=>{}];');f.write('.next/server/app/page.js.nft.json',JSON.stringify({files:['../chunks/owned.js']}));const manifest={ssrModuleMapping:{client:{'*':{id:8,chunks:['server/chunks/owned.js']}}}};return{...f,manifest,path:join(f.root,'.next/server/app/page_client-reference-manifest.js')};}
 it('binds a server module ID to a factory in the owning route trace',()=>{const f=rsc();expect(verifyRscOwnerMapping(f.root,f.path,f.manifest)).toEqual({modules:1});});
 it('rejects a real chunk outside the specific route trace',()=>{const f=rsc();f.write('.next/server/app/page.js.nft.json',JSON.stringify({files:[]}));expect(()=>verifyRscOwnerMapping(f.root,f.path,f.manifest)).toThrow('OWNER_CHUNK_UNTRACED');});
 it('rejects an undefined module ID even when its chunk is traced',()=>{const f=rsc();f.manifest.ssrModuleMapping.client['*'].id=9;expect(()=>verifyRscOwnerMapping(f.root,f.path,f.manifest)).toThrow('MODULE_UNDEFINED');});
 it('rejects escaping and nonliteral chunk data',()=>{const f=rsc();f.manifest.ssrModuleMapping.client['*'].chunks=['server/../../outside.js'];expect(()=>verifyRscOwnerMapping(f.root,f.path,f.manifest)).toThrow('OWNER_CHUNK_UNTRACED');f.manifest.ssrModuleMapping.client['*'].chunks=[{}];expect(()=>verifyRscOwnerMapping(f.root,f.path,f.manifest)).toThrow('CHUNK_INVALID');});
});
describe('resident RSC module closure',()=>{
 it('requires the empty-chunks module to exist in literal owner bootstrap chunks',()=>{const f=fixture();f.write('.next/server/chunks/[turbopack]_runtime.js','module.exports=()=>({});');f.write('.next/server/app/page.js','var R=require("../chunks/[turbopack]_runtime.js")("server/app/page.js"); R.c("server/chunks/owned.js");');f.write('.next/server/chunks/owned.js','module.exports=[8,e=>{}];');f.write('.next/server/app/page.js.nft.json',JSON.stringify({files:['../chunks/owned.js','../chunks/[turbopack]_runtime.js']}));const m={rscModuleMapping:{client:{'*':{id:8,chunks:[]}}}};const p=join(f.root,'.next/server/app/page_client-reference-manifest.js');expect(verifyRscOwnerMapping(f.root,p,m)).toEqual({modules:1});f.write('.next/server/app/page.js','var R=require("../chunks/[turbopack]_runtime.js")("server/app/page.js"); R.c(userInput);');expect(()=>verifyRscOwnerMapping(f.root,p,m)).toThrow('OWNER_NONLITERAL_CHUNK');});
});
describe('RSC registration is executable top-level only',()=>{
 for(const source of ['if(false){module.exports=[8,e=>{}];}','function hidden(){module.exports=[8,e=>{}];}'])it('rejects unreachable or nested registration: '+source,()=>{const f=fixture();f.write('.next/server/app/page.js','module.exports={};');f.write('.next/server/chunks/owned.js',source);f.write('.next/server/app/page.js.nft.json',JSON.stringify({files:['../chunks/owned.js']}));expect(()=>verifyRscOwnerMapping(f.root,join(f.root,'.next/server/app/page_client-reference-manifest.js'),{ssrModuleMapping:{client:{'*':{id:8,chunks:['server/chunks/owned.js']}}}})).toThrow('MODULE_UNDEFINED');});
 it('rejects unbound owner bootstrap R',()=>{const f=fixture();f.write('.next/server/app/page.js','R.c("server/chunks/owned.js");');f.write('.next/server/app/page.js.nft.json',JSON.stringify({files:[]}));expect(()=>verifyRscOwnerMapping(f.root,join(f.root,'.next/server/app/page_client-reference-manifest.js'),{rscModuleMapping:{client:{'*':{id:8,chunks:[]}}}})).toThrow('RUNTIME_BINDING');});
});
describe('physical known Native exclusion scope stays distinct from generic loader analysis',()=>{
 function selected(){const f=fixture();f.write('package.json',JSON.stringify({name:'synthetic-web',version:'1.0.0',dependencies:{safe:'1.0.0','@stallorder/contracts':'0.1.0'}}));f.write('packages/contracts/package.json',JSON.stringify({name:'@stallorder/contracts',version:'0.1.0',dependencies:{safe:'1.0.0'}}));f.write('package-lock.json',JSON.stringify({packages:{'':{name:'synthetic-web',version:'1.0.0'},'packages/contracts':{name:'@stallorder/contracts',version:'0.1.0'},'node_modules/@stallorder/contracts':{link:true,resolved:'packages/contracts'},'node_modules/safe':{version:'1.0.0'}}}));mkdirSync(join(f.root,'node_modules/@stallorder'),{recursive:true});symlinkSync(join(f.root,'packages/contracts'),join(f.root,'node_modules/@stallorder/contracts'),'junction');f.baseline=prepareWebAudit(f.root);f.baseline.oldBuildId=null;utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(f.baseline.preparedAt)+1000));const selectedSbom={bomFormat:'CycloneDX',metadata:{component:{name:'synthetic-web',version:'1.0.0','bom-ref':'synthetic-web@1.0.0'}},components:[{name:'safe',version:'1.0.0','bom-ref':'safe'},{group:'@stallorder',name:'contracts',version:'0.1.0','bom-ref':'contract'}],dependencies:[{ref:'synthetic-web@1.0.0',dependsOn:['safe','contract']},{ref:'contract',dependsOn:['safe']},{ref:'safe',dependsOn:[]}]};return{...f,selectedSbom,verify:()=>verifyKnownNativeExclusion(f.root,f.baseline,audit,selectedSbom)};}
 it('normalizes grouped workspace names against lock identities',()=>{expect(auditPackageSet({bomFormat:'CycloneDX',components:[{group:'@stallorder',name:'contracts',version:'0.1.0'}]},{packages:{'packages/contracts':{name:'@stallorder/contracts',version:'0.1.0'}}})).toContain('@stallorder/contracts@0.1.0');});
 it('exclusion proof passes physical scope while generic dynamic loading remains explicitly incomplete',()=>{const f=selected();f.write('.next/server/[turbopack]_runtime.js','require(resolved);');expect(f.verify()).toMatchObject({status:'PASS',scope:'WEB_KNOWN_NATIVE_DEPENDENCY_EXCLUSION',installation:{installedPackages:2,sbom:'PASS'},generalArtifactAnalysis:{status:'INCOMPLETE',unreviewedGenericLoaders:[{code:'UNKNOWN_COMPILED_IMPORT'}]},runtimeLoaderSafety:'NOT_PROVEN'});expect(verifyWebArtifact(f.root,f.baseline,audit,f.selectedSbom).status).toBe('INCOMPLETE');});
 it('hashes all files in the exact audited contracts NFT directory instead of skipping it',()=>{const f=selected();f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../node_modules/@stallorder/contracts']}));const result=f.verify();expect(result.status).toBe('PASS');expect(result.tracedFiles).toBe(1);const before=result.artifactSha256;f.write('packages/contracts/fixture.txt','new traced content');const baseline=prepareWebAudit(f.root);baseline.oldBuildId=null;utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(baseline.preparedAt)+1000));expect(verifyKnownNativeExclusion(f.root,baseline,audit,f.selectedSbom).artifactSha256).not.toBe(before);});
 it('expands an audited Web package root directory including all its files',()=>{const f=selected();f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../node_modules/safe']}));expect(f.verify()).toMatchObject({status:'PASS',tracedFiles:2});});
 it('rejects arbitrary NFT directories despite root containment',()=>{const f=selected();f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../src']}));expect(f.verify).toThrow('DIRECTORY_SCOPE_UNPROVEN');});
 it('rejects NFT directory symlink escape and cycles instead of skipping files',()=>{const f=selected();f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../node_modules/safe']}));symlinkSync(join(f.root,'node_modules/safe'),join(f.root,'node_modules/safe/loop'),'junction');expect(()=>verifyWebArtifact(f.root,f.baseline,audit,f.selectedSbom)).toThrow('DIRECTORY_CYCLE');unlinkSync(join(f.root,'node_modules/safe/loop'));const outside=mkdtempSync(join(tmpdir(),'trace-outside-'));temporary.push(outside);symlinkSync(outside,join(f.root,'node_modules/safe/escape'),'junction');expect(()=>verifyWebArtifact(f.root,f.baseline,audit,f.selectedSbom)).toThrow('TRACE_ESCAPES_ROOT');});
 it('expanded workspace contents retain package SBOM checks',()=>{const f=selected();f.write('packages/contracts/node_modules/unknown/package.json',JSON.stringify({name:'unknown',version:'1'}));expect(f.verify).toThrow('PACKAGE_NOT_LOCKED');});
 it('installed Native packages cannot be hidden by a clean selected SBOM',()=>{const f=selected();f.write('node_modules/expo/package.json',JSON.stringify({name:'expo',version:'57'}));expect(f.verify).toThrow('WEB_INSTALL_NATIVE_PACKAGE');});
 it('unknown source loading cannot become a generic compiled-loader exemption',()=>{const f=selected();f.write('src/page.ts','require(userInput);');const baseline=prepareWebAudit(f.root);baseline.oldBuildId=null;utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(baseline.preparedAt)+1000));expect(verifyKnownNativeExclusion(f.root,baseline,audit,f.selectedSbom)).toMatchObject({status:'INCOMPLETE',problems:[{code:'UNKNOWN_SOURCE_IMPORT'}]});});
 it('compiled Native imports and parse errors remain blocking',()=>{const f=selected();for(const [source,code] of [["require('expo');",'NATIVE_COMPILED_IMPORT'],['function {','COMPILED_PARSE_FAILED']]){f.write('.next/server/page.js',source);expect(f.verify()).toMatchObject({status:'INCOMPLETE',problems:expect.arrayContaining([{path:expect.any(String),code}])});}});
 it('retains fresh source, trace containment, installed coverage and manifest gates',()=>{const f=selected();f.selectedSbom.components.pop();expect(f.verify).toThrow('SBOM_PACKAGE_MISSING');f.selectedSbom.components.push({group:'@stallorder',name:'contracts',version:'0.1.0','bom-ref':'contract'});f.write('.next/server/app/page_client-reference-manifest.js','executeUntrusted();');expect(f.verify).toThrow('MANIFEST_NOT_LITERAL');});
});

describe('generated Prisma schema and producer identity provenance',()=>{
 function generated(){const root=mkdtempSync(join(tmpdir(),'prisma-proof-'));temporary.push(root);const write=(path,value)=>{mkdirSync(join(root,path,'..'),{recursive:true});writeFileSync(join(root,path),value);};const schema='model Example {\n  id Int @id\n}\n',version='6.19.3';const pkg={name:'prisma-client-'+createHash('sha256').update(schema).digest('hex'),version};write('prisma/schema.prisma',schema);write('node_modules/.prisma/client/schema.prisma',schema);write('node_modules/.prisma/client/package.json',JSON.stringify(pkg));write('node_modules/.prisma/client/index.js','const config='+JSON.stringify({inlineSchema:schema,clientVersion:version})+';');write('node_modules/prisma/package.json',JSON.stringify({name:'prisma',version,bin:{prisma:'build/index.js'}}));write('node_modules/@prisma/client/package.json',JSON.stringify({name:'@prisma/client',version}));write('node_modules/@prisma/client/generator-build/index.js','synthetic generator fixture, not real producer proof');write('node_modules/prisma/build/prisma_schema_build_bg.wasm','synthetic wasm fixture');write('node_modules/prisma/build/index.js',"const fs=require('node:fs');if(process.argv[2]!=='format'||process.argv[3]!=='--schema'||process.env.DATABASE_URL||process.env.NODE_OPTIONS)process.exit(2);const path=process.argv[4];fs.writeFileSync(path,fs.readFileSync(path,'utf8').trim()+'\\n');");write('package-lock.json',JSON.stringify({packages:{'node_modules/prisma':{version},'node_modules/@prisma/client':{version}}}));return{root,write,pkg,schema,packages:new Set(['prisma@'+version,'@prisma/client@'+version]),verify:()=>verifyGeneratedPrisma(root,new Set(['prisma@'+version,'@prisma/client@'+version]))};}
 it('binds exact schema bytes, formatter output, generated name, config and locked producer versions',()=>{const f=generated();expect(f.verify()).toMatchObject({version:'6.19.3',schemaSha256:f.pkg.name.slice('prisma-client-'.length),formatterWasmSha256:expect.stringMatching(/^[a-f0-9]{64}$/)});});
 it('does not pass credential or Node loader env into formatting subprocess',()=>{const f=generated(),prior=process.env.DATABASE_URL;process.env.DATABASE_URL='synthetic-do-not-pass';try{expect(f.verify().version).toBe('6.19.3');}finally{if(prior===undefined)delete process.env.DATABASE_URL;else process.env.DATABASE_URL=prior;}});
 it('rejects generated name hash or version drift',()=>{const f=generated();for(const patch of [{name:'prisma-client-forged'},{version:'9.0.0'}]){f.write('node_modules/.prisma/client/package.json',JSON.stringify({...f.pkg,...patch}));expect(f.verify).toThrow('GENERATED_IDENTITY_INVALID');}});
 it('schema/name agreement alone cannot hide a stale source schema',()=>{const f=generated();f.write('prisma/schema.prisma',f.schema.replace('Int','String'));expect(f.verify).toThrow('SOURCE_SCHEMA_MISMATCH');});
 it('rejects nested Native packages even under a valid generated owner',()=>{for(const name of ['node-forge','expo','renamed-native']){const f=generated();f.write('node_modules/.prisma/client/node_modules/'+name+'/package.json',JSON.stringify({name,version:'1'}));expect(f.verify).toThrow('NESTED_PACKAGE_FORBIDDEN');}const f=generated();f.write('node_modules/.prisma/client/vendor/package.json',JSON.stringify({name:'renamed-native',version:'1'}));expect(f.verify).toThrow('NESTED_PACKAGE_FORBIDDEN');});
 it('rejects Native or unknown generated JS imports and config override ambiguities',()=>{const f=generated(),base='const config='+JSON.stringify({inlineSchema:f.schema,clientVersion:'6.19.3'})+';';for(const source of [base+"require('expo');",base+'require(target);']){f.write('node_modules/.prisma/client/index.js',source);expect(f.verify).toThrow(/NATIVE_GENERATED_IMPORT|GENERATED_IMPORT_UNPROVEN/);}for(const source of ['const config={inlineSchema:'+JSON.stringify(f.schema)+',inlineSchema:external(),clientVersion:"6.19.3"};','const config={inlineSchema:'+JSON.stringify(f.schema)+',clientVersion:"6.19.3",...override};']){f.write('node_modules/.prisma/client/index.js',source);expect(f.verify).toThrow('CONFIG_INVALID');}});
 it('rejects config schema or clientVersion drift and nonliteral config',()=>{const f=generated();for(const source of ['const config='+JSON.stringify({inlineSchema:'different',clientVersion:'6.19.3'})+';','const config='+JSON.stringify({inlineSchema:f.schema,clientVersion:'9.0.0'})+';','const config=loadFromExternal();']){f.write('node_modules/.prisma/client/index.js',source);expect(f.verify).toThrow('CONFIG_INVALID');}});
 it('rejects unaudited or mismatched generator and failed formatter',()=>{const f=generated();expect(()=>verifyGeneratedPrisma(f.root,new Set(['prisma@6.19.3']))).toThrow('GENERATOR_UNAUDITED');f.write('node_modules/prisma/build/index.js','process.exit(1);');expect(f.verify).toThrow('FORMATTER_FAILED');});
 it('binds generated directory NFT files to provenance and hashes all generated bytes',()=>{const f=generated();f.write('package.json',JSON.stringify({name:'synthetic-web',version:'1.0.0'}));f.write('packages/contracts/package.json',JSON.stringify({name:'@stallorder/contracts',dependencies:{}}));f.write('src/page.ts',"import '@prisma/client';");execFileSync('git',['init','--quiet'],{cwd:f.root});execFileSync('git',['add','.'],{cwd:f.root});execFileSync('git',['-c','user.name=Synthetic QA','-c','user.email=qa@example.invalid','commit','--quiet','-m','synthetic producer fixture'],{cwd:f.root});const baseline=prepareWebAudit(f.root);f.write('.next/BUILD_ID','generated-proof-build');utimesSync(join(f.root,'.next/BUILD_ID'),new Date(),new Date(Date.parse(baseline.preparedAt)+1000));f.write('.next/server/page.js',"require('@prisma/client');");f.write('.next/server/page.js.nft.json',JSON.stringify({version:1,files:['../../node_modules/.prisma/client']}));f.write('.next/server/app/page_client-reference-manifest.js','globalThis.__RSC_MANIFEST = globalThis.__RSC_MANIFEST || {}; globalThis.__RSC_MANIFEST["/page"] = {"clientModules":{}};');f.write('.next/server/server-reference-manifest.json',JSON.stringify({node:{},edge:{}}));const producerSbom={bomFormat:'CycloneDX',components:[{name:'prisma',version:'6.19.3'},{name:'@prisma/client',version:'6.19.3'}]};const first=verifyWebArtifact(f.root,baseline,audit,producerSbom);expect(first).toMatchObject({status:'PASS',tracedFiles:3,generatedPrisma:{schemaSha256:f.pkg.name.slice('prisma-client-'.length)}});f.write('node_modules/.prisma/client/new-file.txt','additional generated bytes');expect(verifyWebArtifact(f.root,baseline,audit,producerSbom).artifactSha256).not.toBe(first.artifactSha256);});
 it('rejects generated directory symlink outside the exact hidden output location',()=>{const f=generated(),outside=mkdtempSync(join(tmpdir(),'prisma-outside-'));temporary.push(outside);rmSync(join(f.root,'node_modules/.prisma/client'),{recursive:true});symlinkSync(outside,join(f.root,'node_modules/.prisma/client'),'junction');expect(f.verify).toThrow('GENERATED_PATH_INVALID');});
});
