import { InvoiceProviderError, type InvoiceLifecycleStatus } from "./e-invoice-provider";

const transitions: Readonly<Record<InvoiceLifecycleStatus, readonly InvoiceLifecycleStatus[]>> = {
  NOT_REQUIRED: [],
  PENDING: ["ISSUING", "NOT_REQUIRED", "MANUAL_REVIEW"],
  ISSUING: ["ISSUED", "ISSUE_FAILED", "RECONCILIATION_REQUIRED"],
  ISSUED: ["VOID_PENDING", "ALLOWANCE_PENDING", "RECONCILIATION_REQUIRED", "MANUAL_REVIEW"],
  ISSUE_FAILED: ["ISSUING", "MANUAL_REVIEW"],
  VOID_PENDING: ["VOIDED", "VOID_FAILED", "RECONCILIATION_REQUIRED"],
  VOIDED: ["RECONCILIATION_REQUIRED", "MANUAL_REVIEW"],
  VOID_FAILED: ["VOID_PENDING", "MANUAL_REVIEW"],
  ALLOWANCE_PENDING: ["PARTIALLY_ALLOWED", "FULLY_ALLOWED", "ALLOWANCE_FAILED", "RECONCILIATION_REQUIRED"],
  PARTIALLY_ALLOWED: ["ALLOWANCE_PENDING", "ALLOWANCE_VOID_PENDING", "VOID_PENDING", "RECONCILIATION_REQUIRED", "MANUAL_REVIEW"],
  FULLY_ALLOWED: ["ALLOWANCE_VOID_PENDING", "VOID_PENDING", "RECONCILIATION_REQUIRED", "MANUAL_REVIEW"],
  ALLOWANCE_FAILED: ["ALLOWANCE_PENDING", "MANUAL_REVIEW"],
  ALLOWANCE_VOID_PENDING: ["ALLOWANCE_VOIDED", "ALLOWANCE_VOID_FAILED", "RECONCILIATION_REQUIRED"],
  ALLOWANCE_VOIDED: ["ISSUED", "RECONCILIATION_REQUIRED", "MANUAL_REVIEW"],
  ALLOWANCE_VOID_FAILED: ["ALLOWANCE_VOID_PENDING", "MANUAL_REVIEW"],
  RECONCILIATION_REQUIRED: ["MANUAL_REVIEW", "ISSUED", "VOIDED", "PARTIALLY_ALLOWED", "FULLY_ALLOWED"],
  MANUAL_REVIEW: ["ISSUED", "VOIDED", "PARTIALLY_ALLOWED", "FULLY_ALLOWED", "RECONCILIATION_REQUIRED"],
};

export function canTransitionInvoice(from: InvoiceLifecycleStatus, to: InvoiceLifecycleStatus) {
  return from === to || transitions[from].includes(to);
}

export function assertInvoiceTransition(from: InvoiceLifecycleStatus, to: InvoiceLifecycleStatus) {
  if (!canTransitionInvoice(from, to)) {
    throw new InvoiceProviderError("INVOICE_STATE_TRANSITION_INVALID", 409);
  }
}

