import {test,expect,afterEach} from 'vitest';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';import{basename,join}from'node:path';
import{verifyWebInstallScope,supplementSharedWorkspaceSbom}from'./verify-web-install-scope.mjs';
const dirs=[];afterEach(()=>dirs.splice(0).forEach(path=>rmSync(path,{recursive:true,force:true})));
function fixture(){const root=mkdtempSync(join(tmpdir(),'web-install-'));dirs.push(root);const write=(p,v)=>{mkdirSync(join(root,p,'..'),{recursive:true});writeFileSync(join(root,p),JSON.stringify(v));};const lock={packages:{'':{name:'synthetic-web',version:'1.0.0'},'packages/contracts':{version:'0.1.0'},'node_modules/@stallorder/contracts':{link:true,resolved:'packages/contracts'},'node_modules/zod':{version:'4.4.3'},'node_modules/build-tool':{version:'1.0.0'}}};write('package.json',{name:'synthetic-web',version:'1.0.0',dependencies:{'@stallorder/contracts':'0.1.0',zod:'4.4.3'},devDependencies:{'build-tool':'1.0.0'}});write('packages/contracts/package.json',{name:'@stallorder/contracts',version:'0.1.0',dependencies:{zod:'4.4.3'}});write('node_modules/zod/package.json',{name:'zod',version:'4.4.3'});write('node_modules/build-tool/package.json',{name:'build-tool',version:'1.0.0'});mkdirSync(join(root,'node_modules/@stallorder'),{recursive:true});symlinkSync(join(root,'packages/contracts'),join(root,'node_modules/@stallorder/contracts'),'junction');write('package-lock.json',lock);return{root,write,lock};}
test('actual root development dependencies and contracts link remain audited',()=>{const f=fixture();expect(verifyWebInstallScope(f.root)).toMatchObject({status:'PASS',installedPackages:3,rootDevelopmentDependencies:1,contractsVersion:'0.1.0'});expect(verifyWebInstallScope(f.root).installedGraphSha256).toMatch(/^[a-f0-9]{64}$/);});
for(const name of ['expo','@expo/cli','node-forge','decode-uri-component','query-string','react-native'])test('rejects installed Native chain '+name,()=>{const f=fixture();f.write('node_modules/'+name+'/package.json',{name,version:'1.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('NATIVE_PACKAGE');});
test('rejects missing root build dependencies instead of silently omitting dev',()=>{const f=fixture();rmSync(join(f.root,'node_modules/build-tool'),{recursive:true});expect(()=>verifyWebInstallScope(f.root)).toThrow('REQUIRED_DEPENDENCY_MISSING');});
test('rejects installed package version drift',()=>{const f=fixture();f.write('node_modules/zod/package.json',{name:'zod',version:'0.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('VERSION_DRIFT');});
test('rejects native workspace junction even with safe package metadata',()=>{const f=fixture();f.write('apps/mobile/package.json',{name:'safe',version:'1.0.0'});symlinkSync(join(f.root,'apps/mobile'),join(f.root,'node_modules/safe'),'junction');expect(()=>verifyWebInstallScope(f.root)).toThrow('PATH_OUTSIDE_SCOPE');});
test('rejects leftover mobile install lock entries',()=>{const f=fixture();f.write('node_modules/.package-lock.json',{packages:{'node_modules/@stallorder/mobile':{link:true}}});expect(()=>verifyWebInstallScope(f.root)).toThrow('MOBILE_LOCK_ENTRY');});
test('rejects untracked installed packages and contract identity drift',()=>{const f=fixture();f.write('node_modules/unknown/package.json',{name:'unknown',version:'1.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('PACKAGE_NOT_LOCKED');rmSync(join(f.root,'node_modules/unknown'),{recursive:true});f.write('packages/contracts/package.json',{name:'@stallorder/contracts',version:'9.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('VERSION_DRIFT');});

test('rejects excluded workspace node_modules left by a prior full install',()=>{const f=fixture();f.write('apps/mobile/node_modules/private-native/package.json',{name:'expo',version:'57.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('MOBILE_WORKSPACE_REMAINS');});
test('rejects an owner nested dependency shadow that resolves outside the audited checkout',()=>{const f=fixture();const outside=mkdtempSync(join(tmpdir(),'web-shadow-'));dirs.push(outside);writeFileSync(join(outside,'package.json'),JSON.stringify({name:'zod',version:'4.4.3'}));mkdirSync(join(f.root,'packages/contracts/node_modules'),{recursive:true});symlinkSync(outside,join(f.root,'packages/contracts/node_modules/zod'),'junction');expect(()=>verifyWebInstallScope(f.root)).toThrow('PATH_OUTSIDE_SCOPE');});
test('audits a types-only declared package without requiring a runtime main entry',()=>{const f=fixture();f.write('package.json',{name:'synthetic-web',version:'1.0.0',dependencies:{'@stallorder/contracts':'0.1.0',zod:'4.4.3'},devDependencies:{'build-tool':'1.0.0','@types/synthetic':'1.0.0'}});f.write('node_modules/@types/synthetic/package.json',{name:'@types/synthetic',version:'1.0.0',types:'index.d.ts'});f.lock.packages['node_modules/@types/synthetic']={version:'1.0.0'};f.write('package-lock.json',f.lock);expect(verifyWebInstallScope(f.root)).toMatchObject({status:'PASS',rootDevelopmentDependencies:2});});
function fixtureSbom(){return{bomFormat:'CycloneDX',metadata:{component:{name:'synthetic-web',version:'1.0.0','bom-ref':'synthetic-web@1.0.0'}},components:[{group:'@stallorder',name:'contracts',version:'0.1.0','bom-ref':'contract'},{name:'zod',version:'4.4.3','bom-ref':'zod'},{name:'build-tool',version:'1.0.0','bom-ref':'build'}],dependencies:[{ref:'synthetic-web@1.0.0',dependsOn:['contract','zod','build']},{ref:'contract',dependsOn:['zod']},{ref:'zod',dependsOn:[]},{ref:'build',dependsOn:[]}]};}
function rawSbom(){const sbom=fixtureSbom();sbom.components.shift();sbom.dependencies=sbom.dependencies.filter(e=>e.ref!=='contract');sbom.dependencies[0].dependsOn=sbom.dependencies[0].dependsOn.filter(ref=>ref!=='contract');return sbom;}
test('SBOM independently covers actual installed prod/dev/contracts graph',()=>{const f=fixture();expect(verifyWebInstallScope(f.root,fixtureSbom())).toMatchObject({status:'PASS',sbom:'PASS',installedGraph:expect.arrayContaining([{path:'node_modules/@stallorder/contracts',name:'@stallorder/contracts',version:'0.1.0',target:'packages/contracts'}])});});
test('SBOM fails when build dependency, contracts or version is missing',()=>{const f=fixture();for(const name of ['build-tool','contracts','zod']){const sbom=fixtureSbom();sbom.components=sbom.components.filter(c=>c.name!==name);expect(()=>verifyWebInstallScope(f.root,sbom)).toThrow('SBOM_PACKAGE_MISSING');}const sbom=fixtureSbom();sbom.components[1].version='0.0.0';expect(()=>verifyWebInstallScope(f.root,sbom)).toThrow('SBOM_PACKAGE_MISSING');});
test('SBOM cannot reintroduce native dependencies absent from installed graph',()=>{const f=fixture();const sbom=fixtureSbom();sbom.components.push({group:'@expo',name:'cli',version:'57.0.0'});expect(()=>verifyWebInstallScope(f.root,sbom)).toThrow('SBOM_NATIVE_PACKAGE');});
test('SBOM must be a real supported document',()=>{const f=fixture();expect(()=>verifyWebInstallScope(f.root,{error:'failed CLI'})).toThrow('SBOM_INVALID');});
test('supplements only verified workspace and preserves npm raw bytes and root/build edges',()=>{const f=fixture(),raw=rawSbom(),before=JSON.stringify(raw);const result=supplementSharedWorkspaceSbom(f.root,raw);expect(JSON.stringify(raw)).toBe(before);expect(result.receipt).toMatchObject({status:'PASS',sbom:'PASS',workspaceEdges:2});const ref='pkg:npm/%40stallorder/contracts@0.1.0';expect(result.sbom.dependencies).toContainEqual({ref,dependsOn:['zod']});expect(result.sbom.dependencies[0].dependsOn).toEqual(['zod','build',ref]);expect(result.sbom.components.find(c=>c.name==='contracts')).toMatchObject({purl:ref,'bom-ref':ref});});
test('supplement refuses unrelated missing package, Native document and preexisting workspace',()=>{const f=fixture();const missing=rawSbom();missing.components.pop();expect(()=>supplementSharedWorkspaceSbom(f.root,missing)).toThrow('SBOM_PACKAGE_MISSING');const native=rawSbom();native.components.push({name:'expo',version:'57','bom-ref':'native'});expect(()=>supplementSharedWorkspaceSbom(f.root,native)).toThrow('SBOM_NATIVE_PACKAGE');expect(()=>supplementSharedWorkspaceSbom(f.root,fixtureSbom())).toThrow('CONTRACT_ALREADY_PRESENT');});
test('coverage alone cannot replace root or workspace dependency edges',()=>{const f=fixture();for(const ref of ['synthetic-web@1.0.0','contract']){const sbom=fixtureSbom();sbom.dependencies.find(e=>e.ref===ref).dependsOn=[];expect(()=>verifyWebInstallScope(f.root,sbom)).toThrow('DECLARED_EDGE_MISSING');}const raw=rawSbom();raw.dependencies[0].dependsOn=[];expect(()=>supplementSharedWorkspaceSbom(f.root,raw)).toThrow('DECLARED_EDGE_MISSING');});
test('rejects ambiguous or dangling SBOM references',()=>{const f=fixture();const duplicate=fixtureSbom();duplicate.components[1]['bom-ref']='contract';expect(()=>verifyWebInstallScope(f.root,duplicate)).toThrow('REF_COLLISION');const dangling=fixtureSbom();dangling.dependencies[1].dependsOn=['unknown'];expect(()=>verifyWebInstallScope(f.root,dangling)).toThrow('EDGES_INVALID');const raw=rawSbom();delete raw.metadata;expect(()=>supplementSharedWorkspaceSbom(f.root,raw)).toThrow('ROOT_INVALID');});

test('npm root directory display name is accepted without changing raw identity',()=>{const f=fixture(),raw=rawSbom();raw.metadata.component.name=basename(f.root);const before=JSON.stringify(raw);const result=supplementSharedWorkspaceSbom(f.root,raw);expect(result.sbom.metadata.component.name).toBe(basename(f.root));expect(JSON.stringify(raw)).toBe(before);expect(verifyWebInstallScope(f.root,result.sbom).sbom).toBe('PASS');});
test('root display allowance cannot bypass lock, ref, version or purl identity',()=>{const f=fixture();for(const patch of [{'bom-ref':'other@1.0.0'},{version:'9.0.0'},{name:'unrelated-directory'},{purl:'pkg:npm/other@1.0.0'}]){const raw=rawSbom();Object.assign(raw.metadata.component,patch);expect(()=>supplementSharedWorkspaceSbom(f.root,raw)).toThrow('ROOT_INVALID');const sbom=fixtureSbom();Object.assign(sbom.metadata.component,patch);expect(()=>verifyWebInstallScope(f.root,sbom)).toThrow('ROOT_INVALID');}f.lock.packages[''].name='different-root';f.write('package-lock.json',f.lock);expect(()=>supplementSharedWorkspaceSbom(f.root,rawSbom())).toThrow('ROOT_INVALID');});
