import {afterEach,beforeEach,expect,test,vi} from 'vitest';
import {mkdtempSync,rmSync,readFileSync,existsSync,mkdirSync,symlinkSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const mocks=vi.hoisted(()=>({spawn:vi.fn(),scope:vi.fn(),supplement:vi.fn(),prepare:vi.fn(),artifact:vi.fn(),audit:vi.fn()}));
vi.mock('node:child_process',()=>({spawnSync:mocks.spawn}));
vi.mock('./verify-web-install-scope.mjs',()=>({verifyWebInstallScope:mocks.scope,supplementSharedWorkspaceSbom:mocks.supplement}));
vi.mock('./lib/web-release-dependency-audit.mjs',()=>({assertRootAudit:mocks.audit,prepareWebAudit:mocks.prepare,verifyKnownNativeExclusion:mocks.artifact}));
import {assertFreshWebRunner,runWebReleaseScope} from './verify-web-release-scope.mjs';
let root;const platform=Object.getOwnPropertyDescriptor(process,'platform');
beforeEach(()=>{
 root=mkdtempSync(join(tmpdir(),'web-release-runner-'));vi.clearAllMocks();
 Object.defineProperty(process,'platform',{value:'linux'});
 for(const [key,value]of Object.entries({CI:'true',GITHUB_ACTIONS:'true',RUNNER_ENVIRONMENT:'github-hosted',GITHUB_WORKSPACE:root}))vi.stubEnv(key,value);
 mocks.scope.mockReturnValue({status:'PASS'});mocks.supplement.mockReturnValue({sbom:{bomFormat:'CycloneDX',supplemented:true},receipt:{status:'PASS'}});
 mocks.prepare.mockReturnValue({head:'fixture-head'});mocks.artifact.mockReturnValue({status:'PASS',head:'fixture-head',tree:'fixture-tree',artifactSha256:'fixture-artifact',installation:{installedPackages:661,installedGraphSha256:'fixture-graph'},generalArtifactAnalysis:{status:'INCOMPLETE'}});
 mocks.spawn.mockImplementation((name,args)=>({status:0,stdout:args[0]==='--version'?'11.16.0\n':args[0]==='run'?'synthetic build log\n':args[0]==='sbom'?' {"bomFormat":"CycloneDX","raw":true}\n':'{"metadata":{"vulnerabilities":{"total":0}},"vulnerabilities":{}}\n',stderr:''}));
});
afterEach(()=>{Object.defineProperty(process,'platform',platform);vi.unstubAllEnvs();rmSync(root,{recursive:true,force:true});});
test('requires hosted Linux CI and exact workspace identity before commands or writes',()=>{for(const change of [{CI:'false'},{GITHUB_ACTIONS:'false'},{RUNNER_ENVIRONMENT:'self-hosted'},{GITHUB_WORKSPACE:tmpdir()}])expect(()=>assertFreshWebRunner(root,{...process.env,...change},'linux')).toThrow('FRESH_HOSTED_RUNNER');expect(()=>assertFreshWebRunner(root,process.env,'win32')).toThrow('FRESH_HOSTED_RUNNER');vi.stubEnv('CI','false');expect(()=>runWebReleaseScope(root,'evidence')).toThrow('FRESH_HOSTED_RUNNER');expect(mocks.spawn).not.toHaveBeenCalled();expect(existsSync(join(root,'evidence'))).toBe(false);});
test('uses fixed same selectors and fresh build sequence while preserving raw npm bytes',()=>{expect(runWebReleaseScope(root,'evidence')).toMatchObject({status:'PASS',deployment:'NOT_DEPLOYED',runtimeLoaderSafety:'NOT_PROVEN',installedPackages:661,selector:'npm ci --workspace packages/contracts --include-workspace-root --include=dev',verifierSha256:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(mocks.spawn.mock.calls.map(call=>call[1])).toEqual([['--version'],['audit','--json'],['audit','--workspace','packages/contracts','--include-workspace-root','--include=dev','--audit-level=moderate','--json'],['sbom','--workspaces=false','--package-lock-only','--sbom-format','cyclonedx'],['run','build']]);expect(readFileSync(join(root,'evidence/npm-root-sbom.json'),'utf8')).toBe(' {"bomFormat":"CycloneDX","raw":true}\n');expect(mocks.prepare.mock.invocationCallOrder[0]).toBeLessThan(mocks.artifact.mock.invocationCallOrder[0]);expect(mocks.spawn.mock.calls.every(call=>call[0]==='npm'&&call[2].shell===undefined)).toBe(true);});
test('full repository vulnerability diagnostics remain NON_PASS separately from Web scope proof',()=>{const original=mocks.spawn.getMockImplementation();mocks.spawn.mockImplementation((name,args,options)=>args.length===2&&args[0]==='audit'?{status:1,stdout:'{"metadata":{"vulnerabilities":{"total":7}},"vulnerabilities":{"expo":{}}}',stderr:''}:original(name,args,options));runWebReleaseScope(root,'evidence');expect(JSON.parse(readFileSync(join(root,'evidence/full-repository-diagnostic.json'),'utf8'))).toMatchObject({status:'NON_PASS',vulnerabilities:{total:7},nativeRelease:'NOT_AUTHORIZED_NOT_PUBLISHED'});});
test('does not overwrite prior evidence or write outside checkout',()=>{mkdirSync(join(root,'evidence'));expect(()=>runWebReleaseScope(root,'evidence')).toThrow('NEW_EVIDENCE_DIRECTORY');expect(()=>runWebReleaseScope(root,'../escape')).toThrow('NEW_EVIDENCE_DIRECTORY');expect(mocks.spawn).not.toHaveBeenCalled();});
test('raw SBOM CLI failure is not repaired or ignored',()=>{const original=mocks.spawn.getMockImplementation();mocks.spawn.mockImplementation((name,args,options)=>args[0]==='sbom'?{status:1,stdout:'{"error":"ESBOMPROBLEMS"}',stderr:'missing workspace'}:original(name,args,options));expect(()=>runWebReleaseScope(root,'evidence')).toThrow('RAW_SBOM_NON_PASS');expect(mocks.supplement).not.toHaveBeenCalled();expect(existsSync(join(root,'evidence/npm-root-sbom.json'))).toBe(true);expect(JSON.parse(readFileSync(join(root,'evidence/failure.json'),'utf8')).status).toBe('INCOMPLETE');});
test('physical install failure prevents build and selected audit',()=>{mocks.scope.mockImplementation(()=>{throw new Error('WEB_INSTALL_NATIVE_PACKAGE');});expect(()=>runWebReleaseScope(root,'evidence')).toThrow('NATIVE_PACKAGE');expect(mocks.spawn).toHaveBeenCalledTimes(1);expect(mocks.prepare).not.toHaveBeenCalled();});
test('blocks unknown selected npm version and build/artifact non-pass',()=>{mocks.spawn.mockReturnValueOnce({status:0,stdout:'11.99.0',stderr:''});expect(()=>runWebReleaseScope(root,'version')).toThrow('NPM_VERSION_UNREVIEWED');const original=mocks.spawn.getMockImplementation();mocks.spawn.mockImplementation((name,args,options)=>args[0]==='run'?{status:1,stdout:'build failed',stderr:''}:original(name,args,options));expect(()=>runWebReleaseScope(root,'build')).toThrow('BUILD_NON_PASS');expect(mocks.artifact).not.toHaveBeenCalled();mocks.spawn.mockImplementation(original);mocks.artifact.mockReturnValue({status:'INCOMPLETE'});expect(()=>runWebReleaseScope(root,'artifact')).toThrow('ARTIFACT_NON_PASS');});
test('fails on selected audit exit, malformed JSON or subprocess timeout',()=>{const original=mocks.spawn.getMockImplementation();mocks.spawn.mockImplementation((name,args,options)=>args.includes('--workspace')?{status:1,stdout:'{}',stderr:''}:original(name,args,options));expect(()=>runWebReleaseScope(root,'audit')).toThrow('SELECTED_AUDIT_NON_PASS');mocks.spawn.mockReturnValue({status:0,stdout:'invalid-json',stderr:''});expect(()=>runWebReleaseScope(root,'json')).toThrow('NPM_VERSION_UNREVIEWED');mocks.spawn.mockReturnValue({status:null,stdout:'',stderr:'',signal:'SIGTERM'});expect(()=>runWebReleaseScope(root,'timeout')).toThrow('COMMAND_INCOMPLETE');});

test('rejects an evidence parent symlink pointing outside the checkout',()=>{const outside=mkdtempSync(join(tmpdir(),'web-evidence-outside-'));try{symlinkSync(outside,join(root,'linked'),'junction');expect(()=>runWebReleaseScope(root,'linked/new')).toThrow('EVIDENCE_PATH_ESCAPES_ROOT');expect(mocks.spawn).not.toHaveBeenCalled();}finally{rmSync(outside,{recursive:true,force:true});}});

test('full diagnostic exit zero cannot hide reported vulnerabilities',()=>{const original=mocks.spawn.getMockImplementation();mocks.spawn.mockImplementation((name,args,options)=>args.length===2&&args[0]==='audit'?{status:0,stdout:'{"metadata":{"vulnerabilities":{"total":7}},"vulnerabilities":{"expo":{}}}',stderr:''}:original(name,args,options));runWebReleaseScope(root,'evidence');expect(JSON.parse(readFileSync(join(root,'evidence/full-repository-diagnostic.json'),'utf8')).status).toBe('NON_PASS');});
