import {test,expect,afterEach} from 'vitest';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';import{join}from'node:path';
import{verifyWebInstallScope}from'./verify-web-install-scope.mjs';
const dirs=[];afterEach(()=>dirs.splice(0).forEach(path=>rmSync(path,{recursive:true,force:true})));
function fixture(){const root=mkdtempSync(join(tmpdir(),'web-install-'));dirs.push(root);const write=(p,v)=>{mkdirSync(join(root,p,'..'),{recursive:true});writeFileSync(join(root,p),JSON.stringify(v));};const lock={packages:{'packages/contracts':{version:'0.1.0'},'node_modules/@stallorder/contracts':{link:true,resolved:'packages/contracts'},'node_modules/zod':{version:'4.4.3'},'node_modules/build-tool':{version:'1.0.0'}}};write('package.json',{dependencies:{'@stallorder/contracts':'0.1.0',zod:'4.4.3'},devDependencies:{'build-tool':'1.0.0'}});write('packages/contracts/package.json',{name:'@stallorder/contracts',version:'0.1.0',dependencies:{zod:'4.4.3'}});write('node_modules/zod/package.json',{name:'zod',version:'4.4.3'});write('node_modules/build-tool/package.json',{name:'build-tool',version:'1.0.0'});mkdirSync(join(root,'node_modules/@stallorder'),{recursive:true});symlinkSync(join(root,'packages/contracts'),join(root,'node_modules/@stallorder/contracts'),'junction');write('package-lock.json',lock);return{root,write,lock};}
test('actual root development dependencies and contracts link remain audited',()=>{const f=fixture();expect(verifyWebInstallScope(f.root)).toMatchObject({status:'PASS',installedPackages:3,rootDevelopmentDependencies:1,contractsVersion:'0.1.0'});expect(verifyWebInstallScope(f.root).installedGraphSha256).toMatch(/^[a-f0-9]{64}$/);});
for(const name of ['expo','@expo/cli','node-forge','decode-uri-component','query-string','react-native'])test('rejects installed Native chain '+name,()=>{const f=fixture();f.write('node_modules/'+name+'/package.json',{name,version:'1.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('NATIVE_PACKAGE');});
test('rejects missing root build dependencies instead of silently omitting dev',()=>{const f=fixture();rmSync(join(f.root,'node_modules/build-tool'),{recursive:true});expect(()=>verifyWebInstallScope(f.root)).toThrow('REQUIRED_DEPENDENCY_MISSING');});
test('rejects installed package version drift',()=>{const f=fixture();f.write('node_modules/zod/package.json',{name:'zod',version:'0.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('VERSION_DRIFT');});
test('rejects native workspace junction even with safe package metadata',()=>{const f=fixture();f.write('apps/mobile/package.json',{name:'safe',version:'1.0.0'});symlinkSync(join(f.root,'apps/mobile'),join(f.root,'node_modules/safe'),'junction');expect(()=>verifyWebInstallScope(f.root)).toThrow('PATH_OUTSIDE_SCOPE');});
test('rejects leftover mobile install lock entries',()=>{const f=fixture();f.write('node_modules/.package-lock.json',{packages:{'node_modules/@stallorder/mobile':{link:true}}});expect(()=>verifyWebInstallScope(f.root)).toThrow('MOBILE_LOCK_ENTRY');});
test('rejects untracked installed packages and contract identity drift',()=>{const f=fixture();f.write('node_modules/unknown/package.json',{name:'unknown',version:'1.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('PACKAGE_NOT_LOCKED');rmSync(join(f.root,'node_modules/unknown'),{recursive:true});f.write('packages/contracts/package.json',{name:'@stallorder/contracts',version:'9.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('VERSION_DRIFT');});

test('rejects excluded workspace node_modules left by a prior full install',()=>{const f=fixture();f.write('apps/mobile/node_modules/private-native/package.json',{name:'expo',version:'57.0.0'});expect(()=>verifyWebInstallScope(f.root)).toThrow('MOBILE_WORKSPACE_REMAINS');});
test('rejects an owner nested dependency shadow that resolves outside the audited checkout',()=>{const f=fixture();const outside=mkdtempSync(join(tmpdir(),'web-shadow-'));dirs.push(outside);writeFileSync(join(outside,'package.json'),JSON.stringify({name:'zod',version:'4.4.3'}));mkdirSync(join(f.root,'packages/contracts/node_modules'),{recursive:true});symlinkSync(outside,join(f.root,'packages/contracts/node_modules/zod'),'junction');expect(()=>verifyWebInstallScope(f.root)).toThrow('PATH_OUTSIDE_SCOPE');});
test('audits a types-only declared package without requiring a runtime main entry',()=>{const f=fixture();f.write('package.json',{dependencies:{'@stallorder/contracts':'0.1.0',zod:'4.4.3'},devDependencies:{'build-tool':'1.0.0','@types/synthetic':'1.0.0'}});f.write('node_modules/@types/synthetic/package.json',{name:'@types/synthetic',version:'1.0.0',types:'index.d.ts'});f.lock.packages['node_modules/@types/synthetic']={version:'1.0.0'};f.write('package-lock.json',f.lock);expect(verifyWebInstallScope(f.root)).toMatchObject({status:'PASS',rootDevelopmentDependencies:2});});