import {readFileSync} from 'node:fs';
import {expect,test} from 'vitest';
import {assertRootAudit as validateAudit} from './lib/web-release-dependency-audit.mjs';
const assertRootAudit=(audit,exception,now=Date.parse('2026-10-03T10:00:00+08:00'))=>validateAudit(audit,exception,now);
const policy=JSON.parse(readFileSync(new URL('./web-release-audit-exception.json',import.meta.url)));
const lock=JSON.parse(readFileSync(new URL('../package-lock.json',import.meta.url)));
function audit(){return {auditReportVersion:2,metadata:{vulnerabilities:structuredClone(policy.counts)},vulnerabilities:Object.fromEntries(Object.entries(policy.packages).map(([name,p])=>[name,{name,severity:'high',isDirect:p.isDirect,nodes:[p.node],effects:structuredClone(p.effects),range:p.range,via:name==='braces'?[{source:1240992,url:'https://github.com/advisories/GHSA-vfj7-8cjw-p6xm',name:'braces',dependency:'braces',severity:'high',range:'<=3.0.3'}]:structuredClone(p.via)}]))};}
test('exact accepted dev chain remains rejected without explicit exception',()=>{expect(()=>assertRootAudit(audit())).toThrow('VULNERABILITIES');expect(()=>assertRootAudit(audit(),{policy,lock})).not.toThrow();});
test('expired approval and unknown policy cannot pass',()=>{expect(()=>assertRootAudit(audit(),{policy,lock},Date.parse(policy.expiresAt)+1)).toThrow('EXPIRED');expect(()=>assertRootAudit(audit(),{policy:{...policy,advisory:'OTHER'},lock})).toThrow('LOCK_MISMATCH');});
test.each(['advisory','severity','node','extra','count','via','version','error'])('rejects unreviewed exception change %s',kind=>{const a=audit(),l=structuredClone(lock);if(kind==='advisory')a.vulnerabilities.braces.via[0].url='https://github.com/advisories/OTHER';if(kind==='severity')a.vulnerabilities.braces.severity='critical';if(kind==='node')a.vulnerabilities.braces.nodes.push('node_modules/extra/braces');if(kind==='extra')a.vulnerabilities.other={};if(kind==='count')a.metadata.vulnerabilities.high=6;if(kind==='via')a.vulnerabilities.micromatch.via.push('other');if(kind==='version')l.packages['node_modules/braces'].version='3.0.4';if(kind==='error')a.error={code:'EAUDIT'};expect(()=>assertRootAudit(a,{policy,lock:l})).toThrow();});
