import { z } from "zod";

const uuid = z.uuid();
const integer = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const iso = z.iso.datetime();
const hash = z.string().regex(/^[a-f0-9]{64}$/);
const stalls = z.array(uuid).max(50).refine((ids) => ids.every((id, n) => n === 0 || ids[n - 1] < id), "Stall IDs must be sorted and unique");
export const clientScopeSchema = z.strictObject({
  version: z.literal("v1"), environment: z.enum(["local", "preview", "production"]),
  principalKey: hash, sessionEpoch: hash, permissionRevision: hash,
  context: z.discriminatedUnion("kind", [
    z.strictObject({ kind: z.literal("organization"), organizationId: uuid, stallIds: stalls }),
    z.strictObject({ kind: z.literal("platform") }), z.strictObject({ kind: z.literal("applicant") }),
  ]),
});
export type ClientScope = z.infer<typeof clientScopeSchema>;
const page = z.coerce.number().int().min(1).max(999999).default(1);
const pageSize = z.coerce.number().refine((n) => [5, 10, 25, 50, 100].includes(n)).default(5).transform((n) => n as 5 | 10 | 25 | 50 | 100);
export const pageMetaSchema = z.strictObject({ page: integer.min(1), pageSize: z.union([z.literal(5), z.literal(10), z.literal(25), z.literal(50), z.literal(100)]), total: integer, totalPages: integer.min(1), firstItem: integer, lastItem: integer });
const query = z.string().max(80).refine((s) => !/[\x00-\x1f\x7f]/.test(s)).transform((s) => s.trim().normalize("NFC")).default("");
export const catalogReadInputSchema = z.strictObject({ page, pageSize, q: query, locale: z.string().regex(/^[a-z]{2}(?:-[A-Za-z]{2,4})?$/).default("zh-TW"), categoryId: uuid.optional(), groupId: z.union([uuid, z.literal("ungrouped")]).optional(), stallId: uuid.optional(), active: z.enum(["all", "active", "inactive"]).default("all"), sort: z.enum(["catalog", "nameAsc", "nameDesc"]).default("catalog") });
export type CatalogReadInput = z.infer<typeof catalogReadInputSchema>;
export const historyReadInputSchema = z.strictObject({ organizationId: uuid, stallIds: z.array(uuid).max(50).default([]), dateFrom: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), dateTo: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), page, pageSize, sort: z.enum(["createdAtDesc", "createdAtAsc"]).default("createdAtDesc") });
export const applicationStatusSchema = z.enum(["DRAFT", "SUBMITTED", "PENDING_REVIEW", "NEEDS_INFO", "APPROVED", "REJECTED", "WITHDRAWN", "EXPIRED"]);
export const applicationReadInputSchema = z.strictObject({ page, pageSize, status: applicationStatusSchema.optional(), riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "BLOCKED"]).optional(), duplicateReason: z.enum(["DUPLICATE_EMAIL", "DUPLICATE_PHONE", "DUPLICATE_SLUG"]).optional(), reviewer: z.enum(["ASSIGNED", "UNASSIGNED"]).optional(), reviewerId: uuid.optional(), submitted: z.enum(["TODAY", "OLDER_THAN_2_DAYS"]).optional(), sort: z.enum(["review", "submittedAtDesc", "submittedAtAsc"]).default("review") });
export const productListRowSchema = z.strictObject({ id: uuid, categoryId: uuid, groupId: uuid.nullable(), name: z.string(), localizedName: z.string(), translations: z.array(z.strictObject({ locale: z.string(), name: z.string() })), kind: z.enum(["SINGLE", "BUNDLE"]), isActive: z.boolean(), imageUrl: z.string().nullable(), defaultPrice: integer, sortOrder: z.number().int(), assignments: z.array(z.strictObject({ stallId: uuid, isEnabled: z.boolean(), isSoldOut: z.boolean(), soldOutUntil: iso.nullable(), priceOverride: integer.nullable(), stockRemaining: integer.nullable(), stockVersion: integer })) });
export type ProductListRow = z.infer<typeof productListRowSchema>;
export const historyRowSchema = z.strictObject({ id: uuid, orderNo: z.string(), createdAt: iso, stall: z.strictObject({ id: uuid, name: z.string() }), fulfillmentType: z.enum(["TAKEOUT", "DINE_IN", "DELIVERY"]), status: z.enum(["WAITING_CONFIRMATION", "CONFIRMED", "PREPARING", "PACKING", "READY", "COMPLETED", "CANCELLED", "EXPIRED"]), paymentStatus: z.enum(["UNPAID", "PAID", "REFUNDED", "PENDING_RECONCILIATION"]), total: integer });
export type HistoryRow = z.infer<typeof historyRowSchema>;
export const applicationRowSchema = z.strictObject({ id: uuid, applicationNumber: z.string(), merchantName: z.string(), businessType: z.string(), city: z.string().nullable(), status: applicationStatusSchema, submittedAt: iso.nullable(), riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "BLOCKED"]), riskReasonCodes: z.array(z.string()), assignedReviewer: z.strictObject({ id: uuid, displayName: z.string() }).nullable() });
export type ApplicationRow = z.infer<typeof applicationRowSchema>;
export const pageResultSchema = <T extends z.ZodType>(row: T) => z.strictObject({ version: z.literal("v1"), scope: clientScopeSchema, rows: z.array(row), pagination: pageMetaSchema });
export const catalogReadResultSchema = pageResultSchema(productListRowSchema);
const translations = z.array(z.strictObject({ locale: z.string(), name: z.string() }));
const taxonomy = { id: uuid, name: z.string(), sortOrder: z.number().int(), isActive: z.boolean(), translations };
const bundleChoiceSchema = z.strictObject({ id: uuid, choiceGroupId: uuid, componentProductId: uuid, quantity: integer, priceDelta: z.number().int(), isEnabled: z.boolean(), sortOrder: z.number().int(), componentProduct: z.strictObject({ id: uuid, name: z.string(), kind: z.enum(["SINGLE", "BUNDLE"]), isActive: z.boolean() }) });
const completeProductSchema = productListRowSchema.omit({ localizedName: true, assignments: true, translations: true }).extend({ description: z.string(), isOrderDiscountEligible: z.boolean(), isLotteryEligible: z.boolean(), translations: z.array(z.strictObject({ locale: z.string(), name: z.string(), description: z.string() })), stallProducts: z.array(z.strictObject({ id: uuid, stallId: uuid, priceOverride: integer.nullable(), isEnabled: z.boolean(), isSoldOut: z.boolean(), soldOutUntil: iso.nullable(), stockRemaining: integer.nullable(), stockVersion: integer, sortOrder: z.number().int(), checkoutUpsellSelected: z.boolean() })), bundleChoiceGroups: z.array(z.strictObject({ id: uuid, bundleProductId: uuid, name: z.string(), minSelections: integer, maxSelections: integer, sortOrder: z.number().int(), choices: z.array(bundleChoiceSchema) })) });
const noteOptionSchema = z.strictObject({ id: uuid, reusableNoteId: uuid.nullable(), name: z.string(), priceDelta: z.number().int(), sortOrder: z.number().int(), isActive: z.boolean(), translations });
export const catalogEditorResultSchema = z.strictObject({ version: z.literal("v1"), scope: clientScopeSchema, editor: z.strictObject({ organizationId: uuid, operatingMode: z.enum(["SINGLE_STALL", "MULTI_STALL"]), currency: z.string(), stalls: z.array(z.strictObject({ id: uuid, name: z.string(), isActive: z.boolean() })), initialCatalog: z.strictObject({ categories: z.array(z.strictObject(taxonomy)), groups: z.array(z.strictObject({ ...taxonomy, categoryId: uuid })), products: z.array(completeProductSchema) }), initialNoteGroups: z.array(z.strictObject({ ...taxonomy, selectionMode: z.enum(["SINGLE", "MULTIPLE"]), isRequired: z.boolean(), minSelections: integer, maxSelections: integer.nullable(), assignments: z.array(z.strictObject({ productId: uuid })), options: z.array(noteOptionSchema) })), initialReusableNotes: z.array(noteOptionSchema.omit({ reusableNoteId: true }).extend({ linkedOptionCount: integer })), enabledTranslationLocales: z.array(z.enum(["en", "ja", "ko", "vi", "th"])), aiTranslationConfigured: z.boolean(), aiTranslationProviderLabel: z.string(), versionsHref: z.string().optional() }) });
export const historyReadResultSchema = pageResultSchema(historyRowSchema);
export const historyDetailResultSchema = z.strictObject({ version: z.literal("v1"), scope: clientScopeSchema, detail: historyRowSchema.extend({ source: z.string(), origin: z.string(), customerName: z.string().nullable(), customerPhone: z.string().nullable(), tableLabel: z.string().nullable(), subtotal: integer, discountAmount: integer, note: z.string().nullable(), confirmedAt: iso.nullable(), completedAt: iso.nullable(), cancelledAt: iso.nullable(), payment: z.strictObject({ methodLabel: z.string(), status: z.string(), paidAt: iso.nullable() }).nullable(), items: z.array(z.strictObject({ id: uuid, name: z.string(), quantity: integer, unitPrice: integer, note: z.string().nullable() })) }) });
export const applicationReadResultSchema = pageResultSchema(applicationRowSchema);
export type ApplicationReadInput = z.infer<typeof applicationReadInputSchema>;
export const applicationDetailSchema = z.strictObject({
  id: uuid, applicationNumber: z.string(), status: applicationStatusSchema, riskLevel: z.enum(["LOW", "MEDIUM", "HIGH", "BLOCKED"]), riskReasonsJson: z.array(z.string()),
  applicantDisplayName: z.string(), applicantEmail: z.string(), phone: z.string().nullable(), lineId: z.string().nullable(), preferredContactMethod: z.string().nullable(), merchantName: z.string().nullable(), businessType: z.string().nullable(), businessRegistrationNumber: z.string().nullable(), contactName: z.string().nullable(), businessPhone: z.string().nullable(), city: z.string().nullable(), businessAddress: z.string().nullable(), merchantDescription: z.string().nullable(), stallName: z.string().nullable(), stallLocation: z.string().nullable(), requestedSlug: z.string().nullable(), estimatedDailyOrders: integer.nullable(), expectedStartDate: iso.nullable(), requestedPlanCode: z.string(), needsMultipleStaff: z.boolean(), needsKitchenView: z.boolean(), submittedAt: iso.nullable(), reviewedAt: iso.nullable(), publicReviewNote: z.string().nullable(), internalReviewNote: z.string().nullable(),
  assignedReviewer: z.strictObject({ id: uuid, displayName: z.string() }).nullable(),
  applicant: z.strictObject({ providerDisplayKinds: z.array(z.string()), merchantApplications: z.array(z.strictObject({ id: uuid, applicationNumber: z.string(), merchantName: z.string().nullable(), status: applicationStatusSchema, createdAt: iso })) }),
  approvedOrganization: z.strictObject({ id: uuid, businessName: z.string(), status: z.string(), subscription: z.strictObject({ id: uuid, status: z.string(), trialEndsAt: iso.nullable(), planVersion: z.strictObject({ displayName: z.string(), version: integer }) }).nullable(), merchantSetupProgress: z.strictObject({ testOrderCompleted: z.boolean(), goLiveCompleted: z.boolean() }).nullable() }).nullable(),
});
export const applicationDetailResultSchema = z.strictObject({ version: z.literal("v1"), scope: clientScopeSchema, detail: applicationDetailSchema });
export const apiErrorSchema = z.strictObject({ version: z.literal("v1"), code: z.enum(["INVALID_INPUT", "UNAUTHENTICATED", "FORBIDDEN", "NOT_FOUND", "CONFLICT", "RATE_LIMITED", "READ_FAILED"]), message: z.string().max(300), requestId: z.string().max(100), retryable: z.boolean() });
